{
	"persons": {
		"johnsmith" : {
			"FirstName": "John",
			"LastName": "Smith",
			"Legal_First_Name__c": "Johnathan",
			"SSN_Tax_ID__c": "604544806",
			"Hashed_Tax_ID__c": "490e9ad211ce5c40e45ab2928a24a9e1"
		}
	},
	"orgs": {},
	"cases": {
		"simple" : {
			"status_code__c": "50",
			"status__c": "Cancelled",
			"policystatusdate__c": "2017-12-1",
			"modalpremium__c": "221.60",
			"agent_number__c": "Alan123",
			"applicationsigneddate__c": "2017-11-06",
			"underwritersname__c": "MICHAEL MOFFERSON",
			"issuestate__c": "New York",
			"premiummode__c": "Month or Monthly",
			"policynumber__c": "POL9813980",
			"external_id2__c": "POL9813980",
			"name": "Case for John Smith"		
		}
	},
	"feeds": {
		"simple": {
			"primaryInsured": {
				"objectType": "contact",
				"linkRef": "P000874312",
				"fieldMap": {},
				"relatedEntryMap": {},
				"relatedEntryListMap": {}
			},
			"notes": [],
			"insureds": [],
			"parties": [],
			"coverages": [],
			"requirements": [],
			"agents": [],
			"objectType": "PendingCaseEntry",
			"id": null,
			"fieldMap": {
				"status_code__c": {
					"name": "status_code__c",
					"value": "50"
				},
				"status__c": {
					"name": "status__c",
					"value": "Cancelled"
				},
				"lastunderwritingactivitydate__c": {
					"name": "lastunderwritingactivitydate__c",
					"value": "2015-02-17T12:00:00.000-05:00"
				},
				"additional_indicator__c": {
					"name": "additional_indicator__c",
					"value": ""
				},
				"annual_premium__c": {
					"name": "annual_premium__c",
					"value": ""
				},
				"units__c": {
					"name": "units__c",
					"value": ""
				},
				"formalappindicator__c": {
					"name": "formalappindicator__c",
					"value": "True"
				},
				"policystatusdate__c": {
					"name": "policystatusdate__c",
					"value": "2015-01-21T12:00:00.000-05:00"
				},
				"replacementtype__c": {
					"name": "replacementtype__c",
					"value": ""
				},
				"current_tobacco_basis__c": {
					"name": "current_tobacco_basis__c",
					"value": ""
				},
				"coverage_amount__c": {
					"name": "coverage_amount__c",
					"value": ""
				},
				"modalpremium__c": {
					"name": "modalpremium__c",
					"value": "221.60"
				},
				"excesspremium__c": {
					"name": "excesspremium__c",
					"value": ""
				},
				"amount1035__c": {
					"name": "amount1035__c",
					"value": "0.00"
				},
				"product_name__c": {
					"name": "product_name__c",
					"value": "Term 15"
				},
				"applied_for_carrier_class_name__c": {
					"name": "applied_for_carrier_class_name__c",
					"value": ""
				},
				"agent_number__c": {
					"name": "agent_number__c",
					"value": "Alan123"
				},
				"applied_for_carrier_class_table_rating__c": {
					"name": "applied_for_carrier_class_table_rating__c",
					"value": ""
				},
				"applied_for_table_rating__c": {
					"name": "applied_for_table_rating__c",
					"value": ""
				},
				"alternate_indicator__c": {
					"name": "alternate_indicator__c",
					"value": ""
				},
				"pi_issue_age__c": {
					"name": "pi_issue_age__c",
					"value": "60"
				},
				"applicationsigneddate__c": {
					"name": "applicationsigneddate__c",
					"value": "2015-01-06T12:00:00.000-05:00"
				},
				"issuegender__c": {
					"name": "issuegender__c",
					"value": "Female"
				},
				"product_code__c": {
					"name": "product_code__c",
					"value": "13605"
				},
				"is_base_coverage__c": {
					"name": "is_base_coverage__c",
					"value": "true"
				},
				"cashwithappamt__c": {
					"name": "cashwithappamt__c",
					"value": "221.60"
				},
				"suitabilityperformed__c": {
					"name": "suitabilityperformed__c",
					"value": ""
				},
				"underwritersname__c": {
					"name": "underwritersname__c",
					"value": "MICHAEL MOFFERSON"
				},
				"carriercasemanager__c": {
					"name": "carriercasemanager__c",
					"value": "SALLY SOFFERSON (II)"
				},
				"qualifiedplantype__c": {
					"name": "qualifiedplantype__c",
					"value": ""
				},
				"current_underwriting_class__c": {
					"name": "current_underwriting_class__c",
					"value": ""
				},
				"balanceofpremiumdue__c": {
					"name": "balanceofpremiumdue__c",
					"value": ""
				},
				"disability_benefitamount__c": {
					"name": "disability_benefitamount__c",
					"value": ""
				},
				"issuestate__c": {
					"name": "issuestate__c",
					"value": "New York"
				},
				"premiummode__c": {
					"name": "premiummode__c",
					"value": "Month or Monthly"
				},
				"targetpremium__c": {
					"name": "targetpremium__c",
					"value": "2783.07"
				},
				"policynumber__c": {
					"name": "policynumber__c",
					"value": "POL9813980"
				},
				"external_id2__c": {
					"name": "external_Id2__c",
					"value": "POL9813980"
				},
				"name": {
					"name": "name",
					"value": "Case for John Smith"
				}
			},
			"relatedEntryMap": {},
			"relatedEntryListMap": {
				"refcontacts": [{
						"objectType": "contact",
						"linkId": "P000874312",
						"fieldMap": {
							"legal_first_name__c": {
								"name": "legal_first_name__c",
								"value": "Johnathan"
							},
							"lastname": {
								"name": "lastname",
								"value": "Smith"
							},
							"email": {
								"name": "email",
								"value": "jsmith@agentone-bddtest.com"
							},
							"birthdate": {
								"name": "birthdate",
								"value": ""
							},
							"hashed_tax_id__c": {
								"name": "hashed_tax_id__c",
								"value": "490e9ad211ce5c40e45ab2928a24a9e1"
							},
							"ssn_tax_id__c": {
								"name": "ssn_tax_id__c",
								"value": "604544806"
							}
						},
						"relatedEntryMap": {},
						"relatedEntryListMap": {}
					}
				],
				"refaccounts": []
			}
		},
		"regular": {},
		"full": {}
	}
}
