 Active__c,Adapter_Class_Name__c,Adapter_Namespace__c,Display_Name__c,Height__c,Is_Hosted__c,Minimum_Supported_Operating_Systems__c,Minimum_Supported_Resolution__c,Open_New_Window__c,Order__c,Permission_Name__c, URL__c,Width__c,Name
FALSE,iGoAdapter,,iGO e-App,1751px,TRUE,"Windows NT 6.1,iOS 7.1.1,Mac OS X 10.4",,FALSE,1,,<enter URL here>,100%,igo.eapp
FALSE,iGoAdapter,,iGO Illustrations,1751px,TRUE,"Windows NT 6.1,iOS 7.1.1,Mac OS X 10.4",,FALSE,1,,<enter URL here>,100%,igo.illustration
FALSE,iGoAdapter,,iGO eApp Needs Analysis,1751px,TRUE,"Windows NT 6.1,iOS 7.1.1,Mac OS X 10.4",,FALSE,1,,<enter URL here>,100%,igo.needs_analysis
FALSE,iGoAdapter,,Policy Holder Services,1751px,TRUE,"Windows NT 6.1,iOS 7.1.1,Mac OS X 10.4",,FALSE,1,,<enter URL here>,100%,igo.phs