Code,Product Type,Product Line of Business
1,Whole Life,Life
2,Term,Life
3,Universal Life,Life
4,Variable Universal Life,Life
5,Indexed Universal Life,Life
6,Interest Sensitive Whole Life,Life
8,Variable Whole Life,Life
26,Term with Cash Value,Life
37,Guaranteed Insurability Policy,Life
302,Endowment,Life
9,Fixed Annuity,Annuity
10,Variable Annuity,Annuity
11,Indexed Annuity,Annuity
12,Income Replacement,Disability
23,Overhead Expense,Disability
24,Buyout,Disability
33,Open Ended Investment,Annuity
39,Open ended investment policy for Retirement,Annuity
301,Retirement Annuity,Annuity
303,Policy pays out an income stream instead of lump sum,Annuity
415,Life Linked Investment,Annuity
