<AgentOneSettings name="AgentOne Settings Home" label="AgentOne Settings Home" target="#" >
    <Menus name="CUSTOMIZATION FRAMEWORK" label="CUSTOMIZATION FRAMEWORK" target="">
        <Menu name="Entity_Field_List" label="Entity Field List" target="#/EntityFieldList/list" />
        <!-- <Menu name="Field_Mapper" label="Field Mapper" target="#/FieldMapper/list" /> -->
        <Menu name="iGO_Prefill_Mapping" label="iGO Prefill Mapping" target="#/iGoPrefill/list" />
        <Menu name="Name_and_Value_Mapping" label="Name Value Mapping" target="#/NameValueMapping/list" />
        <Menu name="Synchronization_Mapper" label="Sync Mapper" target="#/SyncMapper/list" /> 
    </Menus>
    <Menus name="CONFIGURATION AND GLOBAL SETTINGS" label="CONFIGURATION AND GLOBAL SETTINGS" target="">
        <Menu name="Application_Configuration" label="Application Configuration" target="#/ApplicationCfg/list" />
        <Menu name="Global_Settings" label="Global Settings" target="#/GlobalSetting/view/org" />
        <Menu name="iGO_Settings_Functional" label="iGO Functional Settings" target="#/iGOSettingsFunctional/view/org" />
        <Menu name="Insurance_Tool_Product_Configuration" label="Insurance Tool Product Configuration" target="#/InsuranceToolCfg/list" />
        <Menu name="Insurance_Tool_Registration" label="Insurance Tool Registration" target="#/InsuranceToolReg/list" />
        <Menu name="Relationship_Mappings" label="Relationship Mappings" target="#/RelationshipMap/list" />
        <Menu name="Relationship_Roles" label="Relationship Roles" target="#/RelationshipRole/list" />
    </Menus>
    <Menus name="SERVER CONFIGURATIONS AND SETTINGS" label="SERVER CONFIGURATIONS AND SETTINGS" target="">
        <Menu name="iGO_Settings_Server" label="iGO Server Settings" target="#/iGOSettingsServer/view/org" />
        <Menu name="Plugin_Extension_and_Registration" label="Plugin Extension and Registration" target="#/PluginExtensionReg/list" />
        <Menu name="Source_Application_Configuration" label="Source Application" target="#/SourceApplication/list" />
    </Menus>
</AgentOneSettings>
