FIELD_NAME__C,VALUE__C,TARGET_APP__C,TARGET_VALUE__C,KEY__C
BenefitMode,Annual Calendar,iGO,30,benefitmode-annual calendar@igo
BenefitMode,Annual or Annually,iGO,1,benefitmode-annual or annually@igo
BenefitMode,Any Paymode is allowed,iGO,100,benefitmode-any paymode is allowed@igo
BenefitMode,Bi-Weekly (every two weeks),iGO,7,benefitmode-bi-weekly (every two weeks)@igo
BenefitMode,Day or Daily,iGO,8,benefitmode-day or daily@igo
BenefitMode,Every 10 months,iGO,21,benefitmode-every 10 months@igo
BenefitMode,Every 11 months,iGO,22,benefitmode-every 11 months@igo
BenefitMode,Every 2 months,iGO,15,benefitmode-every 2 months@igo
BenefitMode,Every 4 months,iGO,16,benefitmode-every 4 months@igo
BenefitMode,Every 4 weeks (4 weekly),iGO,12,benefitmode-every 4 weeks (4 weekly)@igo
BenefitMode,Every 5 months,iGO,17,benefitmode-every 5 months@igo
BenefitMode,Every 7 months,iGO,18,benefitmode-every 7 months@igo
BenefitMode,Every 8 months,iGO,19,benefitmode-every 8 months@igo
BenefitMode,Every 9 months,iGO,20,benefitmode-every 9 months@igo
BenefitMode,Every three weeks,iGO,24,benefitmode-every three weeks@igo
BenefitMode,Fiscal Quarterly mode of payment,iGO,23,benefitmode-fiscal quarterly mode of payment@igo
BenefitMode,Hour or Hourly,iGO,51,benefitmode-hour or hourly@igo
BenefitMode,Lifetime,iGO,40,benefitmode-lifetime@igo
BenefitMode,Mixed,iGO,98,benefitmode-mixed@igo
BenefitMode,Month or Monthly,iGO,4,benefitmode-month or monthly@igo
BenefitMode,Monthly for 10 months,iGO,13,benefitmode-monthly for 10 months@igo
BenefitMode,Monthly for 8 months,iGO,14,benefitmode-monthly for 8 months@igo
BenefitMode,Monthly for Nine months,iGO,10,benefitmode-monthly for nine months@igo
BenefitMode,None,iGO,99,benefitmode-none@igo
BenefitMode,Once every 5 years,iGO,31,benefitmode-once every 5 years@igo
BenefitMode,Other,iGO,2147483647,benefitmode-other@igo
BenefitMode,Payment is made once every three years,iGO,41,benefitmode-payment is made once every three years@igo
BenefitMode,Payment made 5 times a year,iGO,29,benefitmode-payment made 5 times a year@igo
BenefitMode,Payments made 10 times a year,iGO,43,benefitmode-payments made 10 times a year@igo
BenefitMode,Payments made 11 times per year.,iGO,26,benefitmode-payments made 11 times per year.@igo
BenefitMode,Payments made 13 times a year,iGO,44,benefitmode-payments made 13 times a year@igo
BenefitMode,Payments made 14 times per year.,iGO,27,benefitmode-payments made 14 times per year.@igo
BenefitMode,Payments made 16 times a year,iGO,45,benefitmode-payments made 16 times a year@igo
BenefitMode,Payments made 18 times a year,iGO,46,benefitmode-payments made 18 times a year@igo
BenefitMode,Payments made 19 times a year,iGO,47,benefitmode-payments made 19 times a year@igo
BenefitMode,Payments made 20 times a year,iGO,48,benefitmode-payments made 20 times a year@igo
BenefitMode,Payments made 21 times a year,iGO,49,benefitmode-payments made 21 times a year@igo
BenefitMode,Payments made 22 times a year,iGO,50,benefitmode-payments made 22 times a year@igo
BenefitMode,Payments made 28 times per year.,iGO,28,benefitmode-payments made 28 times per year.@igo
BenefitMode,Payments made 7 times per year.,iGO,25,benefitmode-payments made 7 times per year.@igo
BenefitMode,Payments made 9 times a year,iGO,42,benefitmode-payments made 9 times a year@igo
BenefitMode,Quarter or Quarterly,iGO,3,benefitmode-quarter or quarterly@igo
BenefitMode,Random,iGO,11,benefitmode-random@igo
BenefitMode,Semi-Annual (twice a year),iGO,2,benefitmode-semi-annual (twice a year)@igo
BenefitMode,Semi-Monthly (twice a month),iGO,5,benefitmode-semi-monthly (twice a month)@igo
BenefitMode,Single Payment,iGO,9,benefitmode-single payment@igo
BenefitMode,Unknown,iGO,0,benefitmode-unknown@igo
BenefitMode,Week or Weekly,iGO,6,benefitmode-week or weekly@igo
BenefitPeriod,"1 year (12 months, 52 weeks, 365 Days)",iGO,6,"benefitperiod-1 year (12 months, 52 weeks, 365 days)@igo"
BenefitPeriod,10 years,iGO,48,benefitperiod-10 years@igo
BenefitPeriod,10 years from date of issue,iGO,25,benefitperiod-10 years from date of issue@igo
BenefitPeriod,100 days,iGO,57,benefitperiod-100 days@igo
BenefitPeriod,1000 days,iGO,60,benefitperiod-1000 days@igo
BenefitPeriod,10-14 years,iGO,14,benefitperiod-10-14 years@igo
BenefitPeriod,11 days,iGO,55,benefitperiod-11 days@igo
BenefitPeriod,15 months,iGO,5,benefitperiod-15 months@igo
BenefitPeriod,15 years,iGO,15,benefitperiod-15 years@igo
BenefitPeriod,1500 days,iGO,61,benefitperiod-1500 days@igo
BenefitPeriod,18 months,iGO,30,benefitperiod-18 months@igo
BenefitPeriod,180 Days,iGO,1,benefitperiod-180 days@igo
BenefitPeriod,2 months (60 days),iGO,28,benefitperiod-2 months (60 days)@igo
BenefitPeriod,2 years (24 months),iGO,7,benefitperiod-2 years (24 months)@igo
BenefitPeriod,20 days,iGO,56,benefitperiod-20 days@igo
BenefitPeriod,20 years,iGO,31,benefitperiod-20 years@igo
BenefitPeriod,200 weeks,iGO,2,benefitperiod-200 weeks@igo
BenefitPeriod,2000 days,iGO,62,benefitperiod-2000 days@igo
BenefitPeriod,25 years,iGO,32,benefitperiod-25 years@igo
BenefitPeriod,25 years from date of issue,iGO,24,benefitperiod-25 years from date of issue@igo
BenefitPeriod,2500 days,iGO,63,benefitperiod-2500 days@igo
BenefitPeriod,2920 days,iGO,64,benefitperiod-2920 days@igo
BenefitPeriod,3 months (90 days),iGO,3,benefitperiod-3 months (90 days)@igo
BenefitPeriod,3 years (36 months),iGO,8,benefitperiod-3 years (36 months)@igo
BenefitPeriod,30 years,iGO,33,benefitperiod-30 years@igo
BenefitPeriod,360 days,iGO,58,benefitperiod-360 days@igo
BenefitPeriod,4 years (48 months),iGO,9,benefitperiod-4 years (48 months)@igo
BenefitPeriod,5 days,iGO,54,benefitperiod-5 days@igo
BenefitPeriod,5 years (60 months),iGO,10,benefitperiod-5 years (60 months)@igo
BenefitPeriod,500 days,iGO,59,benefitperiod-500 days@igo
BenefitPeriod,5-9 years,iGO,13,benefitperiod-5-9 years@igo
BenefitPeriod,6 months (180 days),iGO,4,benefitperiod-6 months (180 days)@igo
BenefitPeriod,6 years,iGO,11,benefitperiod-6 years@igo
BenefitPeriod,7 years,iGO,12,benefitperiod-7 years@igo
BenefitPeriod,9 months (270 days),iGO,29,benefitperiod-9 months (270 days)@igo
BenefitPeriod,Aggregate limit - 15 times monthly income,iGO,21,benefitperiod-aggregate limit - 15 times monthly income@igo
BenefitPeriod,Aggregate limit - 50 months,iGO,22,benefitperiod-aggregate limit - 50 months@igo
BenefitPeriod,Amount specified in Days,iGO,40,benefitperiod-amount specified in days@igo
BenefitPeriod,Benefit Period in Years,iGO,42,benefitperiod-benefit period in years@igo
BenefitPeriod,Benefit that pays a lump sum disability benefit only,iGO,35,benefitperiod-benefit that pays a lump sum disability benefit only@igo
BenefitPeriod,Coverage to age 55,iGO,26,benefitperiod-coverage to age 55@igo
BenefitPeriod,Coverage to age 60,iGO,27,benefitperiod-coverage to age 60@igo
BenefitPeriod,Coverage to age 60 - reduced 50% after age 60,iGO,23,benefitperiod-coverage to age 60 - reduced 50% after age 60@igo
BenefitPeriod,Coverage to age 65,iGO,16,benefitperiod-coverage to age 65@igo
BenefitPeriod,Coverage to age 67,iGO,17,benefitperiod-coverage to age 67@igo
BenefitPeriod,Coverage to Age 75,iGO,43,benefitperiod-coverage to age 75@igo
BenefitPeriod,Coverage to Age 80,iGO,49,benefitperiod-coverage to age 80@igo
BenefitPeriod,Coverage to Age 85,iGO,44,benefitperiod-coverage to age 85@igo
BenefitPeriod,Coverage to policy expiration,iGO,51,benefitperiod-coverage to policy expiration@igo
BenefitPeriod,Coverage to premium paid up,iGO,50,benefitperiod-coverage to premium paid up@igo
BenefitPeriod,Coverage to specified age,iGO,53,benefitperiod-coverage to specified age@igo
BenefitPeriod,Extended - 2 years or to age 50 (reduced 50% to age 65),iGO,19,benefitperiod-extended - 2 years or to age 50 (reduced 50% to age 65)@igo
BenefitPeriod,"Life time if disability commences prior to age 50, otherwise 2 years",iGO,20,"benefitperiod-life time if disability commences prior to age 50, otherwise 2 years@igo"
BenefitPeriod,Lifetime,iGO,18,benefitperiod-lifetime@igo
BenefitPeriod,Limit Variation,iGO,52,benefitperiod-limit variation@igo
BenefitPeriod,Maximum Benefit Period Available,iGO,47,benefitperiod-maximum benefit period available@igo
BenefitPeriod,Other,iGO,2147483647,benefitperiod-other@igo
BenefitPeriod,Period is expressed in Months,iGO,41,benefitperiod-period is expressed in months@igo
BenefitPeriod,Unknown,iGO,0,benefitperiod-unknown@igo
beneperiod_tc,0,ACORD,Unknown,beneperiod_tc-0@acord
beneperiod_tc,1,ACORD,180 Days,beneperiod_tc-1@acord
beneperiod_tc,2,ACORD,200 weeks,beneperiod_tc-2@acord
beneperiod_tc,3,ACORD,3 months (90 days),beneperiod_tc-3@acord
beneperiod_tc,4,ACORD,6 months (180 days),beneperiod_tc-4@acord
beneperiod_tc,5,ACORD,15 months,beneperiod_tc-5@acord
beneperiod_tc,6,ACORD,"1 year (12 months, 52 weeks, 365 Days)",beneperiod_tc-6@acord
beneperiod_tc,7,ACORD,2 years (24 months),beneperiod_tc-7@acord
beneperiod_tc,8,ACORD,3 years (36 months),beneperiod_tc-8@acord
beneperiod_tc,9,ACORD,4 years (48 months),beneperiod_tc-9@acord
beneperiod_tc,10,ACORD,5 years (60 months),beneperiod_tc-10@acord
beneperiod_tc,11,ACORD,6 years,beneperiod_tc-11@acord
beneperiod_tc,12,ACORD,7 years,beneperiod_tc-12@acord
beneperiod_tc,13,ACORD,5-9 years,beneperiod_tc-13@acord
beneperiod_tc,14,ACORD,10-14 years,beneperiod_tc-14@acord
beneperiod_tc,15,ACORD,15 years,beneperiod_tc-15@acord
beneperiod_tc,16,ACORD,Coverage to age 65,beneperiod_tc-16@acord
beneperiod_tc,17,ACORD,Coverage to age 67,beneperiod_tc-17@acord
beneperiod_tc,18,ACORD,Lifetime,beneperiod_tc-18@acord
beneperiod_tc,19,ACORD,Extended - 2 years or to age 50 (reduced 50% to age 65),beneperiod_tc-19@acord
beneperiod_tc,20,ACORD,"Life time if disability commences prior to age 50, otherwise 2 years",beneperiod_tc-20@acord
beneperiod_tc,21,ACORD,Aggregate limit - 15 times monthly income,beneperiod_tc-21@acord
beneperiod_tc,22,ACORD,Aggregate limit - 50 months,beneperiod_tc-22@acord
beneperiod_tc,23,ACORD,Coverage to age 60 - reduced 50% after age 60,beneperiod_tc-23@acord
beneperiod_tc,24,ACORD,25 years from date of issue,beneperiod_tc-24@acord
beneperiod_tc,25,ACORD,10 years from date of issue,beneperiod_tc-25@acord
beneperiod_tc,26,ACORD,Coverage to age 55,beneperiod_tc-26@acord
beneperiod_tc,27,ACORD,Coverage to age 60,beneperiod_tc-27@acord
beneperiod_tc,28,ACORD,2 months (60 days),beneperiod_tc-28@acord
beneperiod_tc,29,ACORD,9 months (270 days),beneperiod_tc-29@acord
beneperiod_tc,30,ACORD,18 months,beneperiod_tc-30@acord
beneperiod_tc,31,ACORD,20 years,beneperiod_tc-31@acord
beneperiod_tc,32,ACORD,25 years,beneperiod_tc-32@acord
beneperiod_tc,33,ACORD,30 years,beneperiod_tc-33@acord
beneperiod_tc,35,ACORD,Benefit that pays a lump sum disability benefit only,beneperiod_tc-35@acord
beneperiod_tc,40,ACORD,Amount specified in Days,beneperiod_tc-40@acord
beneperiod_tc,41,ACORD,Period is expressed in Months,beneperiod_tc-41@acord
beneperiod_tc,42,ACORD,Benefit Period in Years,beneperiod_tc-42@acord
beneperiod_tc,43,ACORD,Coverage to Age 75,beneperiod_tc-43@acord
beneperiod_tc,44,ACORD,Coverage to Age 85,beneperiod_tc-44@acord
beneperiod_tc,47,ACORD,Maximum Benefit Period Available,beneperiod_tc-47@acord
beneperiod_tc,48,ACORD,10 years,beneperiod_tc-48@acord
beneperiod_tc,49,ACORD,Coverage to Age 80,beneperiod_tc-49@acord
beneperiod_tc,50,ACORD,Coverage to premium paid up,beneperiod_tc-50@acord
beneperiod_tc,51,ACORD,Coverage to policy expiration,beneperiod_tc-51@acord
beneperiod_tc,52,ACORD,Limit Variation,beneperiod_tc-52@acord
beneperiod_tc,53,ACORD,Coverage to specified age,beneperiod_tc-53@acord
beneperiod_tc,54,ACORD,5 days,beneperiod_tc-54@acord
beneperiod_tc,55,ACORD,11 days,beneperiod_tc-55@acord
beneperiod_tc,56,ACORD,20 days,beneperiod_tc-56@acord
beneperiod_tc,57,ACORD,100 days,beneperiod_tc-57@acord
beneperiod_tc,58,ACORD,360 days,beneperiod_tc-58@acord
beneperiod_tc,59,ACORD,500 days,beneperiod_tc-59@acord
beneperiod_tc,60,ACORD,1000 days,beneperiod_tc-60@acord
beneperiod_tc,61,ACORD,1500 days,beneperiod_tc-61@acord
beneperiod_tc,62,ACORD,2000 days,beneperiod_tc-62@acord
beneperiod_tc,63,ACORD,2500 days,beneperiod_tc-63@acord
beneperiod_tc,64,ACORD,2920 days,beneperiod_tc-64@acord
beneperiod_tc,2147483647,ACORD,Other,beneperiod_tc-2147483647@acord
boolean_tc,0,ACORD,FALSE,boolean_tc-0@acord
boolean_tc,1,ACORD,TRUE,boolean_tc-1@acord
Citizenship,Application for Landing Immigration,iGO,6,citizenship-application for landing immigration@igo
Citizenship,Citizen,iGO,8,citizenship-citizen@igo
Citizenship,Employee,iGO,4,citizenship-employee@igo
Citizenship,Landed Immigrant,iGO,7,citizenship-landed immigrant@igo
Citizenship,Other,iGO,2147483647,citizenship-other@igo
Citizenship,Permanent Resident,iGO,1,citizenship-permanent resident@igo
Citizenship,Refugee Claimant,iGO,5,citizenship-refugee claimant@igo
Citizenship,Student,iGO,3,citizenship-student@igo
Citizenship,Unknown,iGO,0,citizenship-unknown@igo
Citizenship,Visitor,iGO,2,citizenship-visitor@igo
Country,Afghanistan,iGO,AF,country-afghanistan@igo
Country,Aland Islands,iGO,AX,country-aland islands@igo
Country,Albania,iGO,AL,country-albania@igo
Country,Algeria,iGO,DZ,country-algeria@igo
Country,Andorra,iGO,AD,country-andorra@igo
Country,Angola,iGO,AO,country-angola@igo
Country,Anguilla,iGO,AI,country-anguilla@igo
Country,Antarctica,iGO,AQ,country-antarctica@igo
Country,Antigua and Barbuda,iGO,AG,country-antigua and barbuda@igo
Country,Argentina,iGO,AR,country-argentina@igo
Country,Armenia,iGO,AM,country-armenia@igo
Country,Aruba,iGO,AW,country-aruba@igo
Country,Australia,iGO,AU,country-australia@igo
Country,Austria,iGO,AT,country-austria@igo
Country,Azerbaijan,iGO,AZ,country-azerbaijan@igo
Country,Bahamas,iGO,BS,country-bahamas@igo
Country,Bahrain,iGO,BH,country-bahrain@igo
Country,Bangladesh,iGO,BD,country-bangladesh@igo
Country,Barbados,iGO,BB,country-barbados@igo
Country,Belarus,iGO,BY,country-belarus@igo
Country,Belgium,iGO,BE,country-belgium@igo
Country,Belize,iGO,BZ,country-belize@igo
Country,Benin,iGO,BJ,country-benin@igo
Country,Bermuda,iGO,BM,country-bermuda@igo
Country,Bhutan,iGO,BT,country-bhutan@igo
Country,Bolivia,iGO,BO,country-bolivia@igo
Country,"Bonaire, Sint Eustatius and Saba",iGO,BQ,"country-bonaire, sint eustatius and saba@igo"
Country,Bosnia and Herzegovina,iGO,BA,country-bosnia and herzegovina@igo
Country,Botswana,iGO,BW,country-botswana@igo
Country,Bouvet Island,iGO,BV,country-bouvet island@igo
Country,Brazil,iGO,BR,country-brazil@igo
Country,British Indian Ocean Territory,iGO,IO,country-british indian ocean territory@igo
Country,Brunei Darussalam,iGO,BN,country-brunei darussalam@igo
Country,Bulgaria,iGO,BG,country-bulgaria@igo
Country,Burkina Faso,iGO,BF,country-burkina faso@igo
Country,Burundi,iGO,BI,country-burundi@igo
Country,Cambodia,iGO,KH,country-cambodia@igo
Country,Cameroon,iGO,CM,country-cameroon@igo
Country,Canada,iGO,CA,country-canada@igo
Country,Cape Verde,iGO,CV,country-cape verde@igo
Country,Cayman Islands,iGO,KY,country-cayman islands@igo
Country,Central African Republic,iGO,CF,country-central african republic@igo
Country,Chad,iGO,TD,country-chad@igo
Country,Chile,iGO,CL,country-chile@igo
Country,China,iGO,CN,country-china@igo
Country,Christmas Island,iGO,CX,country-christmas island@igo
Country,Cocos (Keeling) Islands,iGO,CC,country-cocos (keeling) islands@igo
Country,Colombia,iGO,CO,country-colombia@igo
Country,Comoros,iGO,KM,country-comoros@igo
Country,Congo,iGO,CG,country-congo@igo
Country,"Congo, the Democratic Republic of the",iGO,CD,"country-congo, the democratic republic of the@igo"
Country,Cook Islands,iGO,CK,country-cook islands@igo
Country,Costa Rica,iGO,CR,country-costa rica@igo
Country,Cote d'Ivoire,iGO,CI,country-cote d'ivoire@igo
Country,Croatia,iGO,HR,country-croatia@igo
Country,Cuba,iGO,CU,country-cuba@igo
Country,Curacao,iGO,CW,country-curacao@igo
Country,Cyprus,iGO,CY,country-cyprus@igo
Country,Czech Republic,iGO,CZ,country-czech republic@igo
Country,Denmark,iGO,DK,country-denmark@igo
Country,Djibouti,iGO,DJ,country-djibouti@igo
Country,Dominica,iGO,DM,country-dominica@igo
Country,Dominican Republic,iGO,DO,country-dominican republic@igo
Country,Ecuador,iGO,EC,country-ecuador@igo
Country,Egypt,iGO,EG,country-egypt@igo
Country,El Salvador,iGO,SV,country-el salvador@igo
Country,Equatorial Guinea,iGO,GQ,country-equatorial guinea@igo
Country,Eritrea,iGO,ER,country-eritrea@igo
Country,Estonia,iGO,EE,country-estonia@igo
Country,Ethiopia,iGO,ET,country-ethiopia@igo
Country,Falkland Islands (Malvinas),iGO,FK,country-falkland islands (malvinas)@igo
Country,Faroe Islands,iGO,FO,country-faroe islands@igo
Country,Fiji,iGO,FJ,country-fiji@igo
Country,Finland,iGO,FI,country-finland@igo
Country,France,iGO,FR,country-france@igo
Country,French Guiana,iGO,GF,country-french guiana@igo
Country,French Polynesia,iGO,PF,country-french polynesia@igo
Country,French Southern Territories,iGO,TF,country-french southern territories@igo
Country,Gabon,iGO,GA,country-gabon@igo
Country,Gambia,iGO,GM,country-gambia@igo
Country,Georgia,iGO,GE,country-georgia@igo
Country,Germany,iGO,DE,country-germany@igo
Country,Ghana,iGO,GH,country-ghana@igo
Country,Gibraltar,iGO,GI,country-gibraltar@igo
Country,Greece,iGO,GR,country-greece@igo
Country,Greenland,iGO,GL,country-greenland@igo
Country,Grenada,iGO,GD,country-grenada@igo
Country,Guadeloupe,iGO,GP,country-guadeloupe@igo
Country,Guatemala,iGO,GT,country-guatemala@igo
Country,Guernsey,iGO,GG,country-guernsey@igo
Country,Guinea,iGO,GN,country-guinea@igo
Country,Guinea-Bissau,iGO,GW,country-guinea-bissau@igo
Country,Guyana,iGO,GY,country-guyana@igo
Country,Haiti,iGO,HT,country-haiti@igo
Country,Heard Island and McDonald Islands,iGO,HM,country-heard island and mcdonald islands@igo
Country,Holy See (Vatican City State),iGO,VA,country-holy see (vatican city state)@igo
Country,Honduras,iGO,HN,country-honduras@igo
Country,Hungary,iGO,HU,country-hungary@igo
Country,Iceland,iGO,IS,country-iceland@igo
Country,India,iGO,IN,country-india@igo
Country,Indonesia,iGO,ID,country-indonesia@igo
Country,"Iran, Islamic Republic of",iGO,IR,"country-iran, islamic republic of@igo"
Country,Iraq,iGO,IQ,country-iraq@igo
Country,Ireland,iGO,IE,country-ireland@igo
Country,Isle of Man,iGO,IM,country-isle of man@igo
Country,Israel,iGO,IL,country-israel@igo
Country,Italy,iGO,IT,country-italy@igo
Country,Jamaica,iGO,JM,country-jamaica@igo
Country,Japan,iGO,JP,country-japan@igo
Country,Jersey,iGO,JE,country-jersey@igo
Country,Jordan,iGO,JO,country-jordan@igo
Country,Kazakhstan,iGO,KZ,country-kazakhstan@igo
Country,Kenya,iGO,KE,country-kenya@igo
Country,Kiribati,iGO,KI,country-kiribati@igo
Country,"Korea, Democratic People's Republic of",iGO,KP,"country-korea, democratic people's republic of@igo"
Country,"Korea, Republic of",iGO,KR,"country-korea, republic of@igo"
Country,Kuwait,iGO,KW,country-kuwait@igo
Country,Kyrgyzstan,iGO,KG,country-kyrgyzstan@igo
Country,Lao People's Democratic Republic,iGO,LA,country-lao people's democratic republic@igo
Country,Latvia,iGO,LV,country-latvia@igo
Country,Lebanon,iGO,LB,country-lebanon@igo
Country,Lesotho,iGO,LS,country-lesotho@igo
Country,Liberia,iGO,LR,country-liberia@igo
Country,Libya,iGO,LY,country-libya@igo
Country,Liechtenstein,iGO,LI,country-liechtenstein@igo
Country,Lithuania,iGO,LT,country-lithuania@igo
Country,Luxembourg,iGO,LU,country-luxembourg@igo
Country,Macao,iGO,MO,country-macao@igo
Country,"Macedonia, The Former Yugoslav Republic of",iGO,MK,"country-macedonia, the former yugoslav republic of@igo"
Country,Madagascar,iGO,MG,country-madagascar@igo
Country,Malawi,iGO,MW,country-malawi@igo
Country,Malaysia,iGO,MY,country-malaysia@igo
Country,Maldives,iGO,MV,country-maldives@igo
Country,Mali,iGO,ML,country-mali@igo
Country,Malta,iGO,MT,country-malta@igo
Country,Martinique,iGO,MQ,country-martinique@igo
Country,Mauritania,iGO,MR,country-mauritania@igo
Country,Mauritius,iGO,MU,country-mauritius@igo
Country,Mayotte,iGO,YT,country-mayotte@igo
Country,Mexico,iGO,MX,country-mexico@igo
Country,"Moldova, Republic of",iGO,MD,"country-moldova, republic of@igo"
Country,Monaco,iGO,MC,country-monaco@igo
Country,Mongolia,iGO,MN,country-mongolia@igo
Country,Montenegro,iGO,ME,country-montenegro@igo
Country,Montserrat,iGO,MS,country-montserrat@igo
Country,Morocco,iGO,MA,country-morocco@igo
Country,Mozambique,iGO,MZ,country-mozambique@igo
Country,Myanmar,iGO,MM,country-myanmar@igo
Country,Namibia,iGO,NA,country-namibia@igo
Country,Nauru,iGO,NR,country-nauru@igo
Country,Nepal,iGO,NP,country-nepal@igo
Country,Netherlands,iGO,NL,country-netherlands@igo
Country,New Caledonia,iGO,NC,country-new caledonia@igo
Country,New Zealand,iGO,NZ,country-new zealand@igo
Country,Nicaragua,iGO,NI,country-nicaragua@igo
Country,Niger,iGO,NE,country-niger@igo
Country,Nigeria,iGO,NG,country-nigeria@igo
Country,Niue,iGO,NU,country-niue@igo
Country,Norfolk Island,iGO,NF,country-norfolk island@igo
Country,Norway,iGO,NO,country-norway@igo
Country,Oman,iGO,OM,country-oman@igo
Country,Pakistan,iGO,PK,country-pakistan@igo
Country,"Palestinian Territory, Occupied",iGO,PS,"country-palestinian territory, occupied@igo"
Country,Panama (also known as Canal Zone),iGO,PA,country-panama (also known as canal zone)@igo
Country,Papua New Guinea,iGO,PG,country-papua new guinea@igo
Country,Paraguay,iGO,PY,country-paraguay@igo
Country,Peru,iGO,PE,country-peru@igo
Country,Philippines,iGO,PH,country-philippines@igo
Country,Pitcairn,iGO,PN,country-pitcairn@igo
Country,Poland,iGO,PL,country-poland@igo
Country,Portugal,iGO,PT,country-portugal@igo
Country,Qatar,iGO,QA,country-qatar@igo
Country,Reunion,iGO,RE,country-reunion@igo
Country,Romania,iGO,RO,country-romania@igo
Country,Russian Federation,iGO,RU,country-russian federation@igo
Country,Rwanda,iGO,RW,country-rwanda@igo
Country,Saint Barthelemy,iGO,BL,country-saint barthelemy@igo
Country,"Saint Helena, Ascension and Tristan da Cunha",iGO,SH,"country-saint helena, ascension and tristan da cunha@igo"
Country,Saint Kitts and Nevis,iGO,KN,country-saint kitts and nevis@igo
Country,Saint Lucia,iGO,LC,country-saint lucia@igo
Country,Saint Martin (French Part),iGO,MF,country-saint martin (french part)@igo
Country,Saint Pierre and Miquelon,iGO,PM,country-saint pierre and miquelon@igo
Country,Saint Vincent and the Grenadines,iGO,VC,country-saint vincent and the grenadines@igo
Country,Samoa,iGO,WS,country-samoa@igo
Country,San Marino,iGO,SM,country-san marino@igo
Country,Sao Tome and Principe,iGO,ST,country-sao tome and principe@igo
Country,Saudi Arabia,iGO,SA,country-saudi arabia@igo
Country,Senegal,iGO,SN,country-senegal@igo
Country,Serbia,iGO,RS,country-serbia@igo
Country,Seychelles,iGO,SC,country-seychelles@igo
Country,Sierra Leone,iGO,SL,country-sierra leone@igo
Country,Singapore,iGO,SG,country-singapore@igo
Country,Sint Maarten (Dutch Part),iGO,SX,country-sint maarten (dutch part)@igo
Country,Slovakia,iGO,SK,country-slovakia@igo
Country,Slovenia,iGO,SI,country-slovenia@igo
Country,Solomon Islands,iGO,SB,country-solomon islands@igo
Country,Somalia,iGO,SO,country-somalia@igo
Country,South Africa,iGO,ZA,country-south africa@igo
Country,South Georgia and the South Sandwich Islands,iGO,GS,country-south georgia and the south sandwich islands@igo
Country,South Sudan,iGO,SS,country-south sudan@igo
Country,Spain,iGO,ES,country-spain@igo
Country,Sri Lanka,iGO,LK,country-sri lanka@igo
Country,Sudan,iGO,SD,country-sudan@igo
Country,Suriname,iGO,SR,country-suriname@igo
Country,Svalbard and Jan Mayen,iGO,SJ,country-svalbard and jan mayen@igo
Country,Swaziland,iGO,SZ,country-swaziland@igo
Country,Sweden,iGO,SE,country-sweden@igo
Country,Switzerland,iGO,CH,country-switzerland@igo
Country,Syrian Arab Republic,iGO,SY,country-syrian arab republic@igo
Country,"Taiwan, Province of China",iGO,TW,"country-taiwan, province of china@igo"
Country,Tajikistan,iGO,TJ,country-tajikistan@igo
Country,"Tanzania, United Republic of",iGO,TZ,"country-tanzania, united republic of@igo"
Country,Thailand,iGO,TH,country-thailand@igo
Country,Timor-Leste,iGO,TL,country-timor-leste@igo
Country,Togo,iGO,TG,country-togo@igo
Country,Tokelau,iGO,TK,country-tokelau@igo
Country,Tonga,iGO,TO,country-tonga@igo
Country,Trinidad and Tobago,iGO,TT,country-trinidad and tobago@igo
Country,Tunisia,iGO,TN,country-tunisia@igo
Country,Turkey,iGO,TR,country-turkey@igo
Country,Turkmenistan,iGO,TM,country-turkmenistan@igo
Country,Turks and Caicos Islands,iGO,TC,country-turks and caicos islands@igo
Country,Tuvalu,iGO,TV,country-tuvalu@igo
Country,Uganda,iGO,UG,country-uganda@igo
Country,Ukraine,iGO,UA,country-ukraine@igo
Country,United Arab Emirates,iGO,AE,country-united arab emirates@igo
Country,United Kingdom,iGO,GB,country-united kingdom@igo
Country,United Republic of Tanzania,iGO,TZ,country-united republic of tanzania@igo
Country,United States of America,iGO,US,country-united states of america@igo
Country,United States,iGO,US,country-united states@igo
Country,Uruguay,iGO,UY,country-uruguay@igo
Country,Uzbekistan,iGO,UZ,country-uzbekistan@igo
Country,Vanuatu,iGO,VU,country-vanuatu@igo
Country,Venezuela,iGO,VE,country-venezuela@igo
Country,Viet Nam,iGO,VN,country-viet nam@igo
Country,"Virgin Islands, British",iGO,VG,"country-virgin islands, british@igo"
Country,Wallis and Futuna,iGO,WF,country-wallis and futuna@igo
Country,Western Sahara,iGO,EH,country-western sahara@igo
Country,Yemen,iGO,YE,country-yemen@igo
Country,Yugoslavia,iGO,MK,country-yugoslavia@igo
Country,Zambia,iGO,ZM,country-zambia@igo
Country,Zimbabwe,iGO,ZW,country-zimbabwe@igo
Country_to_ACORD,Afghanistan,iGO,93,country_to_acord-afghanistan@igo
Country_to_ACORD,Aland Islands,iGO,248,country_to_acord-aland islands@igo
Country_to_ACORD,Albania,iGO,355,country_to_acord-albania@igo
Country_to_ACORD,Algeria,iGO,213,country_to_acord-algeria@igo
Country_to_ACORD,American Samoa,iGO,684,country_to_acord-american samoa@igo
Country_to_ACORD,Andorra,iGO,376,country_to_acord-andorra@igo
Country_to_ACORD,Angola,iGO,244,country_to_acord-angola@igo
Country_to_ACORD,Anguilla,iGO,1001,country_to_acord-anguilla@igo
Country_to_ACORD,Antarctica,iGO,672,country_to_acord-antarctica@igo
Country_to_ACORD,Antigua and Barbuda,iGO,268,country_to_acord-antigua and barbuda@igo
Country_to_ACORD,Argentina,iGO,54,country_to_acord-argentina@igo
Country_to_ACORD,Armenia,iGO,374,country_to_acord-armenia@igo
Country_to_ACORD,Aruba,iGO,297,country_to_acord-aruba@igo
Country_to_ACORD,Australia,iGO,61,country_to_acord-australia@igo
Country_to_ACORD,Austria,iGO,43,country_to_acord-austria@igo
Country_to_ACORD,Azerbaijan,iGO,994,country_to_acord-azerbaijan@igo
Country_to_ACORD,Bahamas,iGO,242,country_to_acord-bahamas@igo
Country_to_ACORD,Bahrain,iGO,973,country_to_acord-bahrain@igo
Country_to_ACORD,Bangladesh,iGO,880,country_to_acord-bangladesh@igo
Country_to_ACORD,Barbados,iGO,246,country_to_acord-barbados@igo
Country_to_ACORD,Belarus,iGO,375,country_to_acord-belarus@igo
Country_to_ACORD,Belgium,iGO,32,country_to_acord-belgium@igo
Country_to_ACORD,Belize,iGO,501,country_to_acord-belize@igo
Country_to_ACORD,Benin,iGO,229,country_to_acord-benin@igo
Country_to_ACORD,Bermuda,iGO,441,country_to_acord-bermuda@igo
Country_to_ACORD,Bhutan,iGO,975,country_to_acord-bhutan@igo
Country_to_ACORD,Bolivia,iGO,591,country_to_acord-bolivia@igo
Country_to_ACORD,Bonaire Sint Eustatius and Saba,iGO,535,country_to_acord-bonaire sint eustatius and saba@igo
Country_to_ACORD,Bosnia and Herzegovina,iGO,387,country_to_acord-bosnia and herzegovina@igo
Country_to_ACORD,Botswana,iGO,267,country_to_acord-botswana@igo
Country_to_ACORD,Bouvet Island,iGO,1009,country_to_acord-bouvet island@igo
Country_to_ACORD,Brazil,iGO,55,country_to_acord-brazil@igo
Country_to_ACORD,British Indian Ocean Territory,iGO,1011,country_to_acord-british indian ocean territory@igo
Country_to_ACORD,British Virgin Islands,iGO,284,country_to_acord-british virgin islands@igo
Country_to_ACORD,Brunei Darussalam,iGO,673,country_to_acord-brunei darussalam@igo
Country_to_ACORD,Bulgaria,iGO,359,country_to_acord-bulgaria@igo
Country_to_ACORD,Burkina Faso,iGO,226,country_to_acord-burkina faso@igo
Country_to_ACORD,Burundi,iGO,257,country_to_acord-burundi@igo
Country_to_ACORD,Cambodia,iGO,855,country_to_acord-cambodia@igo
Country_to_ACORD,Cameroon,iGO,237,country_to_acord-cameroon@igo
Country_to_ACORD,Canada,iGO,2,country_to_acord-canada@igo
Country_to_ACORD,Cape Verde,iGO,238,country_to_acord-cape verde@igo
Country_to_ACORD,Cayman Islands,iGO,345,country_to_acord-cayman islands@igo
Country_to_ACORD,Central African Republic,iGO,236,country_to_acord-central african republic@igo
Country_to_ACORD,Chad,iGO,235,country_to_acord-chad@igo
Country_to_ACORD,Chile,iGO,56,country_to_acord-chile@igo
Country_to_ACORD,China,iGO,86,country_to_acord-china@igo
Country_to_ACORD,Christmas Island,iGO,1024,country_to_acord-christmas island@igo
Country_to_ACORD,Cocos (Keeling) Islands,iGO,1007,country_to_acord-cocos (keeling) islands@igo
Country_to_ACORD,Colombia,iGO,57,country_to_acord-colombia@igo
Country_to_ACORD,Comoros,iGO,269,country_to_acord-comoros@igo
Country_to_ACORD,Congo,iGO,1027,country_to_acord-congo@igo
Country_to_ACORD,Cook Islands,iGO,682,country_to_acord-cook islands@igo
Country_to_ACORD,Costa Rica,iGO,506,country_to_acord-costa rica@igo
Country_to_ACORD,Cote d'Ivoire,iGO,1003,country_to_acord-cote d'ivoire@igo
Country_to_ACORD,Croatia,iGO,385,country_to_acord-croatia@igo
Country_to_ACORD,Cuba,iGO,53,country_to_acord-cuba@igo
Country_to_ACORD,Curacao,iGO,1026,country_to_acord-curacao@igo
Country_to_ACORD,Cyprus,iGO,357,country_to_acord-cyprus@igo
Country_to_ACORD,Czech Republic,iGO,420,country_to_acord-czech republic@igo
Country_to_ACORD,Democratic People's Republic of Korea,iGO,952,country_to_acord-democratic people's republic of korea@igo
Country_to_ACORD,Denmark,iGO,45,country_to_acord-denmark@igo
Country_to_ACORD,Djibouti,iGO,253,country_to_acord-djibouti@igo
Country_to_ACORD,Dominica,iGO,767,country_to_acord-dominica@igo
Country_to_ACORD,Dominican Republic,iGO,809,country_to_acord-dominican republic@igo
Country_to_ACORD,Ecuador,iGO,593,country_to_acord-ecuador@igo
Country_to_ACORD,Egypt,iGO,20,country_to_acord-egypt@igo
Country_to_ACORD,El Salvador,iGO,503,country_to_acord-el salvador@igo
Country_to_ACORD,Equatorial Guinea,iGO,240,country_to_acord-equatorial guinea@igo
Country_to_ACORD,Eritrea,iGO,1004,country_to_acord-eritrea@igo
Country_to_ACORD,Estonia,iGO,372,country_to_acord-estonia@igo
Country_to_ACORD,Ethiopia,iGO,251,country_to_acord-ethiopia@igo
Country_to_ACORD,Falkland Islands,iGO,500,country_to_acord-falkland islands@igo
Country_to_ACORD,Falkland Islands (Malvinas),iGO,500,country_to_acord-falkland islands (malvinas)@igo
Country_to_ACORD,Faroe Islands,iGO,298,country_to_acord-faroe islands@igo
Country_to_ACORD,Federated States of Micronesia,iGO,695,country_to_acord-federated states of micronesia@igo
Country_to_ACORD,Fiji,iGO,679,country_to_acord-fiji@igo
Country_to_ACORD,Finland,iGO,358,country_to_acord-finland@igo
Country_to_ACORD,France,iGO,33,country_to_acord-france@igo
Country_to_ACORD,French Guiana,iGO,594,country_to_acord-french guiana@igo
Country_to_ACORD,French Polynesia,iGO,689,country_to_acord-french polynesia@igo
Country_to_ACORD,French Southern Territories,iGO,1015,country_to_acord-french southern territories@igo
Country_to_ACORD,Gabon,iGO,241,country_to_acord-gabon@igo
Country_to_ACORD,Gambia,iGO,220,country_to_acord-gambia@igo
Country_to_ACORD,Georgia,iGO,995,country_to_acord-georgia@igo
Country_to_ACORD,Germany,iGO,49,country_to_acord-germany@igo
Country_to_ACORD,Ghana,iGO,233,country_to_acord-ghana@igo
Country_to_ACORD,Gibraltar,iGO,350,country_to_acord-gibraltar@igo
Country_to_ACORD,Greece,iGO,30,country_to_acord-greece@igo
Country_to_ACORD,Greenland,iGO,299,country_to_acord-greenland@igo
Country_to_ACORD,Grenada,iGO,473,country_to_acord-grenada@igo
Country_to_ACORD,Guadeloupe,iGO,590,country_to_acord-guadeloupe@igo
Country_to_ACORD,Guam,iGO,671,country_to_acord-guam@igo
Country_to_ACORD,Guatemala,iGO,502,country_to_acord-guatemala@igo
Country_to_ACORD,Guernsey,iGO,360,country_to_acord-guernsey@igo
Country_to_ACORD,Guinea,iGO,224,country_to_acord-guinea@igo
Country_to_ACORD,Guinea-Bissau,iGO,270,country_to_acord-guinea-bissau@igo
Country_to_ACORD,Guyana,iGO,592,country_to_acord-guyana@igo
Country_to_ACORD,Haiti,iGO,509,country_to_acord-haiti@igo
Country_to_ACORD,Heard Island and McDonald Islands,iGO,1016,country_to_acord-heard island and mcdonald islands@igo
Country_to_ACORD,Holy See (Vatican City State),iGO,1029,country_to_acord-holy see (vatican city state)@igo
Country_to_ACORD,Honduras,iGO,504,country_to_acord-honduras@igo
Country_to_ACORD,Hong Kong,iGO,852,country_to_acord-hong kong@igo
Country_to_ACORD,Hungary,iGO,36,country_to_acord-hungary@igo
Country_to_ACORD,Iceland,iGO,354,country_to_acord-iceland@igo
Country_to_ACORD,India,iGO,91,country_to_acord-india@igo
Country_to_ACORD,Indonesia,iGO,62,country_to_acord-indonesia@igo
Country_to_ACORD,Iran,iGO,98,country_to_acord-iran@igo
Country_to_ACORD,Iraq,iGO,964,country_to_acord-iraq@igo
Country_to_ACORD,Ireland,iGO,353,country_to_acord-ireland@igo
Country_to_ACORD,Islamic Republic of Iran,iGO,98,country_to_acord-islamic republic of iran@igo
Country_to_ACORD,Isle of Man,iGO,1035,country_to_acord-isle of man@igo
Country_to_ACORD,Israel,iGO,972,country_to_acord-israel@igo
Country_to_ACORD,Italy,iGO,39,country_to_acord-italy@igo
Country_to_ACORD,Jamaica,iGO,876,country_to_acord-jamaica@igo
Country_to_ACORD,Japan,iGO,81,country_to_acord-japan@igo
Country_to_ACORD,Jersey,iGO,1034,country_to_acord-jersey@igo
Country_to_ACORD,Jordan,iGO,962,country_to_acord-jordan@igo
Country_to_ACORD,Kazakhstan,iGO,1005,country_to_acord-kazakhstan@igo
Country_to_ACORD,Kenya,iGO,254,country_to_acord-kenya@igo
Country_to_ACORD,Kiribati,iGO,686,country_to_acord-kiribati@igo
Country_to_ACORD,Kosovo,iGO,390,country_to_acord-kosovo@igo
Country_to_ACORD,Kuwait,iGO,965,country_to_acord-kuwait@igo
Country_to_ACORD,Kyrgyzstan,iGO,1006,country_to_acord-kyrgyzstan@igo
Country_to_ACORD,Lao People's Democratic Republic,iGO,856,country_to_acord-lao people's democratic republic@igo
Country_to_ACORD,Latvia,iGO,371,country_to_acord-latvia@igo
Country_to_ACORD,Lebanon,iGO,961,country_to_acord-lebanon@igo
Country_to_ACORD,Lesotho,iGO,266,country_to_acord-lesotho@igo
Country_to_ACORD,Liberia,iGO,231,country_to_acord-liberia@igo
Country_to_ACORD,Libya,iGO,218,country_to_acord-libya@igo
Country_to_ACORD,Liechtenstein,iGO,423,country_to_acord-liechtenstein@igo
Country_to_ACORD,Lithuania,iGO,370,country_to_acord-lithuania@igo
Country_to_ACORD,Luxembourg,iGO,352,country_to_acord-luxembourg@igo
Country_to_ACORD,Macao,iGO,853,country_to_acord-macao@igo
Country_to_ACORD,Madagascar,iGO,261,country_to_acord-madagascar@igo
Country_to_ACORD,Malawi,iGO,265,country_to_acord-malawi@igo
Country_to_ACORD,Malaysia,iGO,60,country_to_acord-malaysia@igo
Country_to_ACORD,Maldives,iGO,1023,country_to_acord-maldives@igo
Country_to_ACORD,Mali,iGO,223,country_to_acord-mali@igo
Country_to_ACORD,Malta,iGO,356,country_to_acord-malta@igo
Country_to_ACORD,Marshall Islands,iGO,694,country_to_acord-marshall islands@igo
Country_to_ACORD,Martinique,iGO,596,country_to_acord-martinique@igo
Country_to_ACORD,Mauritania,iGO,222,country_to_acord-mauritania@igo
Country_to_ACORD,Mauritius,iGO,230,country_to_acord-mauritius@igo
Country_to_ACORD,Mayotte,iGO,1017,country_to_acord-mayotte@igo
Country_to_ACORD,Mexico,iGO,52,country_to_acord-mexico@igo
Country_to_ACORD,Monaco,iGO,1028,country_to_acord-monaco@igo
Country_to_ACORD,Mongolia,iGO,1008,country_to_acord-mongolia@igo
Country_to_ACORD,Montenegro,iGO,1037,country_to_acord-montenegro@igo
Country_to_ACORD,Montserrat,iGO,664,country_to_acord-montserrat@igo
Country_to_ACORD,Morocco,iGO,212,country_to_acord-morocco@igo
Country_to_ACORD,Mozambique,iGO,258,country_to_acord-mozambique@igo
Country_to_ACORD,Myanmar,iGO,950,country_to_acord-myanmar@igo
Country_to_ACORD,Namibia,iGO,264,country_to_acord-namibia@igo
Country_to_ACORD,Nauru,iGO,674,country_to_acord-nauru@igo
Country_to_ACORD,Nepal,iGO,977,country_to_acord-nepal@igo
Country_to_ACORD,Netherlands,iGO,31,country_to_acord-netherlands@igo
Country_to_ACORD,Netherlands Antilles,iGO,599,country_to_acord-netherlands antilles@igo
Country_to_ACORD,New Caledonia,iGO,687,country_to_acord-new caledonia@igo
Country_to_ACORD,New Zealand,iGO,64,country_to_acord-new zealand@igo
Country_to_ACORD,Nicaragua,iGO,505,country_to_acord-nicaragua@igo
Country_to_ACORD,Niger,iGO,227,country_to_acord-niger@igo
Country_to_ACORD,Nigeria,iGO,234,country_to_acord-nigeria@igo
Country_to_ACORD,Niue,iGO,683,country_to_acord-niue@igo
Country_to_ACORD,Norfolk Island,iGO,1025,country_to_acord-norfolk island@igo
Country_to_ACORD,North Yemen,iGO,1038,country_to_acord-north yemen@igo
Country_to_ACORD,Northern Mariana Islands,iGO,691,country_to_acord-northern mariana islands@igo
Country_to_ACORD,Norway,iGO,47,country_to_acord-norway@igo
Country_to_ACORD,NZ,iGO,64,country_to_acord-nz@igo
Country_to_ACORD,Occupied Palestinian Territory,iGO,1032,country_to_acord-occupied palestinian territory@igo
Country_to_ACORD,Oman,iGO,968,country_to_acord-oman@igo
Country_to_ACORD,Other,iGO,2147483647,country_to_acord-other@igo
Country_to_ACORD,Pakistan,iGO,92,country_to_acord-pakistan@igo
Country_to_ACORD,Palau,iGO,693,country_to_acord-palau@igo
Country_to_ACORD,Panama (also known as Canal Zone),iGO,1002,country_to_acord-panama (also known as canal zone)@igo
Country_to_ACORD,Papua New Guinea,iGO,675,country_to_acord-papua new guinea@igo
Country_to_ACORD,Paraguay,iGO,595,country_to_acord-paraguay@igo
Country_to_ACORD,Peru,iGO,51,country_to_acord-peru@igo
Country_to_ACORD,Philippines,iGO,63,country_to_acord-philippines@igo
Country_to_ACORD,Pitcairn,iGO,1018,country_to_acord-pitcairn@igo
Country_to_ACORD,Poland,iGO,48,country_to_acord-poland@igo
Country_to_ACORD,Portugal,iGO,351,country_to_acord-portugal@igo
Country_to_ACORD,Puerto Rico,iGO,510,country_to_acord-puerto rico@igo
Country_to_ACORD,Qatar,iGO,974,country_to_acord-qatar@igo
Country_to_ACORD,Republic of Korea,iGO,951,country_to_acord-republic of korea@igo
Country_to_ACORD,Republic of Moldova,iGO,373,country_to_acord-republic of moldova@igo
Country_to_ACORD,Reunion,iGO,262,country_to_acord-reunion@igo
Country_to_ACORD,Romania,iGO,40,country_to_acord-romania@igo
Country_to_ACORD,Russia,iGO,7,country_to_acord-russia@igo
Country_to_ACORD,Russian Federation,iGO,7,country_to_acord-russian federation@igo
Country_to_ACORD,Rwanda,iGO,250,country_to_acord-rwanda@igo
Country_to_ACORD,Saint Barthelemy,iGO,652,country_to_acord-saint barthelemy@igo
Country_to_ACORD,Saint Helena Ascension and Tristan da Cunha,iGO,290,country_to_acord-saint helena ascension and tristan da cunha@igo
Country_to_ACORD,Saint Kitts and Nevis,iGO,869,country_to_acord-saint kitts and nevis@igo
Country_to_ACORD,Saint Lucia,iGO,758,country_to_acord-saint lucia@igo
Country_to_ACORD,Saint Martin (French Part),iGO,663,country_to_acord-saint martin (french part)@igo
Country_to_ACORD,Saint Pierre and Miquelon,iGO,508,country_to_acord-saint pierre and miquelon@igo
Country_to_ACORD,Saint Vincent and the Grenadines,iGO,784,country_to_acord-saint vincent and the grenadines@igo
Country_to_ACORD,Samoa,iGO,1013,country_to_acord-samoa@igo
Country_to_ACORD,San Marino,iGO,378,country_to_acord-san marino@igo
Country_to_ACORD,Sao Tome and Principe,iGO,239,country_to_acord-sao tome and principe@igo
Country_to_ACORD,Saudi Arabia,iGO,966,country_to_acord-saudi arabia@igo
Country_to_ACORD,Senegal,iGO,221,country_to_acord-senegal@igo
Country_to_ACORD,Serbia,iGO,1036,country_to_acord-serbia@igo
Country_to_ACORD,Seychelles,iGO,1010,country_to_acord-seychelles@igo
Country_to_ACORD,Sierra Leone,iGO,232,country_to_acord-sierra leone@igo
Country_to_ACORD,Singapore,iGO,65,country_to_acord-singapore@igo
Country_to_ACORD,Sint Maarten (Dutch Part),iGO,534,country_to_acord-sint maarten (dutch part)@igo
Country_to_ACORD,Slovakia,iGO,421,country_to_acord-slovakia@igo
Country_to_ACORD,Slovenia,iGO,386,country_to_acord-slovenia@igo
Country_to_ACORD,Solomon Islands,iGO,677,country_to_acord-solomon islands@igo
Country_to_ACORD,Somalia,iGO,252,country_to_acord-somalia@igo
Country_to_ACORD,South Africa,iGO,27,country_to_acord-south africa@igo
Country_to_ACORD,South Georgia and the South Sandwich Islands,iGO,512,country_to_acord-south georgia and the south sandwich islands@igo
Country_to_ACORD,South Sudan,iGO,728,country_to_acord-south sudan@igo
Country_to_ACORD,South Yemen,iGO,1039,country_to_acord-south yemen@igo
Country_to_ACORD,Spain,iGO,34,country_to_acord-spain@igo
Country_to_ACORD,Sri Lanka,iGO,94,country_to_acord-sri lanka@igo
Country_to_ACORD,Sudan,iGO,249,country_to_acord-sudan@igo
Country_to_ACORD,Suriname,iGO,597,country_to_acord-suriname@igo
Country_to_ACORD,Svalbard and Jan Mayen,iGO,1019,country_to_acord-svalbard and jan mayen@igo
Country_to_ACORD,Swaziland,iGO,1031,country_to_acord-swaziland@igo
Country_to_ACORD,Sweden,iGO,46,country_to_acord-sweden@igo
Country_to_ACORD,Switzerland,iGO,41,country_to_acord-switzerland@igo
Country_to_ACORD,Syrian Arab Republic,iGO,963,country_to_acord-syrian arab republic@igo
Country_to_ACORD,Taiwan Province of China,iGO,886,country_to_acord-taiwan province of china@igo
Country_to_ACORD,Tajikistan,iGO,992,country_to_acord-tajikistan@igo
Country_to_ACORD,Tanzania,iGO,255,country_to_acord-tanzania@igo
Country_to_ACORD,Thailand,iGO,66,country_to_acord-thailand@igo
Country_to_ACORD,The Democratic Republic of the Congo,iGO,271,country_to_acord-the democratic republic of the congo@igo
Country_to_ACORD,The Former Yugoslav Republic of Macedonia,iGO,389,country_to_acord-the former yugoslav republic of macedonia@igo
Country_to_ACORD,Timor-Leste,iGO,1014,country_to_acord-timor-leste@igo
Country_to_ACORD,Togo,iGO,228,country_to_acord-togo@igo
Country_to_ACORD,Tokelau,iGO,1020,country_to_acord-tokelau@igo
Country_to_ACORD,Tonga,iGO,676,country_to_acord-tonga@igo
Country_to_ACORD,Trinidad and Tobago,iGO,868,country_to_acord-trinidad and tobago@igo
Country_to_ACORD,Tunisia,iGO,216,country_to_acord-tunisia@igo
Country_to_ACORD,Turkey,iGO,90,country_to_acord-turkey@igo
Country_to_ACORD,Turkmenistan,iGO,993,country_to_acord-turkmenistan@igo
Country_to_ACORD,Turks and Caicos Islands,iGO,649,country_to_acord-turks and caicos islands@igo
Country_to_ACORD,Tuvalu,iGO,688,country_to_acord-tuvalu@igo
Country_to_ACORD,Uganda,iGO,256,country_to_acord-uganda@igo
Country_to_ACORD,UK,iGO,44,country_to_acord-uk@igo
Country_to_ACORD,Ukraine,iGO,380,country_to_acord-ukraine@igo
Country_to_ACORD,Union of Soviet Socialist Republics,iGO,1040,country_to_acord-union of soviet socialist republics@igo
Country_to_ACORD,United Arab Emirates,iGO,971,country_to_acord-united arab emirates@igo
Country_to_ACORD,United Kingdom,iGO,44,country_to_acord-united kingdom@igo
Country_to_ACORD,United Republic of Tanzania,iGO,255,country_to_acord-united republic of tanzania@igo
Country_to_ACORD,United States,iGO,1,country_to_acord-united states@igo
Country_to_ACORD,United States Minor Outlying Islands,iGO,1021,country_to_acord-united states minor outlying islands@igo
Country_to_ACORD,United States of America,iGO,1,country_to_acord-united states of america@igo
Country_to_ACORD,Unknown,iGO,0,country_to_acord-unknown@igo
Country_to_ACORD,Uruguay,iGO,598,country_to_acord-uruguay@igo
Country_to_ACORD,US,iGO,1,country_to_acord-us@igo
Country_to_ACORD,US Virgin Islands,iGO,511,country_to_acord-us virgin islands@igo
Country_to_ACORD,USA,iGO,1,country_to_acord-usa@igo
Country_to_ACORD,Uzbekistan,iGO,998,country_to_acord-uzbekistan@igo
Country_to_ACORD,Vanuatu,iGO,678,country_to_acord-vanuatu@igo
Country_to_ACORD,Venezuela,iGO,58,country_to_acord-venezuela@igo
Country_to_ACORD,Viet Nam,iGO,84,country_to_acord-viet nam@igo
Country_to_ACORD,Virgin Islands,iGO,284,country_to_acord-virgin islands@igo
Country_to_ACORD,Wallis and Futuna,iGO,681,country_to_acord-wallis and futuna@igo
Country_to_ACORD,Western Sahara,iGO,1022,country_to_acord-western sahara@igo
Country_to_ACORD,Yemen,iGO,967,country_to_acord-yemen@igo
Country_to_ACORD,Yugoslavia,iGO,38,country_to_acord-yugoslavia@igo
Country_to_ACORD,Zambia,iGO,260,country_to_acord-zambia@igo
Country_to_ACORD,Zimbabwe,iGO,263,country_to_acord-zimbabwe@igo
dthnenetype_tc,0,ACORD,Unknown,dthnenetype_tc-0@acord
dthnenetype_tc,1,ACORD,Level (DB = Face),dthnenetype_tc-1@acord
dthnenetype_tc,2,ACORD,Increasing (DB = Face + Cash),dthnenetype_tc-2@acord
dthnenetype_tc,3,ACORD,Increasing (DB = Face + Return of Cumulative Premiums),dthnenetype_tc-3@acord
dthnenetype_tc,4,ACORD,Increasing (Face + Simple Percent),dthnenetype_tc-4@acord
dthnenetype_tc,5,ACORD,Increasing (Face + Compound Percent),dthnenetype_tc-5@acord
dthnenetype_tc,6,ACORD,Increasing (DB = Return of Cumulative Premiums),dthnenetype_tc-6@acord
dthnenetype_tc,7,ACORD,Increasing (Face + Sum of Deposits with Interest),dthnenetype_tc-7@acord
dthnenetype_tc,8,ACORD,Increasing DB based on client specified schedule,dthnenetype_tc-8@acord
dthnenetype_tc,9,ACORD,Decreasing DB based on client specified schedule,dthnenetype_tc-9@acord
dthnenetype_tc,10,ACORD,Decreasing based on a commuted value,dthnenetype_tc-10@acord
dthnenetype_tc,11,ACORD,Level Choice (DB=greater of Face or Investment AV),dthnenetype_tc-11@acord
dthnenetype_tc,12,ACORD,Increasing by Greater of Invest AV or Net Deposits,dthnenetype_tc-12@acord
dthnenetype_tc,13,ACORD,Increasing Choice (Greater of sum insured and FV),dthnenetype_tc-13@acord
dthnenetype_tc,14,ACORD,Adjustable,dthnenetype_tc-14@acord
dthnenetype_tc,15,ACORD,Increasing (DB = Face Amount + interest percent),dthnenetype_tc-15@acord
dthnenetype_tc,16,ACORD,Increasing (Face + Invest AV),dthnenetype_tc-16@acord
EliminationPeriod,0 days elimination or Not applicable,iGO,1,eliminationperiod-0 days elimination or not applicable@igo
EliminationPeriod,100 days elimination,iGO,17,eliminationperiod-100 days elimination@igo
EliminationPeriod,1095 days,iGO,23,eliminationperiod-1095 days@igo
EliminationPeriod,120 days elimination,iGO,14,eliminationperiod-120 days elimination@igo
EliminationPeriod,14 days elimination (15 days),iGO,5,eliminationperiod-14 days elimination (15 days)@igo
EliminationPeriod,1460 days,iGO,24,eliminationperiod-1460 days@igo
EliminationPeriod,150 days,iGO,22,eliminationperiod-150 days@igo
EliminationPeriod,180 days elimination,iGO,6,eliminationperiod-180 days elimination@igo
EliminationPeriod,20 days elimination,iGO,15,eliminationperiod-20 days elimination@igo
EliminationPeriod,270 days elimination (9 months),iGO,13,eliminationperiod-270 days elimination (9 months)@igo
EliminationPeriod,28 days elimination,iGO,10,eliminationperiod-28 days elimination@igo
EliminationPeriod,3 days elimination,iGO,3,eliminationperiod-3 days elimination@igo
EliminationPeriod,3 months elimination,iGO,18,eliminationperiod-3 months elimination@igo
EliminationPeriod,30 days elimination (1 month),iGO,4,eliminationperiod-30 days elimination (1 month)@igo
EliminationPeriod,"365 days elimination (360 days, 1 year, 12 months)",iGO,2,"eliminationperiod-365 days elimination (360 days, 1 year, 12 months)@igo"
EliminationPeriod,42 days,iGO,21,eliminationperiod-42 days@igo
EliminationPeriod,45 days elimination,iGO,16,eliminationperiod-45 days elimination@igo
EliminationPeriod,5 days,iGO,20,eliminationperiod-5 days@igo
EliminationPeriod,540 days elimination (18 months),iGO,12,eliminationperiod-540 days elimination (18 months)@igo
EliminationPeriod,6 months elimination,iGO,19,eliminationperiod-6 months elimination@igo
EliminationPeriod,60 days elimination,iGO,7,eliminationperiod-60 days elimination@igo
EliminationPeriod,7 days elimination,iGO,8,eliminationperiod-7 days elimination@igo
EliminationPeriod,"720 days elimination (2 years, 730 days, 24 months)",iGO,11,"eliminationperiod-720 days elimination (2 years, 730 days, 24 months)@igo"
EliminationPeriod,"90 days elimination (3 months, 13 weeks)",iGO,9,"eliminationperiod-90 days elimination (3 months, 13 weeks)@igo"
EliminationPeriod,Other,iGO,2147483647,eliminationperiod-other@igo
EliminationPeriod,Unknown,iGO,0,eliminationperiod-unknown@igo
elimperiod_tc,0,ACORD,Unknown,elimperiod_tc-0@acord
elimperiod_tc,1,ACORD,0 days,elimperiod_tc-1@acord
elimperiod_tc,2,ACORD,365 days,elimperiod_tc-2@acord
elimperiod_tc,3,ACORD,3 days,elimperiod_tc-3@acord
elimperiod_tc,4,ACORD,30 days,elimperiod_tc-4@acord
elimperiod_tc,5,ACORD,14 days,elimperiod_tc-5@acord
elimperiod_tc,6,ACORD,180 days,elimperiod_tc-6@acord
elimperiod_tc,7,ACORD,60 days,elimperiod_tc-7@acord
elimperiod_tc,8,ACORD,7 days,elimperiod_tc-8@acord
elimperiod_tc,9,ACORD,90 days,elimperiod_tc-9@acord
elimperiod_tc,10,ACORD,28 days,elimperiod_tc-10@acord
elimperiod_tc,11,ACORD,720 days,elimperiod_tc-11@acord
elimperiod_tc,12,ACORD,540 days,elimperiod_tc-12@acord
elimperiod_tc,13,ACORD,270 days,elimperiod_tc-13@acord
elimperiod_tc,14,ACORD,120 days,elimperiod_tc-14@acord
elimperiod_tc,15,ACORD,20 days,elimperiod_tc-15@acord
elimperiod_tc,16,ACORD,45 days,elimperiod_tc-16@acord
elimperiod_tc,17,ACORD,100 days,elimperiod_tc-17@acord
elimperiod_tc,18,ACORD,3 months,elimperiod_tc-18@acord
elimperiod_tc,19,ACORD,6 months,elimperiod_tc-19@acord
elimperiod_tc,20,ACORD,5 days,elimperiod_tc-20@acord
elimperiod_tc,21,ACORD,42 days,elimperiod_tc-21@acord
elimperiod_tc,22,ACORD,150 days,elimperiod_tc-22@acord
elimperiod_tc,23,ACORD,1095 days,elimperiod_tc-23@acord
elimperiod_tc,24,ACORD,1460 days,elimperiod_tc-24@acord
elimperiod_tc,2147483647,ACORD,Other,elimperiod_tc-2147483647@acord
EmploymentStatus,Active,iGO,1,employmentstatus-active@igo
EmploymentStatus,Active disabled,iGO,13,employmentstatus-active disabled@igo
EmploymentStatus,Active retired,iGO,12,employmentstatus-active retired@igo
EmploymentStatus,Deceased,iGO,9,employmentstatus-deceased@igo
EmploymentStatus,Disabled,iGO,3,employmentstatus-disabled@igo
EmploymentStatus,Early Retiree,iGO,10,employmentstatus-early retiree@igo
EmploymentStatus,Laid Off,iGO,6,employmentstatus-laid off@igo
EmploymentStatus,Leave due to childbirth,iGO,15,employmentstatus-leave due to childbirth@igo
EmploymentStatus,Leave due to military service,iGO,14,employmentstatus-leave due to military service@igo
EmploymentStatus,Leave of Absence,iGO,4,employmentstatus-leave of absence@igo
EmploymentStatus,Not Active for reason unidentified,iGO,2,employmentstatus-not active for reason unidentified@igo
EmploymentStatus,On Strike,iGO,7,employmentstatus-on strike@igo
EmploymentStatus,Other,iGO,2147483647,employmentstatus-other@igo
EmploymentStatus,Resigned,iGO,11,employmentstatus-resigned@igo
EmploymentStatus,Retired,iGO,8,employmentstatus-retired@igo
EmploymentStatus,Sabbatical,iGO,19,employmentstatus-sabbatical@igo
EmploymentStatus,Short Term Disability,iGO,17,employmentstatus-short term disability@igo
EmploymentStatus,Temporarily reassigned,iGO,18,employmentstatus-temporarily reassigned@igo
EmploymentStatus,Terminated,iGO,5,employmentstatus-terminated@igo
EmploymentStatus,Transferred,iGO,16,employmentstatus-transferred@igo
EmploymentStatus,Unknown,iGO,0,employmentstatus-unknown@igo
empstattypecodes_tc,0,ACORD,Unknown,empstattypecodes_tc-0@acord
empstattypecodes_tc,1,ACORD,Active,empstattypecodes_tc-1@acord
empstattypecodes_tc,2,ACORD,Not Active for reason unidentified,empstattypecodes_tc-2@acord
empstattypecodes_tc,3,ACORD,Disabled,empstattypecodes_tc-3@acord
empstattypecodes_tc,4,ACORD,Leave of Absence,empstattypecodes_tc-4@acord
empstattypecodes_tc,5,ACORD,Terminated,empstattypecodes_tc-5@acord
empstattypecodes_tc,6,ACORD,Laid Off,empstattypecodes_tc-6@acord
empstattypecodes_tc,7,ACORD,On Strike,empstattypecodes_tc-7@acord
empstattypecodes_tc,8,ACORD,Retired,empstattypecodes_tc-8@acord
empstattypecodes_tc,9,ACORD,Deceased,empstattypecodes_tc-9@acord
empstattypecodes_tc,10,ACORD,Early Retiree,empstattypecodes_tc-10@acord
empstattypecodes_tc,11,ACORD,Resigned,empstattypecodes_tc-11@acord
empstattypecodes_tc,12,ACORD,Active retired,empstattypecodes_tc-12@acord
empstattypecodes_tc,13,ACORD,Active disabled,empstattypecodes_tc-13@acord
empstattypecodes_tc,14,ACORD,Leave due to military service,empstattypecodes_tc-14@acord
empstattypecodes_tc,15,ACORD,Leave due to childbirth,empstattypecodes_tc-15@acord
empstattypecodes_tc,16,ACORD,Transferred,empstattypecodes_tc-16@acord
empstattypecodes_tc,17,ACORD,Short Term Disability,empstattypecodes_tc-17@acord
empstattypecodes_tc,18,ACORD,Temporarily reassigned,empstattypecodes_tc-18@acord
empstattypecodes_tc,19,ACORD,Sabbatical,empstattypecodes_tc-19@acord
empstattypecodes_tc,2147483647,ACORD,Other,empstattypecodes_tc-2147483647@acord
Gender,Female,iGO,2,gender-female@igo
Gender,Male,iGO,1,gender-male@igo
gender_tc,1,ACORD,Male,gender_tc-1@acord
gender_tc,2,ACORD,Female,gender_tc-2@acord
immstat_tc,0,ACORD,Unknown,immstat_tc-0@acord
immstat_tc,1,ACORD,Permanent Resident,immstat_tc-1@acord
immstat_tc,2,ACORD,Visitor,immstat_tc-2@acord
immstat_tc,3,ACORD,Student,immstat_tc-3@acord
immstat_tc,4,ACORD,Employee,immstat_tc-4@acord
immstat_tc,5,ACORD,Refugee Claimant,immstat_tc-5@acord
immstat_tc,6,ACORD,Application for Landing Immigration,immstat_tc-6@acord
immstat_tc,7,ACORD,Landed Immigrant,immstat_tc-7@acord
immstat_tc,8,ACORD,Citizen,immstat_tc-8@acord
immstat_tc,2147483647,ACORD,Other,immstat_tc-2147483647@acord
intassumption_tc,0,ACORD,Unknown,intassumption_tc-0@acord
intassumption_tc,1,ACORD,Guaranteed - default,intassumption_tc-1@acord
intassumption_tc,2,ACORD,Current,intassumption_tc-2@acord
intassumption_tc,3,ACORD,Specified ( Alternate ),intassumption_tc-3@acord
intassumption_tc,4,ACORD,Custom Specified (Alternate),intassumption_tc-4@acord
intassumption_tc,5,ACORD,Net Specified (variable products only),intassumption_tc-5@acord
intassumption_tc,6,ACORD,NAIC Midpoint,intassumption_tc-6@acord
intassumption_tc,7,ACORD,Custom Blended,intassumption_tc-7@acord
intassumption_tc,8,ACORD,Historical (Variable products),intassumption_tc-8@acord
intassumption_tc,9,ACORD,NAIC Disciplined Current Scale,intassumption_tc-9@acord
intassumption_tc,11,ACORD,High rate,intassumption_tc-11@acord
intassumption_tc,12,ACORD,Low rate,intassumption_tc-12@acord
intassumption_tc,2147483647,ACORD,Other,intassumption_tc-2147483647@acord
IssueState,AB,iGO,101,issuestate-ab@igo
IssueState,AK,iGO,2,issuestate-ak@igo
IssueState,AL,iGO,1,issuestate-al@igo
IssueState,Alabama,iGO,1,issuestate-alabama@igo
IssueState,Alaska,iGO,2,issuestate-alaska@igo
IssueState,Alberta,iGO,101,issuestate-alberta@igo
IssueState,American Samoa,iGO,3,issuestate-american samoa@igo
IssueState,AR,iGO,5,issuestate-ar@igo
IssueState,Arizona,iGO,4,issuestate-arizona@igo
IssueState,Arkansas,iGO,5,issuestate-arkansas@igo
IssueState,AS,iGO,3,issuestate-as@igo
IssueState,AZ,iGO,4,issuestate-az@igo
IssueState,BC,iGO,102,issuestate-bc@igo
IssueState,British Columbia,iGO,102,issuestate-british columbia@igo
IssueState,CA,iGO,6,issuestate-ca@igo
IssueState,California,iGO,6,issuestate-california@igo
IssueState,CO,iGO,7,issuestate-co@igo
IssueState,Colorado,iGO,7,issuestate-colorado@igo
IssueState,Connecticut,iGO,8,issuestate-connecticut@igo
IssueState,CT,iGO,8,issuestate-ct@igo
IssueState,DC,iGO,10,issuestate-dc@igo
IssueState,DE,iGO,9,issuestate-de@igo
IssueState,Delaware,iGO,9,issuestate-delaware@igo
IssueState,District of Columbia,iGO,10,issuestate-district of columbia@igo
IssueState,FL,iGO,12,issuestate-fl@igo
IssueState,Florida,iGO,12,issuestate-florida@igo
IssueState,GA,iGO,13,issuestate-ga@igo
IssueState,Georgia,iGO,13,issuestate-georgia@igo
IssueState,GU,iGO,14,issuestate-gu@igo
IssueState,Guam,iGO,14,issuestate-guam@igo
IssueState,Hawaii,iGO,15,issuestate-hawaii@igo
IssueState,HI,iGO,15,issuestate-hi@igo
IssueState,IA,iGO,19,issuestate-ia@igo
IssueState,ID,iGO,16,issuestate-id@igo
IssueState,Idaho,iGO,16,issuestate-idaho@igo
IssueState,IL,iGO,17,issuestate-il@igo
IssueState,Illinois,iGO,17,issuestate-illinois@igo
IssueState,IN,iGO,18,issuestate-in@igo
IssueState,Indiana,iGO,18,issuestate-indiana@igo
IssueState,Iowa,iGO,19,issuestate-iowa@igo
IssueState,Kansas,iGO,20,issuestate-kansas@igo
IssueState,Kentucky,iGO,21,issuestate-kentucky@igo
IssueState,KS,iGO,20,issuestate-ks@igo
IssueState,KY,iGO,21,issuestate-ky@igo
IssueState,LA,iGO,22,issuestate-la@igo
IssueState,Louisiana,iGO,22,issuestate-louisiana@igo
IssueState,MA,iGO,26,issuestate-ma@igo
IssueState,Maine,iGO,23,issuestate-maine@igo
IssueState,Manitoba,iGO,103,issuestate-manitoba@igo
IssueState,Maryland,iGO,25,issuestate-maryland@igo
IssueState,Massachusetts,iGO,26,issuestate-massachusetts@igo
IssueState,MB,iGO,103,issuestate-mb@igo
IssueState,MD,iGO,25,issuestate-md@igo
IssueState,ME,iGO,23,issuestate-me@igo
IssueState,MI,iGO,27,issuestate-mi@igo
IssueState,Michigan,iGO,27,issuestate-michigan@igo
IssueState,Minnesota,iGO,28,issuestate-minnesota@igo
IssueState,Mississippi,iGO,29,issuestate-mississippi@igo
IssueState,Missouri,iGO,30,issuestate-missouri@igo
IssueState,MN,iGO,28,issuestate-mn@igo
IssueState,MO,iGO,30,issuestate-mo@igo
IssueState,Montana,iGO,31,issuestate-montana@igo
IssueState,MP,iGO,40,issuestate-mp@igo
IssueState,MS,iGO,29,issuestate-ms@igo
IssueState,MT,iGO,31,issuestate-mt@igo
IssueState,NB,iGO,104,issuestate-nb@igo
IssueState,NC,iGO,38,issuestate-nc@igo
IssueState,ND,iGO,39,issuestate-nd@igo
IssueState,NE,iGO,32,issuestate-ne@igo
IssueState,Nebraska,iGO,32,issuestate-nebraska@igo
IssueState,Nevada,iGO,33,issuestate-nevada@igo
IssueState,New Brunswick,iGO,104,issuestate-new brunswick@igo
IssueState,New Hampshire,iGO,34,issuestate-new hampshire@igo
IssueState,New Jersey,iGO,35,issuestate-new jersey@igo
IssueState,New Mexico,iGO,36,issuestate-new mexico@igo
IssueState,New York,iGO,37,issuestate-new york@igo
IssueState,Newfoundland and Labrador,iGO,105,issuestate-newfoundland and labrador@igo
IssueState,NH,iGO,34,issuestate-nh@igo
IssueState,NJ,iGO,35,issuestate-nj@igo
IssueState,NL,iGO,105,issuestate-nl@igo
IssueState,NM,iGO,36,issuestate-nm@igo
IssueState,North Carolina,iGO,38,issuestate-north carolina@igo
IssueState,North Dakota,iGO,39,issuestate-north dakota@igo
IssueState,Northern Mariana Islands,iGO,40,issuestate-northern mariana islands@igo
IssueState,Northwest Territories,iGO,106,issuestate-northwest territories@igo
IssueState,Nova Scotia,iGO,107,issuestate-nova scotia@igo
IssueState,NS,iGO,107,issuestate-ns@igo
IssueState,NT,iGO,106,issuestate-nt@igo
IssueState,NU,iGO,113,issuestate-nu@igo
IssueState,Nunavut,iGO,113,issuestate-nunavut@igo
IssueState,NV,iGO,33,issuestate-nv@igo
IssueState,NY,iGO,37,issuestate-ny@igo
IssueState,OH,iGO,41,issuestate-oh@igo
IssueState,Ohio,iGO,41,issuestate-ohio@igo
IssueState,OK,iGO,42,issuestate-ok@igo
IssueState,Oklahoma,iGO,42,issuestate-oklahoma@igo
IssueState,ON,iGO,108,issuestate-on@igo
IssueState,Ontario,iGO,108,issuestate-ontario@igo
IssueState,OR,iGO,43,issuestate-or@igo
IssueState,Oregon,iGO,43,issuestate-oregon@igo
IssueState,PA,iGO,45,issuestate-pa@igo
IssueState,PE,iGO,109,issuestate-pe@igo
IssueState,Pennsylvania,iGO,45,issuestate-pennsylvania@igo
IssueState,PR,iGO,46,issuestate-pr@igo
IssueState,Prince Edward Island,iGO,109,issuestate-prince edward island@igo
IssueState,Puerto Rico,iGO,46,issuestate-puerto rico@igo
IssueState,QC,iGO,110,issuestate-qc@igo
IssueState,Quebec,iGO,110,issuestate-quebec@igo
IssueState,Rhode Island,iGO,47,issuestate-rhode island@igo
IssueState,RI,iGO,47,issuestate-ri@igo
IssueState,Saskatchewan,iGO,111,issuestate-saskatchewan@igo
IssueState,SC,iGO,48,issuestate-sc@igo
IssueState,SD,iGO,49,issuestate-sd@igo
IssueState,SK,iGO,111,issuestate-sk@igo
IssueState,South Carolina,iGO,48,issuestate-south carolina@igo
IssueState,South Dakota,iGO,49,issuestate-south dakota@igo
IssueState,Tennessee,iGO,50,issuestate-tennessee@igo
IssueState,Texas,iGO,51,issuestate-texas@igo
IssueState,TN,iGO,50,issuestate-tn@igo
IssueState,TX,iGO,51,issuestate-tx@igo
IssueState,UT,iGO,52,issuestate-ut@igo
IssueState,Utah,iGO,52,issuestate-utah@igo
IssueState,VA,iGO,55,issuestate-va@igo
IssueState,Vermont,iGO,53,issuestate-vermont@igo
IssueState,VI,iGO,54,issuestate-vi@igo
IssueState,Virgin Islands,iGO,54,issuestate-virgin islands@igo
IssueState,Virginia,iGO,55,issuestate-virginia@igo
IssueState,VT,iGO,53,issuestate-vt@igo
IssueState,WA,iGO,56,issuestate-wa@igo
IssueState,Washington,iGO,56,issuestate-washington@igo
IssueState,West Virginia,iGO,57,issuestate-west virginia@igo
IssueState,WI,iGO,58,issuestate-wi@igo
IssueState,Wisconsin,iGO,58,issuestate-wisconsin@igo
IssueState,WV,iGO,57,issuestate-wv@igo
IssueState,WY,iGO,59,issuestate-wy@igo
IssueState,Wyoming,iGO,59,issuestate-wyoming@igo
IssueState,YT,iGO,112,issuestate-yt@igo
IssueState,Yukon Territory,iGO,112,issuestate-yukon territory@igo
MaritalStatus,Unknown,iGO,0,maritalstatus-unknonw@igo
MaritalStatus,Married,iGO,1,maritalstatus-maried@igo
MaritalStatus,Single,iGO,2,maritalstatus-single@igo
MaritalStatus,Divorced,iGO,3,maritalstatus-divorced@igo
MaritalStatus,Widowed,iGO,4,maritalstatus-widowed@igo
MaritalStatus,Legally Separated,iGO,5,maritalstatus-legally separated@igo
MaritalStatus,Common Law,iGO,6,maritalstatus-common law@igo
MaritalStatus,Estranged,iGO,7,maritalstatus-estranged@igo
MaritalStatus,Head of Household,iGO,8,maritalstatus-head of household@igo
MaritalStatus,Maried withholding single,iGO,9,maritalstatus-maried withholding single@igo
MaritalStatus,Domestic Partner,iGO,10,maritalstatus-domestic partner@igo
MaritalStatus,Other,iGO,2147483647,maritalstatus-other@igo
marstat_tc,0,ACORD,Unknown,marstat_tc-0@acord
marstat_tc,1,ACORD,Married,marstat_tc-1@acord
marstat_tc,2,ACORD,Single,marstat_tc-2@acord
marstat_tc,3,ACORD,Divorced,marstat_tc-3@acord
marstat_tc,4,ACORD,Widowed,marstat_tc-4@acord
marstat_tc,5,ACORD,Legally Separated,marstat_tc-5@acord
marstat_tc,6,ACORD,Common Law,marstat_tc-6@acord
marstat_tc,7,ACORD,Estranged,marstat_tc-7@acord
marstat_tc,8,ACORD,Head of Household,marstat_tc-8@acord
marstat_tc,9,ACORD,Married withholding single,marstat_tc-9@acord
marstat_tc,10,ACORD,Domestic Partner,marstat_tc-10@acord
marstat_tc,2147483647,ACORD,Other,marstat_tc-2147483647@acord
nation_tc,0,ACORD,Unknown,nation_tc-0@acord
nation_tc,1,ACORD,United States of America,nation_tc-1@acord
nation_tc,2,ACORD,Canada,nation_tc-2@acord
nation_tc,7,ACORD,Russia,nation_tc-7@acord
nation_tc,20,ACORD,Egypt,nation_tc-20@acord
nation_tc,27,ACORD,South Africa,nation_tc-27@acord
nation_tc,30,ACORD,Greece,nation_tc-30@acord
nation_tc,31,ACORD,Netherlands,nation_tc-31@acord
nation_tc,32,ACORD,Belgium,nation_tc-32@acord
nation_tc,33,ACORD,France,nation_tc-33@acord
nation_tc,34,ACORD,Spain,nation_tc-34@acord
nation_tc,36,ACORD,Hungary,nation_tc-36@acord
nation_tc,38,ACORD,Yugoslavia,nation_tc-38@acord
nation_tc,39,ACORD,Italy,nation_tc-39@acord
nation_tc,40,ACORD,Romania,nation_tc-40@acord
nation_tc,41,ACORD,Switzerland,nation_tc-41@acord
nation_tc,43,ACORD,Austria,nation_tc-43@acord
nation_tc,44,ACORD,United Kingdom,nation_tc-44@acord
nation_tc,45,ACORD,Denmark,nation_tc-45@acord
nation_tc,46,ACORD,Sweden,nation_tc-46@acord
nation_tc,47,ACORD,Norway,nation_tc-47@acord
nation_tc,48,ACORD,Poland,nation_tc-48@acord
nation_tc,49,ACORD,Germany,nation_tc-49@acord
nation_tc,51,ACORD,Peru,nation_tc-51@acord
nation_tc,52,ACORD,Mexico,nation_tc-52@acord
nation_tc,53,ACORD,Cuba,nation_tc-53@acord
nation_tc,54,ACORD,Argentina,nation_tc-54@acord
nation_tc,55,ACORD,Brazil,nation_tc-55@acord
nation_tc,56,ACORD,Chile,nation_tc-56@acord
nation_tc,57,ACORD,Colombia,nation_tc-57@acord
nation_tc,58,ACORD,Venezuela,nation_tc-58@acord
nation_tc,60,ACORD,Malaysia,nation_tc-60@acord
nation_tc,61,ACORD,Australia,nation_tc-61@acord
nation_tc,62,ACORD,Indonesia,nation_tc-62@acord
nation_tc,63,ACORD,Philippines,nation_tc-63@acord
nation_tc,64,ACORD,New Zealand,nation_tc-64@acord
nation_tc,65,ACORD,Singapore,nation_tc-65@acord
nation_tc,66,ACORD,Thailand,nation_tc-66@acord
nation_tc,81,ACORD,Japan,nation_tc-81@acord
nation_tc,84,ACORD,Viet Nam,nation_tc-84@acord
nation_tc,86,ACORD,China,nation_tc-86@acord
nation_tc,90,ACORD,Turkey,nation_tc-90@acord
nation_tc,91,ACORD,India,nation_tc-91@acord
nation_tc,92,ACORD,Pakistan,nation_tc-92@acord
nation_tc,93,ACORD,Afghanistan,nation_tc-93@acord
nation_tc,94,ACORD,Sri Lanka,nation_tc-94@acord
nation_tc,98,ACORD,Islamic Republic of Iran,nation_tc-98@acord
nation_tc,212,ACORD,Morocco,nation_tc-212@acord
nation_tc,213,ACORD,Algeria,nation_tc-213@acord
nation_tc,216,ACORD,Tunisia,nation_tc-216@acord
nation_tc,218,ACORD,Libya,nation_tc-218@acord
nation_tc,220,ACORD,Gambia,nation_tc-220@acord
nation_tc,221,ACORD,Senegal,nation_tc-221@acord
nation_tc,222,ACORD,Mauritania,nation_tc-222@acord
nation_tc,223,ACORD,Mali,nation_tc-223@acord
nation_tc,224,ACORD,Guinea,nation_tc-224@acord
nation_tc,226,ACORD,Burkina Faso,nation_tc-226@acord
nation_tc,227,ACORD,Niger,nation_tc-227@acord
nation_tc,228,ACORD,Togo,nation_tc-228@acord
nation_tc,229,ACORD,Benin,nation_tc-229@acord
nation_tc,230,ACORD,Mauritius,nation_tc-230@acord
nation_tc,231,ACORD,Liberia,nation_tc-231@acord
nation_tc,232,ACORD,Sierra Leone,nation_tc-232@acord
nation_tc,233,ACORD,Ghana,nation_tc-233@acord
nation_tc,234,ACORD,Nigeria,nation_tc-234@acord
nation_tc,235,ACORD,Chad,nation_tc-235@acord
nation_tc,236,ACORD,Central African Republic,nation_tc-236@acord
nation_tc,237,ACORD,Cameroon,nation_tc-237@acord
nation_tc,238,ACORD,Cape Verde,nation_tc-238@acord
nation_tc,239,ACORD,Sao Tome and Principe,nation_tc-239@acord
nation_tc,240,ACORD,Equatorial Guinea,nation_tc-240@acord
nation_tc,241,ACORD,Gabon,nation_tc-241@acord
nation_tc,242,ACORD,Bahamas,nation_tc-242@acord
nation_tc,244,ACORD,Angola,nation_tc-244@acord
nation_tc,246,ACORD,Barbados,nation_tc-246@acord
nation_tc,248,ACORD,Aland Islands,nation_tc-248@acord
nation_tc,249,ACORD,Sudan,nation_tc-249@acord
nation_tc,250,ACORD,Rwanda,nation_tc-250@acord
nation_tc,251,ACORD,Ethiopia,nation_tc-251@acord
nation_tc,252,ACORD,Somalia,nation_tc-252@acord
nation_tc,253,ACORD,Djibouti,nation_tc-253@acord
nation_tc,254,ACORD,Kenya,nation_tc-254@acord
nation_tc,255,ACORD,United Republic of Tanzania,nation_tc-255@acord
nation_tc,257,ACORD,Burundi,nation_tc-257@acord
nation_tc,258,ACORD,Mozambique,nation_tc-258@acord
nation_tc,260,ACORD,Zambia,nation_tc-260@acord
nation_tc,261,ACORD,Madagascar,nation_tc-261@acord
nation_tc,262,ACORD,Reunion,nation_tc-262@acord
nation_tc,263,ACORD,Zimbabwe,nation_tc-263@acord
nation_tc,264,ACORD,Namibia,nation_tc-264@acord
nation_tc,265,ACORD,Malawi,nation_tc-265@acord
nation_tc,266,ACORD,Lesotho,nation_tc-266@acord
nation_tc,267,ACORD,Botswana,nation_tc-267@acord
nation_tc,268,ACORD,Antigua and Barbuda,nation_tc-268@acord
nation_tc,269,ACORD,Comoros,nation_tc-269@acord
nation_tc,270,ACORD,Guinea-Bissau,nation_tc-270@acord
nation_tc,271,ACORD,The Democratic Republic of the Congo,nation_tc-271@acord
nation_tc,284,ACORD,British Virgin Islands,nation_tc-284@acord
nation_tc,290,ACORD,Saint Helena Ascension and Tristan da Cunha,nation_tc-290@acord
nation_tc,297,ACORD,Aruba,nation_tc-297@acord
nation_tc,298,ACORD,Faroe Islands,nation_tc-298@acord
nation_tc,299,ACORD,Greenland,nation_tc-299@acord
nation_tc,345,ACORD,Cayman Islands,nation_tc-345@acord
nation_tc,350,ACORD,Gibraltar,nation_tc-350@acord
nation_tc,351,ACORD,Portugal,nation_tc-351@acord
nation_tc,352,ACORD,Luxembourg,nation_tc-352@acord
nation_tc,353,ACORD,Ireland,nation_tc-353@acord
nation_tc,354,ACORD,Iceland,nation_tc-354@acord
nation_tc,355,ACORD,Albania,nation_tc-355@acord
nation_tc,356,ACORD,Malta,nation_tc-356@acord
nation_tc,357,ACORD,Cyprus,nation_tc-357@acord
nation_tc,358,ACORD,Finland,nation_tc-358@acord
nation_tc,359,ACORD,Bulgaria,nation_tc-359@acord
nation_tc,360,ACORD,Guernsey,nation_tc-360@acord
nation_tc,370,ACORD,Lithuania,nation_tc-370@acord
nation_tc,371,ACORD,Latvia,nation_tc-371@acord
nation_tc,372,ACORD,Estonia,nation_tc-372@acord
nation_tc,373,ACORD,Republic of Moldova,nation_tc-373@acord
nation_tc,374,ACORD,Armenia,nation_tc-374@acord
nation_tc,375,ACORD,Belarus,nation_tc-375@acord
nation_tc,376,ACORD,Andorra,nation_tc-376@acord
nation_tc,378,ACORD,San Marino,nation_tc-378@acord
nation_tc,380,ACORD,Ukraine,nation_tc-380@acord
nation_tc,385,ACORD,Croatia,nation_tc-385@acord
nation_tc,386,ACORD,Slovenia,nation_tc-386@acord
nation_tc,387,ACORD,Bosnia and Herzegovina,nation_tc-387@acord
nation_tc,389,ACORD,The Former Yugoslav Republic of Macedonia,nation_tc-389@acord
nation_tc,390,ACORD,Kosovo,nation_tc-390@acord
nation_tc,420,ACORD,Czech Republic,nation_tc-420@acord
nation_tc,421,ACORD,Slovakia,nation_tc-421@acord
nation_tc,423,ACORD,Liechtenstein,nation_tc-423@acord
nation_tc,441,ACORD,Bermuda,nation_tc-441@acord
nation_tc,473,ACORD,Grenada,nation_tc-473@acord
nation_tc,500,ACORD,Falkland Islands,nation_tc-500@acord
nation_tc,501,ACORD,Belize,nation_tc-501@acord
nation_tc,502,ACORD,Guatemala,nation_tc-502@acord
nation_tc,503,ACORD,El Salvador,nation_tc-503@acord
nation_tc,504,ACORD,Honduras,nation_tc-504@acord
nation_tc,505,ACORD,Nicaragua,nation_tc-505@acord
nation_tc,506,ACORD,Costa Rica,nation_tc-506@acord
nation_tc,508,ACORD,Saint Pierre and Miquelon,nation_tc-508@acord
nation_tc,509,ACORD,Haiti,nation_tc-509@acord
nation_tc,510,ACORD,Puerto Rico,nation_tc-510@acord
nation_tc,511,ACORD,US Virgin Islands,nation_tc-511@acord
nation_tc,512,ACORD,South Georgia and the South Sandwich Islands,nation_tc-512@acord
nation_tc,534,ACORD,Sint Maarten (Dutch Part),nation_tc-534@acord
nation_tc,535,ACORD,Bonaire Sint Eustatius and Saba,nation_tc-535@acord
nation_tc,590,ACORD,Guadeloupe,nation_tc-590@acord
nation_tc,591,ACORD,Bolivia,nation_tc-591@acord
nation_tc,592,ACORD,Guyana,nation_tc-592@acord
nation_tc,593,ACORD,Ecuador,nation_tc-593@acord
nation_tc,594,ACORD,French Guiana,nation_tc-594@acord
nation_tc,595,ACORD,Paraguay,nation_tc-595@acord
nation_tc,596,ACORD,Martinique,nation_tc-596@acord
nation_tc,597,ACORD,Suriname,nation_tc-597@acord
nation_tc,598,ACORD,Uruguay,nation_tc-598@acord
nation_tc,599,ACORD,Netherlands Antilles,nation_tc-599@acord
nation_tc,649,ACORD,Turks and Caicos Islands,nation_tc-649@acord
nation_tc,652,ACORD,Saint Barthelemy,nation_tc-652@acord
nation_tc,663,ACORD,Saint Martin (French Part),nation_tc-663@acord
nation_tc,664,ACORD,Montserrat,nation_tc-664@acord
nation_tc,671,ACORD,Guam,nation_tc-671@acord
nation_tc,672,ACORD,Antarctica,nation_tc-672@acord
nation_tc,673,ACORD,Brunei Darussalam,nation_tc-673@acord
nation_tc,674,ACORD,Nauru,nation_tc-674@acord
nation_tc,675,ACORD,Papua New Guinea,nation_tc-675@acord
nation_tc,676,ACORD,Tonga,nation_tc-676@acord
nation_tc,677,ACORD,Solomon Islands,nation_tc-677@acord
nation_tc,678,ACORD,Vanuatu,nation_tc-678@acord
nation_tc,679,ACORD,Fiji,nation_tc-679@acord
nation_tc,681,ACORD,Wallis and Futuna,nation_tc-681@acord
nation_tc,682,ACORD,Cook Islands,nation_tc-682@acord
nation_tc,683,ACORD,Niue,nation_tc-683@acord
nation_tc,684,ACORD,American Samoa,nation_tc-684@acord
nation_tc,686,ACORD,Kiribati,nation_tc-686@acord
nation_tc,687,ACORD,New Caledonia,nation_tc-687@acord
nation_tc,688,ACORD,Tuvalu,nation_tc-688@acord
nation_tc,689,ACORD,French Polynesia,nation_tc-689@acord
nation_tc,691,ACORD,Northern Mariana Islands,nation_tc-691@acord
nation_tc,693,ACORD,Palau,nation_tc-693@acord
nation_tc,694,ACORD,Marshall Islands,nation_tc-694@acord
nation_tc,695,ACORD,Federated States of Micronesia,nation_tc-695@acord
nation_tc,728,ACORD,South Sudan,nation_tc-728@acord
nation_tc,758,ACORD,Saint Lucia,nation_tc-758@acord
nation_tc,767,ACORD,Dominica,nation_tc-767@acord
nation_tc,784,ACORD,Saint Vincent and the Grenadines,nation_tc-784@acord
nation_tc,809,ACORD,Dominican Republic,nation_tc-809@acord
nation_tc,852,ACORD,Hong Kong,nation_tc-852@acord
nation_tc,853,ACORD,Macao,nation_tc-853@acord
nation_tc,855,ACORD,Cambodia,nation_tc-855@acord
nation_tc,856,ACORD,Lao People's Democratic Republic,nation_tc-856@acord
nation_tc,868,ACORD,Trinidad and Tobago,nation_tc-868@acord
nation_tc,869,ACORD,Saint Kitts and Nevis,nation_tc-869@acord
nation_tc,876,ACORD,Jamaica,nation_tc-876@acord
nation_tc,880,ACORD,Bangladesh,nation_tc-880@acord
nation_tc,886,ACORD,Taiwan Province of China,nation_tc-886@acord
nation_tc,950,ACORD,Myanmar,nation_tc-950@acord
nation_tc,951,ACORD,Republic of Korea,nation_tc-951@acord
nation_tc,952,ACORD,Democratic People's Republic of Korea,nation_tc-952@acord
nation_tc,961,ACORD,Lebanon,nation_tc-961@acord
nation_tc,962,ACORD,Jordan,nation_tc-962@acord
nation_tc,963,ACORD,Syrian Arab Republic,nation_tc-963@acord
nation_tc,964,ACORD,Iraq,nation_tc-964@acord
nation_tc,965,ACORD,Kuwait,nation_tc-965@acord
nation_tc,966,ACORD,Saudi Arabia,nation_tc-966@acord
nation_tc,967,ACORD,Yemen,nation_tc-967@acord
nation_tc,968,ACORD,Oman,nation_tc-968@acord
nation_tc,971,ACORD,United Arab Emirates,nation_tc-971@acord
nation_tc,972,ACORD,Israel,nation_tc-972@acord
nation_tc,973,ACORD,Bahrain,nation_tc-973@acord
nation_tc,974,ACORD,Qatar,nation_tc-974@acord
nation_tc,975,ACORD,Bhutan,nation_tc-975@acord
nation_tc,977,ACORD,Nepal,nation_tc-977@acord
nation_tc,992,ACORD,Tajikistan,nation_tc-992@acord
nation_tc,993,ACORD,Turkmenistan,nation_tc-993@acord
nation_tc,994,ACORD,Azerbaijan,nation_tc-994@acord
nation_tc,995,ACORD,Georgia,nation_tc-995@acord
nation_tc,998,ACORD,Uzbekistan,nation_tc-998@acord
nation_tc,1001,ACORD,Anguilla,nation_tc-1001@acord
nation_tc,1002,ACORD,Panama (also known as Canal Zone),nation_tc-1002@acord
nation_tc,1003,ACORD,Cote d'Ivoire,nation_tc-1003@acord
nation_tc,1004,ACORD,Eritrea,nation_tc-1004@acord
nation_tc,1005,ACORD,Kazakhstan,nation_tc-1005@acord
nation_tc,1006,ACORD,Kyrgyzstan,nation_tc-1006@acord
nation_tc,1007,ACORD,Cocos (Keeling) Islands,nation_tc-1007@acord
nation_tc,1008,ACORD,Mongolia,nation_tc-1008@acord
nation_tc,1009,ACORD,Bouvet Island,nation_tc-1009@acord
nation_tc,1010,ACORD,Seychelles,nation_tc-1010@acord
nation_tc,1011,ACORD,British Indian Ocean Territory,nation_tc-1011@acord
nation_tc,1013,ACORD,Samoa,nation_tc-1013@acord
nation_tc,1014,ACORD,Timor-Leste,nation_tc-1014@acord
nation_tc,1015,ACORD,French Southern Territories,nation_tc-1015@acord
nation_tc,1016,ACORD,Heard Island and McDonald Islands,nation_tc-1016@acord
nation_tc,1017,ACORD,Mayotte,nation_tc-1017@acord
nation_tc,1018,ACORD,Pitcairn,nation_tc-1018@acord
nation_tc,1019,ACORD,Svalbard and Jan Mayen,nation_tc-1019@acord
nation_tc,1020,ACORD,Tokelau,nation_tc-1020@acord
nation_tc,1021,ACORD,United States Minor Outlying Islands,nation_tc-1021@acord
nation_tc,1022,ACORD,Western Sahara,nation_tc-1022@acord
nation_tc,1023,ACORD,Maldives,nation_tc-1023@acord
nation_tc,1024,ACORD,Christmas Island,nation_tc-1024@acord
nation_tc,1025,ACORD,Norfolk Island,nation_tc-1025@acord
nation_tc,1026,ACORD,Curacao,nation_tc-1026@acord
nation_tc,1027,ACORD,Congo,nation_tc-1027@acord
nation_tc,1028,ACORD,Monaco,nation_tc-1028@acord
nation_tc,1029,ACORD,Holy See (Vatican City State),nation_tc-1029@acord
nation_tc,1031,ACORD,Swaziland,nation_tc-1031@acord
nation_tc,1032,ACORD,Occupied Palestinian Territory,nation_tc-1032@acord
nation_tc,1034,ACORD,Jersey,nation_tc-1034@acord
nation_tc,1035,ACORD,Isle of Man,nation_tc-1035@acord
nation_tc,1036,ACORD,Serbia,nation_tc-1036@acord
nation_tc,1037,ACORD,Montenegro,nation_tc-1037@acord
nation_tc,1038,ACORD,North Yemen,nation_tc-1038@acord
nation_tc,1039,ACORD,South Yemen,nation_tc-1039@acord
nation_tc,1040,ACORD,Union of Soviet Socialist Republics,nation_tc-1040@acord
nation_tc,2147483647,ACORD,Other,nation_tc-2147483647@acord
immstat_tc,0,ACORD,Unknown,immstat_tc-0@acord
immstat_tc,1,ACORD,Permanent Resident,immstat_tc-0@acord
immstat_tc,2,ACORD,Visitor,immstat_tc-0@acord
immstat_tc,3,ACORD,Student,immstat_tc-0@acord
immstat_tc,4,ACORD,Employee,immstat_tc-0@acord
immstat_tc,5,ACORD,Refugee Claimant,immstat_tc-0@acord
immstat_tc,6,ACORD,Application for Landing Immigration,immstat_tc-0@acord
immstat_tc,7,ACORD,Landed Immigrant,immstat_tc-0@acord
immstat_tc,8,ACORD,Citizen,immstat_tc-0@acord
immstat_tc,9,ACORD,Non-Landed Immigrant,immstat_tc-0@acord
immstat_tc,2147483647,ACORD,Other,immstat_tc-2147483647@acord
OccupationClass,Board Member,iGO,16,occupationclass-board member@igo
OccupationClass,Corporate Officer,iGO,14,occupationclass-corporate officer@igo
OccupationClass,Flagged Occupation,iGO,8,occupationclass-flagged occupation@igo
OccupationClass,Homemaker,iGO,7,occupationclass-homemaker@igo
OccupationClass,Military,iGO,6,occupationclass-military@igo
OccupationClass,"Office, Sales",iGO,11,"occupationclass-office, sales@igo"
OccupationClass,Officer/Board Member,iGO,15,occupationclass-officer/board member@igo
OccupationClass,Other,iGO,2147483647,occupationclass-other@igo
OccupationClass,Owner,iGO,19,occupationclass-owner@igo
OccupationClass,Owner/Employee,iGO,18,occupationclass-owner/employee@igo
OccupationClass,Partner,iGO,17,occupationclass-partner@igo
OccupationClass,Part-Time Employee,iGO,13,occupationclass-part-time employee@igo
OccupationClass,"Professional, Managerial",iGO,9,"occupationclass-professional, managerial@igo"
OccupationClass,Retired,iGO,3,occupationclass-retired@igo
OccupationClass,Salaried,iGO,1,occupationclass-salaried@igo
OccupationClass,Self-Employed,iGO,2,occupationclass-self-employed@igo
OccupationClass,"Skilled, Semi-skilled",iGO,10,"occupationclass-skilled, semi-skilled@igo"
OccupationClass,Sole Proprietor,iGO,20,occupationclass-sole proprietor@igo
OccupationClass,Student,iGO,5,occupationclass-student@igo
OccupationClass,Unemployed,iGO,4,occupationclass-unemployed@igo
OccupationClass,Unknown,iGO,0,occupationclass-unknown@igo
OccupationClass,Unskilled,iGO,12,occupationclass-unskilled@igo
occupclass_tc,0,ACORD,Unknown,occupclass_tc-0@acord
occupclass_tc,1,ACORD,Salaried,occupclass_tc-1@acord
occupclass_tc,2,ACORD,Self-Employed,occupclass_tc-2@acord
occupclass_tc,3,ACORD,Retired,occupclass_tc-3@acord
occupclass_tc,4,ACORD,Unemployed,occupclass_tc-4@acord
occupclass_tc,5,ACORD,Student,occupclass_tc-5@acord
occupclass_tc,6,ACORD,Military,occupclass_tc-6@acord
occupclass_tc,7,ACORD,Homemaker,occupclass_tc-7@acord
occupclass_tc,8,ACORD,Flagged Occupation,occupclass_tc-8@acord
occupclass_tc,9,ACORD,"Professional, Managerial",occupclass_tc-9@acord
occupclass_tc,10,ACORD,"Skilled, Semi-skilled",occupclass_tc-10@acord
occupclass_tc,11,ACORD,"Office, Sales",occupclass_tc-11@acord
occupclass_tc,12,ACORD,Unskilled,occupclass_tc-12@acord
occupclass_tc,13,ACORD,Part-Time Employee,occupclass_tc-13@acord
occupclass_tc,14,ACORD,Corporate Officer,occupclass_tc-14@acord
occupclass_tc,15,ACORD,Officer/Board Member,occupclass_tc-15@acord
occupclass_tc,16,ACORD,Board Member,occupclass_tc-16@acord
occupclass_tc,17,ACORD,Partner,occupclass_tc-17@acord
occupclass_tc,18,ACORD,Owner/Employee,occupclass_tc-18@acord
occupclass_tc,19,ACORD,Owner,occupclass_tc-19@acord
occupclass_tc,20,ACORD,Sole Proprietor,occupclass_tc-20@acord
occupclass_tc,2147483647,ACORD,Other,occupclass_tc-2147483647@acord
orgform_tc,0,ACORD,Unknown,orgform_tc-0@acord
orgform_tc,1,ACORD,Sole Proprietorship,orgform_tc-1@acord
orgform_tc,2,ACORD,Partnership,orgform_tc-2@acord
orgform_tc,3,ACORD,Limited Partnership (LP),orgform_tc-3@acord
orgform_tc,4,ACORD,Private Corporation,orgform_tc-4@acord
orgform_tc,5,ACORD,Public Corporation,orgform_tc-5@acord
orgform_tc,6,ACORD,S Corporation,orgform_tc-6@acord
orgform_tc,7,ACORD,Professional Corporation,orgform_tc-7@acord
orgform_tc,8,ACORD,Personal Services Corp.,orgform_tc-8@acord
orgform_tc,9,ACORD,Government Agency,orgform_tc-9@acord
orgform_tc,10,ACORD,Association,orgform_tc-10@acord
orgform_tc,11,ACORD,Charitable Organization,orgform_tc-11@acord
orgform_tc,12,ACORD,Nonprofit Organization,orgform_tc-12@acord
orgform_tc,13,ACORD,C Corporation,orgform_tc-13@acord
orgform_tc,14,ACORD,Limited Liability Company (LLC),orgform_tc-14@acord
orgform_tc,15,ACORD,Franchise,orgform_tc-15@acord
orgform_tc,16,ACORD,Trust,orgform_tc-16@acord
orgform_tc,17,ACORD,Plan,orgform_tc-17@acord
orgform_tc,18,ACORD,Mutual Company,orgform_tc-18@acord
orgform_tc,19,ACORD,Closed Corporation,orgform_tc-19@acord
orgform_tc,20,ACORD,Pty. Ltd.,orgform_tc-20@acord
orgform_tc,21,ACORD,Superannuation Fund,orgform_tc-21@acord
orgform_tc,22,ACORD,Internal,orgform_tc-22@acord
orgform_tc,23,ACORD,Corporation (general),orgform_tc-23@acord
orgform_tc,24,ACORD,Estate,orgform_tc-24@acord
orgform_tc,25,ACORD,Plan Administrator,orgform_tc-25@acord
orgform_tc,26,ACORD,Religious Organization,orgform_tc-26@acord
orgform_tc,27,ACORD,Credit Union,orgform_tc-27@acord
orgform_tc,29,ACORD,Limited Liability Partnership (LLP),orgform_tc-29@acord
orgform_tc,30,ACORD,Limited Liability Limited Partnership (LLLP),orgform_tc-30@acord
orgform_tc,2147483647,ACORD,Other,orgform_tc-2147483647@acord
paymethod_tc,0,ACORD,Unknown,paymethod_tc-0@acord
paymethod_tc,1,ACORD,No Billing,paymethod_tc-1@acord
paymethod_tc,2,ACORD,Regular Billing,paymethod_tc-2@acord
paymethod_tc,3,ACORD,Irregular Billing,paymethod_tc-3@acord
paymethod_tc,4,ACORD,Paid in Advance,paymethod_tc-4@acord
paymethod_tc,5,ACORD,List Bill,paymethod_tc-5@acord
paymethod_tc,6,ACORD,Payroll Deduction,paymethod_tc-6@acord
paymethod_tc,7,ACORD,Electronic Funds Transfer,paymethod_tc-7@acord
paymethod_tc,8,ACORD,Government Allotment,paymethod_tc-8@acord
paymethod_tc,9,ACORD,Credit Card Billing,paymethod_tc-9@acord
paymethod_tc,10,ACORD,Collection Institution,paymethod_tc-10@acord
paymethod_tc,11,ACORD,Suspended Billing,paymethod_tc-11@acord
paymethod_tc,12,ACORD,Pay from a Premium Deposit Fund,paymethod_tc-12@acord
paymethod_tc,13,ACORD,Pay From Special Accounts,paymethod_tc-13@acord
paymethod_tc,14,ACORD,Combined Billing,paymethod_tc-14@acord
paymethod_tc,15,ACORD,Automatic Premium Loan,paymethod_tc-15@acord
paymethod_tc,16,ACORD,Discounted Premium,paymethod_tc-16@acord
paymethod_tc,17,ACORD,Dividends on Deposit,paymethod_tc-17@acord
paymethod_tc,25,ACORD,Paid based on premium offset,paymethod_tc-25@acord
paymethod_tc,26,ACORD,Pre-Authorized Check,paymethod_tc-26@acord
paymethod_tc,27,ACORD,Receiving Carrier to Request Release of Funds,paymethod_tc-27@acord
paymethod_tc,28,ACORD,Distributor Has Requested Release of Funds,paymethod_tc-28@acord
paymethod_tc,29,ACORD,Pre-signed post dated cheques,paymethod_tc-29@acord
paymethod_tc,30,ACORD,Premium Waiver,paymethod_tc-30@acord
paymethod_tc,31,ACORD,Deferred Premium Facility,paymethod_tc-31@acord
paymode_tc,0,ACORD,Unknown,paymode_tc-0@acord
paymode_tc,1,ACORD,Annual or Annually,paymode_tc-1@acord
paymode_tc,2,ACORD,Semi-Annual (twice a year),paymode_tc-2@acord
paymode_tc,3,ACORD,Quarter or Quarterly,paymode_tc-3@acord
paymode_tc,4,ACORD,Month or Monthly,paymode_tc-4@acord
paymode_tc,5,ACORD,Semi-Monthly (twice a month),paymode_tc-5@acord
paymode_tc,6,ACORD,Week or Weekly,paymode_tc-6@acord
paymode_tc,7,ACORD,Bi-Weekly (every two weeks),paymode_tc-7@acord
paymode_tc,8,ACORD,Day or Daily,paymode_tc-8@acord
paymode_tc,9,ACORD,Single Payment,paymode_tc-9@acord
paymode_tc,10,ACORD,Monthly for Nine months,paymode_tc-10@acord
paymode_tc,11,ACORD,Random,paymode_tc-11@acord
paymode_tc,12,ACORD,Every 4 weeks (4 weekly),paymode_tc-12@acord
paymode_tc,13,ACORD,Monthly for 10 months,paymode_tc-13@acord
paymode_tc,14,ACORD,Monthly for 8 months,paymode_tc-14@acord
paymode_tc,15,ACORD,Every 2 months,paymode_tc-15@acord
paymode_tc,16,ACORD,Every 4 months,paymode_tc-16@acord
paymode_tc,17,ACORD,Every 5 months,paymode_tc-17@acord
paymode_tc,18,ACORD,Every 7 months,paymode_tc-18@acord
paymode_tc,19,ACORD,Every 8 months,paymode_tc-19@acord
paymode_tc,20,ACORD,Every 9 months,paymode_tc-20@acord
paymode_tc,21,ACORD,Every 10 months,paymode_tc-21@acord
paymode_tc,22,ACORD,Every 11 months,paymode_tc-22@acord
paymode_tc,23,ACORD,Fiscal Quarterly mode of payment,paymode_tc-23@acord
paymode_tc,24,ACORD,Every three weeks,paymode_tc-24@acord
paymode_tc,25,ACORD,Payments made 7 times per year.,paymode_tc-25@acord
paymode_tc,26,ACORD,Payments made 11 times per year.,paymode_tc-26@acord
paymode_tc,27,ACORD,Payments made 14 times per year.,paymode_tc-27@acord
paymode_tc,28,ACORD,Payments made 28 times per year.,paymode_tc-28@acord
paymode_tc,29,ACORD,Payment made 5 times a year,paymode_tc-29@acord
paymode_tc,30,ACORD,Annual Calendar,paymode_tc-30@acord
paymode_tc,31,ACORD,Once every 5 years,paymode_tc-31@acord
paymode_tc,40,ACORD,Lifetime,paymode_tc-40@acord
paymode_tc,41,ACORD,Payment is made once every three years,paymode_tc-41@acord
paymode_tc,42,ACORD,Payments made 9 times a year,paymode_tc-42@acord
paymode_tc,43,ACORD,Payments made 10 times a year,paymode_tc-43@acord
paymode_tc,44,ACORD,Payments made 13 times a year,paymode_tc-44@acord
paymode_tc,45,ACORD,Payments made 16 times a year,paymode_tc-45@acord
paymode_tc,46,ACORD,Payments made 18 times a year,paymode_tc-46@acord
paymode_tc,47,ACORD,Payments made 19 times a year,paymode_tc-47@acord
paymode_tc,48,ACORD,Payments made 20 times a year,paymode_tc-48@acord
paymode_tc,49,ACORD,Payments made 21 times a year,paymode_tc-49@acord
paymode_tc,50,ACORD,Payments made 22 times a year,paymode_tc-50@acord
paymode_tc,51,ACORD,Hour or Hourly,paymode_tc-51@acord
paymode_tc,98,ACORD,Mixed,paymode_tc-98@acord
paymode_tc,99,ACORD,None,paymode_tc-99@acord
paymode_tc,100,ACORD,Any paymode_tc is allowed,paymode_tc-100@acord
paymode_tc,2147483647,ACORD,Other,paymode_tc-2147483647@acord
polprod_tc,0,ACORD,Unknown,polprod_tc-0@acord
polprod_tc,1,ACORD,Whole Life,polprod_tc-1@acord
polprod_tc,2,ACORD,Term,polprod_tc-2@acord
polprod_tc,3,ACORD,Universal Life,polprod_tc-3@acord
polprod_tc,4,ACORD,Variable Universal Life,polprod_tc-4@acord
polprod_tc,5,ACORD,Indexed Universal Life,polprod_tc-5@acord
polprod_tc,6,ACORD,Interest Sensitive Whole Life,polprod_tc-6@acord
polprod_tc,7,ACORD,Excess Interest Life,polprod_tc-7@acord
polprod_tc,8,ACORD,Variable Whole Life,polprod_tc-8@acord
polprod_tc,9,ACORD,Fixed Annuity,polprod_tc-9@acord
polprod_tc,10,ACORD,Variable Annuity,polprod_tc-10@acord
polprod_tc,11,ACORD,Indexed Annuity,polprod_tc-11@acord
polprod_tc,12,ACORD,Income Replacement,polprod_tc-12@acord
polprod_tc,13,ACORD,Major Medical,polprod_tc-13@acord
polprod_tc,14,ACORD,Hospital Indemnity,polprod_tc-14@acord
polprod_tc,15,ACORD,Medicare Supplement,polprod_tc-15@acord
polprod_tc,16,ACORD,Dread Disease,polprod_tc-16@acord
polprod_tc,17,ACORD,Long Term Care,polprod_tc-17@acord
polprod_tc,18,ACORD,Nursing Home,polprod_tc-18@acord
polprod_tc,19,ACORD,Hospital/Surgical,polprod_tc-19@acord
polprod_tc,20,ACORD,Medical Expense,polprod_tc-20@acord
polprod_tc,21,ACORD,Cancer,polprod_tc-21@acord
polprod_tc,22,ACORD,Travel Accident,polprod_tc-22@acord
polprod_tc,23,ACORD,Overhead Expense,polprod_tc-23@acord
polprod_tc,24,ACORD,Buyout,polprod_tc-24@acord
polprod_tc,25,ACORD,Accident and Health,polprod_tc-25@acord
polprod_tc,26,ACORD,Term with Cash Value,polprod_tc-26@acord
polprod_tc,30,ACORD,Critical Illness,polprod_tc-30@acord
polprod_tc,31,ACORD,Disability Income,polprod_tc-31@acord
polprod_tc,32,ACORD,Credit Mortgage,polprod_tc-32@acord
polprod_tc,33,ACORD,Open Ended Investment,polprod_tc-33@acord
polprod_tc,35,ACORD,Funeral Policy,polprod_tc-35@acord
polprod_tc,37,ACORD,Guaranteed Insurability Policy,polprod_tc-37@acord
polprod_tc,39,ACORD,Open ended investment policy for Retirement,polprod_tc-39@acord
polprod_tc,40,ACORD,Errors and Omission Coverage,polprod_tc-40@acord
polprod_tc,42,ACORD,Auto,polprod_tc-42@acord
polprod_tc,43,ACORD,Home,polprod_tc-43@acord
polprod_tc,44,ACORD,Boat,polprod_tc-44@acord
polprod_tc,45,ACORD,PELP,polprod_tc-45@acord
polprod_tc,46,ACORD,Combo,polprod_tc-46@acord
polprod_tc,47,ACORD,Home Health Care,polprod_tc-47@acord
polprod_tc,48,ACORD,Heart/Stroke,polprod_tc-48@acord
polprod_tc,49,ACORD,Intensive Care,polprod_tc-49@acord
polprod_tc,50,ACORD,Short Term Care,polprod_tc-50@acord
polprod_tc,51,ACORD,Accidental Death & Dismemberment,polprod_tc-51@acord
polprod_tc,52,ACORD,Short Term Disability,polprod_tc-52@acord
polprod_tc,53,ACORD,Long Term Disability,polprod_tc-53@acord
polprod_tc,54,ACORD,Dental,polprod_tc-54@acord
polprod_tc,55,ACORD,Vision,polprod_tc-55@acord
ProductType,1,iGO,3,producttype-1@igo
ProductType,2,iGO,1,producttype-2@igo
ProductType,3,iGO,2,producttype-3@igo
ProductType,4,iGO,16,producttype-4@igo
ProductType,5,iGO,74,producttype-5@igo
ProductType,9,iGO,14,producttype-9@igo
ProductType,12,iGO,31,producttype-12@igo
ProductType,23,iGO,31,producttype-23@igo
ProductType,24,iGO,31,producttype-24@igo
ratings_tc,0,ACORD,Unknown,ratings_tc-0@acord
ratings_tc,1,ACORD,None,ratings_tc-1@acord
ratings_tc,2,ACORD,125%,ratings_tc-2@acord
ratings_tc,3,ACORD,137.50%,ratings_tc-3@acord
ratings_tc,4,ACORD,150%,ratings_tc-4@acord
ratings_tc,5,ACORD,162.50%,ratings_tc-5@acord
ratings_tc,6,ACORD,175%,ratings_tc-6@acord
ratings_tc,7,ACORD,200%,ratings_tc-7@acord
ratings_tc,8,ACORD,225%,ratings_tc-8@acord
ratings_tc,9,ACORD,250%,ratings_tc-9@acord
ratings_tc,10,ACORD,275%,ratings_tc-10@acord
ratings_tc,11,ACORD,300%,ratings_tc-11@acord
ratings_tc,12,ACORD,325%,ratings_tc-12@acord
ratings_tc,13,ACORD,350%,ratings_tc-13@acord
ratings_tc,14,ACORD,375%,ratings_tc-14@acord
ratings_tc,15,ACORD,400%,ratings_tc-15@acord
ratings_tc,16,ACORD,425%,ratings_tc-16@acord
ratings_tc,17,ACORD,450%,ratings_tc-17@acord
ratings_tc,18,ACORD,475%,ratings_tc-18@acord
ratings_tc,19,ACORD,500%,ratings_tc-19@acord
ratings_tc,20,ACORD,Uninsurable and/or declined,ratings_tc-20@acord
rel_tc,0,ACORD,Unknown,rel_tc-0@acord
rel_tc,1,ACORD,Spouse,rel_tc-1@acord
rel_tc,2,ACORD,Child,rel_tc-2@acord
rel_tc,3,ACORD,Parent,rel_tc-3@acord
rel_tc,4,ACORD,Sibling,rel_tc-4@acord
rel_tc,5,ACORD,Family,rel_tc-5@acord
rel_tc,6,ACORD,Employee,rel_tc-6@acord
rel_tc,7,ACORD,Employer,rel_tc-7@acord
rel_tc,8,ACORD,Owner,rel_tc-8@acord
rel_tc,9,ACORD,Partner,rel_tc-9@acord
rel_tc,10,ACORD,Advisor,rel_tc-10@acord
rel_tc,11,ACORD,Agent,rel_tc-11@acord
rel_tc,12,ACORD,Referral,rel_tc-12@acord
rel_tc,13,ACORD,Nominator,rel_tc-13@acord
rel_tc,14,ACORD,Friend,rel_tc-14@acord
rel_tc,15,ACORD,Domestic Partner,rel_tc-15@acord
rel_tc,16,ACORD,Roommate,rel_tc-16@acord
rel_tc,17,ACORD,Business Contact,rel_tc-17@acord
rel_tc,18,ACORD,Household,rel_tc-18@acord
rel_tc,20,ACORD,Advisee,rel_tc-20@acord
rel_tc,21,ACORD,Client,rel_tc-21@acord
rel_tc,22,ACORD,Contact w/ Business,rel_tc-22@acord
rel_tc,23,ACORD,Household Head,rel_tc-23@acord
rel_tc,24,ACORD,Household Member,rel_tc-24@acord
rel_tc,25,ACORD,Owned By,rel_tc-25@acord
rel_tc,26,ACORD,Board Member,rel_tc-26@acord
rel_tc,27,ACORD,Legal Guardian,rel_tc-27@acord
rel_tc,28,ACORD,Group,rel_tc-28@acord
rel_tc,29,ACORD,Group Contact,rel_tc-29@acord
rel_tc,30,ACORD,Group Member Party,rel_tc-30@acord
rel_tc,31,ACORD,Payer,rel_tc-31@acord
rel_tc,32,ACORD,Insured,rel_tc-32@acord
rel_tc,33,ACORD,Coverage Insured,rel_tc-33@acord
rel_tc,34,ACORD,Primary Beneficiar,rel_tc-34@acord
rel_tc,35,ACORD,Annuitant,rel_tc-35@acord
rel_tc,36,ACORD,Contingent Beneficiary,rel_tc-36@acord
rel_tc,37,ACORD,Primary Writing Agent,rel_tc-37@acord
rel_tc,38,ACORD,Primary Servicing Agent,rel_tc-38@acord
rel_tc,39,ACORD,Assigned Agent,rel_tc-39@acord
rel_tc,40,ACORD,Dependent,rel_tc-40@acord
rel_tc,41,ACORD,Physician,rel_tc-41@acord
rel_tc,42,ACORD,Patient,rel_tc-42@acord
rel_tc,43,ACORD,Originator,rel_tc-43@acord
rel_tc,44,ACORD,Target,rel_tc-44@acord
rel_tc,45,ACORD,Performer,rel_tc-45@acord
rel_tc,46,ACORD,Superior Agent,rel_tc-46@acord
rel_tc,47,ACORD,Subordinate Agent,rel_tc-47@acord
rel_tc,48,ACORD,General Agent,rel_tc-48@acord
rel_tc,49,ACORD,Package Holder,rel_tc-49@acord
rel_tc,50,ACORD,Package Component,rel_tc-50@acord
rel_tc,51,ACORD,Consignee Agent,rel_tc-51@acord
rel_tc,52,ACORD,Additional Writing Agent,rel_tc-52@acord
rel_tc,53,ACORD,Regional Agent,rel_tc-53@acord
rel_tc,54,ACORD,Plan Sponsor,rel_tc-54@acord
rel_tc,55,ACORD,Assignee Beneficiary,rel_tc-55@acord
rel_tc,56,ACORD,Tertiary Beneficiary,rel_tc-56@acord
rel_tc,57,ACORD,Custodian,rel_tc-57@acord
rel_tc,58,ACORD,Primary Physician,rel_tc-58@acord
rel_tc,59,ACORD,Trustee of Minor,rel_tc-59@acord
rel_tc,60,ACORD,Trusteed Minor,rel_tc-60@acord
rel_tc,61,ACORD,Trustee of Incompetent,rel_tc-61@acord
rel_tc,62,ACORD,Trusteed Incompetent,rel_tc-62@acord
rel_tc,63,ACORD,Replaced,rel_tc-63@acord
rel_tc,64,ACORD,Replaced by,rel_tc-64@acord
rel_tc,65,ACORD,Rollover,rel_tc-65@acord
rel_tc,66,ACORD,Rolled into,rel_tc-66@acord
rel_tc,67,ACORD,Exchanged,rel_tc-67@acord
rel_tc,68,ACORD,"Exchanged For (previously named ""Exchanged By"")",rel_tc-68@acord
rel_tc,69,ACORD,Trustee,rel_tc-69@acord
rel_tc,70,ACORD,Curator,rel_tc-70@acord
rel_tc,71,ACORD,Shareholder,rel_tc-71@acord
rel_tc,72,ACORD,Security Cession (collateral),rel_tc-72@acord
rel_tc,73,ACORD,Absolute Cession (collateral),rel_tc-73@acord
rel_tc,74,ACORD,Investor,rel_tc-74@acord
rel_tc,75,ACORD,Member,rel_tc-75@acord
rel_tc,76,ACORD,As Applied,rel_tc-76@acord
rel_tc,77,ACORD,As Approved,rel_tc-77@acord
rel_tc,78,ACORD,Successor Owner,rel_tc-78@acord
rel_tc,80,ACORD,Health Insurer,rel_tc-80@acord
rel_tc,81,ACORD,Joint Marketing Agreement,rel_tc-81@acord
rel_tc,82,ACORD,Registered Representative,rel_tc-82@acord
rel_tc,83,ACORD,Broker/Dealer,rel_tc-83@acord
rel_tc,84,ACORD,Paramedical Examiner,rel_tc-84@acord
rel_tc,85,ACORD,Superior Office,rel_tc-85@acord
rel_tc,86,ACORD,Subordinate Office,rel_tc-86@acord
rel_tc,87,ACORD,Carrier,rel_tc-87@acord
rel_tc,88,ACORD,Holding Company,rel_tc-88@acord
rel_tc,89,ACORD,Subsidiary Company,rel_tc-89@acord
rel_tc,90,ACORD,Paramed Company,rel_tc-90@acord
rel_tc,91,ACORD,Requested By,rel_tc-91@acord
rel_tc,92,ACORD,Grandparent,rel_tc-92@acord
rel_tc,93,ACORD,Grandchild,rel_tc-93@acord
rel_tc,94,ACORD,Step-Child,rel_tc-94@acord
rel_tc,95,ACORD,Counter signing Agent,rel_tc-95@acord
rel_tc,96,ACORD,Applicant,rel_tc-96@acord
rel_tc,97,ACORD,Requestor,rel_tc-97@acord
rel_tc,99,ACORD,Fulfills,rel_tc-99@acord
rel_tc,100,ACORD,Fulfilled By,rel_tc-100@acord
rel_tc,101,ACORD,Scenario Participant,rel_tc-101@acord
rel_tc,102,ACORD,Medical Provider,rel_tc-102@acord
rel_tc,103,ACORD,Nominee Name,rel_tc-103@acord
rel_tc,104,ACORD,Intermediary,rel_tc-104@acord
rel_tc,105,ACORD,Form has been attached to another form,rel_tc-105@acord
rel_tc,106,ACORD,This form has been physically included in another form,rel_tc-106@acord
rel_tc,108,ACORD,Signing Officer,rel_tc-108@acord
rel_tc,109,ACORD,Creditor,rel_tc-109@acord
rel_tc,110,ACORD,Creditor Of,rel_tc-110@acord
rel_tc,111,ACORD,Fiancé,rel_tc-111@acord
rel_tc,112,ACORD,Underwriter,rel_tc-112@acord
rel_tc,113,ACORD,Power of Attorney,rel_tc-113@acord
rel_tc,114,ACORD,Power of Attorney For xxx,rel_tc-114@acord
rel_tc,115,ACORD,Banker,rel_tc-115@acord
rel_tc,116,ACORD,Banker of,rel_tc-116@acord
rel_tc,117,ACORD,Attached To Form,rel_tc-117@acord
rel_tc,118,ACORD,Add To Form,rel_tc-118@acord
rel_tc,119,ACORD,Payee,rel_tc-119@acord
rel_tc,120,ACORD,Agent of Agency,rel_tc-120@acord
rel_tc,121,ACORD,Agency,rel_tc-121@acord
rel_tc,122,ACORD,Original Holding,rel_tc-122@acord
rel_tc,123,ACORD,Alternate Holding,rel_tc-123@acord
rel_tc,124,ACORD,Additional Holding,rel_tc-124@acord
rel_tc,125,ACORD,Original to Additional Holding,rel_tc-125@acord
rel_tc,126,ACORD,Additional Servicing Agent,rel_tc-126@acord
rel_tc,127,ACORD,Third Party Designee,rel_tc-127@acord
rel_tc,128,ACORD,Qualified Adult,rel_tc-128@acord
rel_tc,131,ACORD,Step Parent,rel_tc-131@acord
rel_tc,132,ACORD,Great Grandchild,rel_tc-132@acord
rel_tc,133,ACORD,Great Grandparent,rel_tc-133@acord
rel_tc,134,ACORD,Foster Child,rel_tc-134@acord
rel_tc,135,ACORD,Foster Parent,rel_tc-135@acord
rel_tc,136,ACORD,Foster Sibling,rel_tc-136@acord
rel_tc,137,ACORD,God Child,rel_tc-137@acord
rel_tc,138,ACORD,God Parent,rel_tc-138@acord
rel_tc,139,ACORD,Parents-in-law,rel_tc-139@acord
rel_tc,141,ACORD,Ceding Company to Reinsurance Company,rel_tc-141@acord
rel_tc,142,ACORD,Reinsurance Company to Retrocessionaire,rel_tc-142@acord
rel_tc,143,ACORD,Specific Coverage to Reinsurance Carrier,rel_tc-143@acord
rel_tc,144,ACORD,Primary Holding for a Collection,rel_tc-144@acord
rel_tc,145,ACORD,Assignee,rel_tc-145@acord
rel_tc,146,ACORD,Business Associate,rel_tc-146@acord
rel_tc,148,ACORD,Plan Participant,rel_tc-148@acord
rel_tc,149,ACORD,Depositor,rel_tc-149@acord
rel_tc,150,ACORD,Authorized Person,rel_tc-150@acord
rel_tc,153,ACORD,Contingent Annuitant,rel_tc-153@acord
rel_tc,154,ACORD,Servicing Agency,rel_tc-154@acord
rel_tc,156,ACORD,Business,rel_tc-156@acord
rel_tc,158,ACORD,Romantic Interest of some kind,rel_tc-158@acord
rel_tc,160,ACORD,Non Relative,rel_tc-160@acord
rel_tc,162,ACORD,Claim Processor,rel_tc-162@acord
rel_tc,164,ACORD,Retiree,rel_tc-164@acord
rel_tc,166,ACORD,Converted,rel_tc-166@acord
rel_tc,167,ACORD,Converted To,rel_tc-167@acord
rel_tc,168,ACORD,Self,rel_tc-168@acord
rel_tc,169,ACORD,All but self,rel_tc-169@acord
rel_tc,170,ACORD,Half Sibling,rel_tc-170@acord
rel_tc,171,ACORD,Child-in-Law,rel_tc-171@acord
rel_tc,172,ACORD,Step-Sibling,rel_tc-172@acord
rel_tc,173,ACORD,Common Law Spouse,rel_tc-173@acord
rel_tc,174,ACORD,Former Spouse,rel_tc-174@acord
rel_tc,177,ACORD,Contingent Owner,rel_tc-177@acord
rel_tc,178,ACORD,Former Employer due to Retirement,rel_tc-178@acord
rel_tc,179,ACORD,Legal Ward,rel_tc-179@acord
rel_tc,180,ACORD,New to Old Address,rel_tc-180@acord
rel_tc,182,ACORD,Writing Agency,rel_tc-182@acord
rel_tc,183,ACORD,Joint Annuitant,rel_tc-183@acord
rel_tc,184,ACORD,Joint Owner,rel_tc-184@acord
rel_tc,185,ACORD,Recruitee,rel_tc-185@acord
rel_tc,186,ACORD,Recruiter,rel_tc-186@acord
rel_tc,187,ACORD,Surrendering administration carrier for exchanged policy,rel_tc-187@acord
rel_tc,189,ACORD,Joint Insured,rel_tc-189@acord
rel_tc,191,ACORD,Owner's (or Joint Owner's) Beneficiary,rel_tc-191@acord
rel_tc,192,ACORD,Owner's (or Joint Owner's) Contingent Beneficiary,rel_tc-192@acord
rel_tc,193,ACORD,Plan Administrator,rel_tc-193@acord
rel_tc,194,ACORD,Settlement info,rel_tc-194@acord
rel_tc,196,ACORD,Sibling in Law,rel_tc-196@acord
rel_tc,198,ACORD,Parents Sibling,rel_tc-198@acord
rel_tc,199,ACORD,Sibling's Child,rel_tc-199@acord
rel_tc,203,ACORD,Co-Mortgagor,rel_tc-203@acord
rel_tc,204,ACORD,National Marketing Organization,rel_tc-204@acord
rel_tc,205,ACORD,Conservator,rel_tc-205@acord
rel_tc,207,ACORD,The entities have an affinity relationship with one another,rel_tc-207@acord
rel_tc,208,ACORD,Designated/Responsible Producer,rel_tc-208@acord
rel_tc,209,ACORD,Designated/Responsible entity,rel_tc-209@acord
rel_tc,210,ACORD,Designated/Responsible Officer/Director (not Owner/Partner),rel_tc-210@acord
rel_tc,211,ACORD,The child of an aunt or uncle,rel_tc-211@acord
rel_tc,212,ACORD,Regional Office,rel_tc-212@acord
rel_tc,213,ACORD,Home Office,rel_tc-213@acord
rel_tc,214,ACORD,Reinsurer to Cedent,rel_tc-214@acord
rel_tc,215,ACORD,Retrocessionnaire to Reinsurer,rel_tc-215@acord
rel_tc,216,ACORD,Whether the agent's office is remote or not,rel_tc-216@acord
rel_tc,217,ACORD,Campaign,rel_tc-217@acord
rel_tc,218,ACORD,Experience Group,rel_tc-218@acord
rel_tc,220,ACORD,Government Allotter,rel_tc-220@acord
rel_tc,221,ACORD,Payment Receiving Agency,rel_tc-221@acord
rel_tc,223,ACORD,Adoptive Parent,rel_tc-223@acord
rel_tc,224,ACORD,Adopted Child,rel_tc-224@acord
rel_tc,227,ACORD,Dividend Payee,rel_tc-227@acord
rel_tc,228,ACORD,Successor Custodian,rel_tc-228@acord
rel_tc,230,ACORD,Assistant,rel_tc-230@acord
rel_tc,231,ACORD,Assistee,rel_tc-231@acord
rel_tc,232,ACORD,Child Not Yet Legally Adopted,rel_tc-232@acord
rel_tc,234,ACORD,Prior Client,rel_tc-234@acord
rel_tc,235,ACORD,Case Manager,rel_tc-235@acord
rel_tc,236,ACORD,Grantor,rel_tc-236@acord
rel_tc,237,ACORD,Language Interpreter,rel_tc-237@acord
rel_tc,238,ACORD,Grantee,rel_tc-238@acord
rel_tc,239,ACORD,Case Managed By,rel_tc-239@acord
rel_tc,240,ACORD,Task,rel_tc-240@acord
rel_tc,241,ACORD,Recipient,rel_tc-241@acord
rel_tc,242,ACORD,Interpretee,rel_tc-242@acord
rel_tc,243,ACORD,Case,rel_tc-243@acord
rel_tc,244,ACORD,Notary Public,rel_tc-244@acord
rel_tc,245,ACORD,Physical Therapist,rel_tc-245@acord
rel_tc,246,ACORD,Skilled Nurse,rel_tc-246@acord
rel_tc,247,ACORD,Succeeding Beneficiary,rel_tc-247@acord
rel_tc,248,ACORD,Authorized user,rel_tc-248@acord
rel_tc,250,ACORD,Collateral Assignee,rel_tc-250@acord
rel_tc,251,ACORD,Coverage Primary Agent,rel_tc-251@acord
rel_tc,252,ACORD,Coverage Servicing Agent,rel_tc-252@acord
rel_tc,253,ACORD,Ancillary Holding to Primary Holding,rel_tc-253@acord
rel_tc,254,ACORD,Primary Holding for one or more Ancillary Holdings,rel_tc-254@acord
rel_tc,255,ACORD,Suitability and Compliance Reviewer,rel_tc-255@acord
rel_tc,256,ACORD,Holding is Part of a Structured Settlement Case,rel_tc-256@acord
rel_tc,257,ACORD,Registered Investment Advisor ,rel_tc-257@acord
rel_tc,258,ACORD,Submitter,rel_tc-258@acord
rel_tc,259,ACORD,Form Preparer,rel_tc-259@acord
rel_tc,260,ACORD,Primary Contact,rel_tc-260@acord
rel_tc,261,ACORD,Marketing Team,rel_tc-261@acord
rel_tc,262,ACORD,Response Party,rel_tc-262@acord
rel_tc,263,ACORD,Biological Child,rel_tc-263@acord
rel_tc,264,ACORD,Unborn Child,rel_tc-264@acord
rel_tc,265,ACORD,Authentication Challenge/Response Questions Party,rel_tc-265@acord
rel_tc,275,ACORD,Additional Compensation Recipient,rel_tc-275@acord
rel_tc,276,ACORD,Informant,rel_tc-276@acord
rel_tc,277,ACORD,Funeral Parlour,rel_tc-277@acord
rel_tc,278,ACORD,Companion,rel_tc-278@acord
rel_tc,279,ACORD,Mentor,rel_tc-279@acord
rel_tc,280,ACORD,Mentored By,rel_tc-280@acord
rel_tc,281,ACORD,Attorney's Client,rel_tc-281@acord
rel_tc,282,ACORD,Managing Office,rel_tc-282@acord
rel_tc,283,ACORD,Managed Office,rel_tc-283@acord
rel_tc,284,ACORD,Associate Member,rel_tc-284@acord
rel_tc,285,ACORD,Legal Interest,rel_tc-285@acord
rel_tc,286,ACORD,Accountant,rel_tc-286@acord
rel_tc,287,ACORD,Attorney,rel_tc-287@acord
rel_tc,288,ACORD,Accountant's Client,rel_tc-288@acord
rel_tc,289,ACORD,Reference,rel_tc-289@acord
rel_tc,290,ACORD,Reference for,rel_tc-290@acord
rel_tc,291,ACORD,Collateral For,rel_tc-291@acord
rel_tc,292,ACORD,Collateralized by,rel_tc-292@acord
rel_tc,293,ACORD,Borrower,rel_tc-293@acord
rel_tc,294,ACORD,Existing Holding With,rel_tc-294@acord
rel_tc,295,ACORD,Field Wholesaler,rel_tc-295@acord
rel_tc,296,ACORD,Internal Wholesaler,rel_tc-296@acord
rel_tc,297,ACORD,Regional Sales Manager,rel_tc-297@acord
rel_tc,298,ACORD,Operations Account Manager,rel_tc-298@acord
rel_tc,299,ACORD,Billing Recipient,rel_tc-299@acord
rel_tc,300,ACORD,Coordinator of Benefits,rel_tc-300@acord
rel_tc,301,ACORD,Business Development Specialist,rel_tc-301@acord
rel_tc,302,ACORD,Product Specialist,rel_tc-302@acord
rel_tc,303,ACORD,Contract Distributor / MGA,rel_tc-303@acord
rel_tc,304,ACORD,Disabled Adult Dependent,rel_tc-304@acord
rel_tc,305,ACORD,Disabled Adult Provider,rel_tc-305@acord
rel_tc,306,ACORD,Adoptive Sibling,rel_tc-306@acord
rel_tc,307,ACORD,Sibling of Grandparent,rel_tc-307@acord
rel_tc,308,ACORD,Grandchild of Sibling,rel_tc-308@acord
rel_tc,309,ACORD,Medical Declaration Provider,rel_tc-309@acord
rel_tc,310,ACORD,Decedent,rel_tc-310@acord
rel_tc,311,ACORD,Associated,rel_tc-311@acord
rel_tc,312,ACORD,Assignor,rel_tc-312@acord
rel_tc,313,ACORD,DistributionAgreement,rel_tc-313@acord
rel_tc,314,ACORD,Previous Owner of a Re-traded policy,rel_tc-314@acord
rel_tc,315,ACORD,Retirement Fund,rel_tc-315@acord
rel_tc,316,ACORD,Participating Employer,rel_tc-316@acord
rel_tc,999,ACORD,Any Relationship is Acceptable,rel_tc-999@acord
rel_tc,1001,ACORD,Hit,rel_tc-1001@acord
rel_tc,1002,ACORD,Try,rel_tc-1002@acord
rel_tc,2147483647,ACORD,Other,rel_tc-2147483647@acord
reldesc_tc,0,ACORD,Unknown,reldesc_tc-0@acord
reldesc_tc,1,ACORD,Husband,reldesc_tc-1@acord
reldesc_tc,2,ACORD,Wife,reldesc_tc-2@acord
reldesc_tc,3,ACORD,Father,reldesc_tc-3@acord
reldesc_tc,4,ACORD,Mother,reldesc_tc-4@acord
reldesc_tc,5,ACORD,Son,reldesc_tc-5@acord
reldesc_tc,6,ACORD,Daughter,reldesc_tc-6@acord
reldesc_tc,7,ACORD,Brother,reldesc_tc-7@acord
reldesc_tc,8,ACORD,Sister,reldesc_tc-8@acord
reldesc_tc,9,ACORD,Ex-husband,reldesc_tc-9@acord
reldesc_tc,10,ACORD,Ex-wife,reldesc_tc-10@acord
reldesc_tc,11,ACORD,Step Mother,reldesc_tc-11@acord
reldesc_tc,12,ACORD,Step Father,reldesc_tc-12@acord
reldesc_tc,13,ACORD,Step Son,reldesc_tc-13@acord
reldesc_tc,14,ACORD,Step Daughter,reldesc_tc-14@acord
reldesc_tc,15,ACORD,Step Brother,reldesc_tc-15@acord
reldesc_tc,16,ACORD,Step Sister,reldesc_tc-16@acord
reldesc_tc,17,ACORD,Grandfather,reldesc_tc-17@acord
reldesc_tc,18,ACORD,Grandmother,reldesc_tc-18@acord
reldesc_tc,19,ACORD,Grandson,reldesc_tc-19@acord
reldesc_tc,20,ACORD,Granddaughter,reldesc_tc-20@acord
reldesc_tc,21,ACORD,Father-in-law,reldesc_tc-21@acord
reldesc_tc,22,ACORD,Mother-in-law,reldesc_tc-22@acord
reldesc_tc,23,ACORD,Son-in-law,reldesc_tc-23@acord
reldesc_tc,24,ACORD,Daughter-in-law,reldesc_tc-24@acord
reldesc_tc,25,ACORD,Brother-in-law,reldesc_tc-25@acord
reldesc_tc,26,ACORD,Sister-in-law,reldesc_tc-26@acord
reldesc_tc,27,ACORD,Half Brother,reldesc_tc-27@acord
reldesc_tc,28,ACORD,Half Sister,reldesc_tc-28@acord
reldesc_tc,29,ACORD,Cousin (Male cousin - non English),reldesc_tc-29@acord
reldesc_tc,30,ACORD,Uncle,reldesc_tc-30@acord
reldesc_tc,31,ACORD,Aunt,reldesc_tc-31@acord
reldesc_tc,32,ACORD,Nephew,reldesc_tc-32@acord
reldesc_tc,33,ACORD,Niece,reldesc_tc-33@acord
reldesc_tc,34,ACORD,God Father,reldesc_tc-34@acord
reldesc_tc,35,ACORD,God Mother,reldesc_tc-35@acord
reldesc_tc,37,ACORD,Secretary,reldesc_tc-37@acord
reldesc_tc,38,ACORD,General Manager,reldesc_tc-38@acord
reldesc_tc,39,ACORD,President,reldesc_tc-39@acord
reldesc_tc,40,ACORD,Vice President,reldesc_tc-40@acord
reldesc_tc,41,ACORD,Executive,reldesc_tc-41@acord
reldesc_tc,42,ACORD,Attorney,reldesc_tc-42@acord
reldesc_tc,43,ACORD,Auditor,reldesc_tc-43@acord
reldesc_tc,44,ACORD,Bookkeeper,reldesc_tc-44@acord
reldesc_tc,45,ACORD,Consultant,reldesc_tc-45@acord
reldesc_tc,46,ACORD,Chairman of the Board,reldesc_tc-46@acord
reldesc_tc,47,ACORD,Chief Executive Officer,reldesc_tc-47@acord
reldesc_tc,48,ACORD,Chief Financial Officer,reldesc_tc-48@acord
reldesc_tc,49,ACORD,Chief Operating Officer,reldesc_tc-49@acord
reldesc_tc,50,ACORD,Chief Information Officer,reldesc_tc-50@acord
reldesc_tc,52,ACORD,Tax Agent,reldesc_tc-52@acord
reldesc_tc,53,ACORD,Estate Agent,reldesc_tc-53@acord
reldesc_tc,54,ACORD,Legal Agent,reldesc_tc-54@acord
reldesc_tc,55,ACORD,God Son,reldesc_tc-55@acord
reldesc_tc,56,ACORD,God Daughter,reldesc_tc-56@acord
reldesc_tc,57,ACORD,Owner of Cash Value,reldesc_tc-57@acord
reldesc_tc,58,ACORD,Owner of Death Benefit,reldesc_tc-58@acord
reldesc_tc,59,ACORD,Owner of cash value and death benefit,reldesc_tc-59@acord
reldesc_tc,60,ACORD,Fiancé (male),reldesc_tc-60@acord
reldesc_tc,61,ACORD,Common Law Wife,reldesc_tc-61@acord
reldesc_tc,62,ACORD,Common Law Husband,reldesc_tc-62@acord
reldesc_tc,63,ACORD,Great Aunt (Grandaunt),reldesc_tc-63@acord
reldesc_tc,64,ACORD,Great Uncle (Granduncle),reldesc_tc-64@acord
reldesc_tc,65,ACORD,Grand Nephew,reldesc_tc-65@acord
reldesc_tc,66,ACORD,Grand Niece,reldesc_tc-66@acord
reldesc_tc,67,ACORD,Great Grandson,reldesc_tc-67@acord
reldesc_tc,68,ACORD,Great Granddaughter,reldesc_tc-68@acord
reldesc_tc,69,ACORD,Great Grandfather,reldesc_tc-69@acord
reldesc_tc,70,ACORD,Great Grandmother,reldesc_tc-70@acord
reldesc_tc,71,ACORD,Foster Son,reldesc_tc-71@acord
reldesc_tc,72,ACORD,Foster Daughter,reldesc_tc-72@acord
reldesc_tc,73,ACORD,Foster Father,reldesc_tc-73@acord
reldesc_tc,74,ACORD,Foster Mother,reldesc_tc-74@acord
reldesc_tc,75,ACORD,Foster Brother,reldesc_tc-75@acord
reldesc_tc,76,ACORD,Foster Sister,reldesc_tc-76@acord
reldesc_tc,77,ACORD,Accountant,reldesc_tc-77@acord
reldesc_tc,78,ACORD,CPA,reldesc_tc-78@acord
reldesc_tc,79,ACORD,Financial Advisor,reldesc_tc-79@acord
reldesc_tc,80,ACORD,Stockbroker,reldesc_tc-80@acord
reldesc_tc,81,ACORD,Estate Planner,reldesc_tc-81@acord
reldesc_tc,82,ACORD,Charitable Advisor,reldesc_tc-82@acord
reldesc_tc,83,ACORD,Business Insurance Advisor,reldesc_tc-83@acord
reldesc_tc,84,ACORD,Business Accountant,reldesc_tc-84@acord
reldesc_tc,85,ACORD,Business CPA,reldesc_tc-85@acord
reldesc_tc,86,ACORD,Business Attorney,reldesc_tc-86@acord
reldesc_tc,87,ACORD,Valuation Analyst,reldesc_tc-87@acord
reldesc_tc,88,ACORD,Boy Friend,reldesc_tc-88@acord
reldesc_tc,89,ACORD,Girl Friend,reldesc_tc-89@acord
reldesc_tc,90,ACORD,Fiancée (engaged female),reldesc_tc-90@acord
reldesc_tc,91,ACORD,Self,reldesc_tc-91@acord
reldesc_tc,92,ACORD,Custodian,reldesc_tc-92@acord
reldesc_tc,95,ACORD,Cousin - Female cousin,reldesc_tc-95@acord
reldesc_tc,96,ACORD,Day-to-day Contact,reldesc_tc-96@acord
reldesc_tc,97,ACORD,Benefits Administrator,reldesc_tc-97@acord
reldesc_tc,98,ACORD,Account Specialist,reldesc_tc-98@acord
reldesc_tc,99,ACORD,Administrative Unit,reldesc_tc-99@acord
reldesc_tc,100,ACORD,Special Care Agency,reldesc_tc-100@acord
reldesc_tc,101,ACORD,Special Care Agent,reldesc_tc-101@acord
reldesc_tc,102,ACORD,Adopted Daughter,reldesc_tc-102@acord
reldesc_tc,103,ACORD,Adopted Son,reldesc_tc-103@acord
reldesc_tc,104,ACORD,Adoptive Mother,reldesc_tc-104@acord
reldesc_tc,105,ACORD,Adoptive Father,reldesc_tc-105@acord
reldesc_tc,106,ACORD,Internal Replacement,reldesc_tc-106@acord
reldesc_tc,107,ACORD,External Replacement,reldesc_tc-107@acord
reldesc_tc,108,ACORD,Finance Purchase,reldesc_tc-108@acord
reldesc_tc,109,ACORD,Term Conversion,reldesc_tc-109@acord
reldesc_tc,110,ACORD,Guaranteed Purchase Option,reldesc_tc-110@acord
reldesc_tc,111,ACORD,Group Conversion,reldesc_tc-111@acord
reldesc_tc,112,ACORD,Replaced in Same Statutory Company,reldesc_tc-112@acord
reldesc_tc,113,ACORD,Replaced Between Statutory Companies,reldesc_tc-113@acord
reldesc_tc,114,ACORD,Adoptive Brother,reldesc_tc-114@acord
reldesc_tc,115,ACORD,Adoptive Sister,reldesc_tc-115@acord
reldesc_tc,116,ACORD,Housekeeper,reldesc_tc-116@acord
reldesc_tc,117,ACORD,Informal,reldesc_tc-117@acord
reldesc_tc,118,ACORD,Formal,reldesc_tc-118@acord
reldesc_tc,119,ACORD,Companion,reldesc_tc-119@acord
reldesc_tc,2147483647,ACORD,Other,reldesc_tc-2147483647@acord
ReqCode,3,iGO,HIV,reqcode-3@igo
ReqCode,6,iGO,HIV,reqcode-6@igo
ReqCode,10,iGO,Exam,reqcode-10@igo
ReqCode,23,iGO,Authorization,reqcode-23@igo
ReqCode,102,iGO,Q_Aviation,reqcode-102@igo
ReqCode,103,iGO,Q_Avocation,reqcode-103@igo
ReqCode,106,iGO,Q_Medical,reqcode-106@igo
ReqCode,107,iGO,Q_Asthma,reqcode-107@igo
ReqCode,111,iGO,Q_Diabetes,reqcode-111@igo
ReqCode,114,iGO,Q_Alcohol,reqcode-114@igo
ReqCode,115,iGO,Q_Drug,reqcode-115@igo
ReqCode,116,iGO,Q_Tobacco,reqcode-116@igo
ReqCode,117,iGO,Q_Financial,reqcode-117@igo
ReqCode,118,iGO,Q_Military,reqcode-118@igo
ReqCode,120,iGO,Q_Other,reqcode-120@igo
ReqCode,127,iGO,Replacement,reqcode-127@igo
ReqCode,134,iGO,1035_Exchange,reqcode-134@igo
ReqCode,135,iGO,Application,reqcode-135@igo
ReqCode,140,iGO,Authorization,reqcode-140@igo
ReqCode,141,iGO,Payroll_Deduc,reqcode-141@igo
ReqCode,142,iGO,Authorization,reqcode-142@igo
ReqCode,143,iGO,Authorization,reqcode-143@igo
ReqCode,148,iGO,Disclosure,reqcode-148@igo
ReqCode,157,iGO,Application,reqcode-157@igo
ReqCode,165,iGO,Application,reqcode-165@igo
ReqCode,170,iGO,Disclosure,reqcode-170@igo
ReqCode,210,iGO,Q_Travel,reqcode-210@igo
ReqCode,211,iGO,Q_Residence,reqcode-211@igo
ReqCode,220,iGO,Authorization,reqcode-220@igo
ReqCode,225,iGO,Application,reqcode-225@igo
ReqCode,246,iGO,Cert_Comp_Illustrat,reqcode-246@igo
ReqCode,251,iGO,Disclosure,reqcode-251@igo
ReqCode,260,iGO,NAIC Replacement,reqcode-260@igo
ReqCode,266,iGO,Non- Med,reqcode-266@igo
ReqCode,315,iGO,Application,reqcode-315@igo
ReqCode,510,iGO,App_Supp,reqcode-510@igo
ReqCode,514,iGO,Authorization,reqcode-514@igo
ReqCode,532,iGO,Authorization,reqcode-532@igo
ReqCode,600,iGO,Application,reqcode-600@igo
ReqCode,633,iGO,Application,reqcode-633@igo
ReqCode,634,iGO,Application,reqcode-634@igo
ReqCode,635,iGO,Application,reqcode-635@igo
ReqCode,694,iGO,Replacement,reqcode-694@igo
ReqCode,702,iGO,Authorization,reqcode-702@igo
ReqCode,818,iGO,Child_Rider,reqcode-818@igo
ReqCode,822,iGO,HIPAA,reqcode-822@igo
ReqCode,840,iGO,Authorization,reqcode-840@igo
ReqCode,859,iGO,Authorization,reqcode-859@igo
ReqCode,866,iGO,Application,reqcode-866@igo
ReqCode,893,iGO,AgentInstruc,reqcode-893@igo
ReqCode,895,iGO,Guide,reqcode-895@igo
smokerstat_tc,0,ACORD,Unknown,smokerstat_tc-0@acord
smokerstat_tc,1,ACORD,Never,smokerstat_tc-1@acord
smokerstat_tc,2,ACORD,Prior,smokerstat_tc-2@acord
smokerstat_tc,3,ACORD,Current,smokerstat_tc-3@acord
smokerstat_tc,2147483647,ACORD,Other,smokerstat_tc-2147483647@acord
state_tc,1,ACORD,Alabama,state_tc-1@acord
state_tc,2,ACORD,Alaska,state_tc-2@acord
state_tc,3,ACORD,American Samoa,state_tc-3@acord
state_tc,4,ACORD,Arizona,state_tc-4@acord
state_tc,5,ACORD,Arkansas,state_tc-5@acord
state_tc,6,ACORD,California,state_tc-6@acord
state_tc,7,ACORD,Colorado,state_tc-7@acord
state_tc,8,ACORD,Connecticut,state_tc-8@acord
state_tc,9,ACORD,Delaware,state_tc-9@acord
state_tc,10,ACORD,District of Columbia,state_tc-10@acord
state_tc,12,ACORD,Florida,state_tc-12@acord
state_tc,13,ACORD,Georgia,state_tc-13@acord
state_tc,14,ACORD,Guam,state_tc-14@acord
state_tc,15,ACORD,Hawaii,state_tc-15@acord
state_tc,16,ACORD,Idaho,state_tc-16@acord
state_tc,17,ACORD,Illinois,state_tc-17@acord
state_tc,18,ACORD,Indiana,state_tc-18@acord
state_tc,19,ACORD,Iowa,state_tc-19@acord
state_tc,20,ACORD,Kansas,state_tc-20@acord
state_tc,21,ACORD,Kentucky,state_tc-21@acord
state_tc,22,ACORD,Louisiana,state_tc-22@acord
state_tc,23,ACORD,Maine,state_tc-23@acord
state_tc,25,ACORD,Maryland,state_tc-25@acord
state_tc,26,ACORD,Massachusetts,state_tc-26@acord
state_tc,27,ACORD,Michigan,state_tc-27@acord
state_tc,28,ACORD,Minnesota,state_tc-28@acord
state_tc,29,ACORD,Mississippi,state_tc-29@acord
state_tc,30,ACORD,Missouri,state_tc-30@acord
state_tc,31,ACORD,Montana,state_tc-31@acord
state_tc,32,ACORD,Nebraska,state_tc-32@acord
state_tc,33,ACORD,Nevada,state_tc-33@acord
state_tc,34,ACORD,New Hampshire,state_tc-34@acord
state_tc,35,ACORD,New Jersey,state_tc-35@acord
state_tc,36,ACORD,New Mexico,state_tc-36@acord
state_tc,37,ACORD,New York,state_tc-37@acord
state_tc,38,ACORD,North Carolina,state_tc-38@acord
state_tc,39,ACORD,North Dakota,state_tc-39@acord
state_tc,40,ACORD,Northern Mariana Islands,state_tc-40@acord
state_tc,41,ACORD,Ohio,state_tc-41@acord
state_tc,42,ACORD,Oklahoma,state_tc-42@acord
state_tc,43,ACORD,Oregon,state_tc-43@acord
state_tc,45,ACORD,Pennsylvania,state_tc-45@acord
state_tc,46,ACORD,Puerto Rico,state_tc-46@acord
state_tc,47,ACORD,Rhode Island,state_tc-47@acord
state_tc,48,ACORD,South Carolina,state_tc-48@acord
state_tc,49,ACORD,South Dakota,state_tc-49@acord
state_tc,50,ACORD,Tennessee,state_tc-50@acord
state_tc,51,ACORD,Texas,state_tc-51@acord
state_tc,52,ACORD,Utah,state_tc-52@acord
state_tc,53,ACORD,Vermont,state_tc-53@acord
state_tc,54,ACORD,Virgin Islands,state_tc-54@acord
state_tc,55,ACORD,Virginia,state_tc-55@acord
state_tc,56,ACORD,Washington,state_tc-56@acord
state_tc,57,ACORD,West Virginia,state_tc-57@acord
state_tc,58,ACORD,Wisconsin,state_tc-58@acord
state_tc,59,ACORD,Wyoming,state_tc-59@acord
state_tc,60,ACORD,Armed Forces Americas (except Canada),state_tc-60@acord
state_tc,61,ACORD,"Armed Forces Canada, Africa, Europe, Middle East",state_tc-61@acord
state_tc,62,ACORD,US Armed Forces Pacific,state_tc-62@acord
state_tc,80,ACORD,Guantanamo Bay (US Naval Base) Cuba,state_tc-80@acord
state_tc,101,ACORD,Alberta,state_tc-101@acord
state_tc,102,ACORD,British Columbia,state_tc-102@acord
state_tc,103,ACORD,Manitoba,state_tc-103@acord
state_tc,104,ACORD,New Brunswick,state_tc-104@acord
state_tc,105,ACORD,Newfoundland and Labrador,state_tc-105@acord
state_tc,106,ACORD,Northwest Territories,state_tc-106@acord
state_tc,107,ACORD,Nova Scotia,state_tc-107@acord
state_tc,108,ACORD,Ontario,state_tc-108@acord
state_tc,109,ACORD,Prince Edward Island,state_tc-109@acord
state_tc,110,ACORD,Quebec,state_tc-110@acord
state_tc,111,ACORD,Saskatchewan,state_tc-111@acord
state_tc,112,ACORD,Yukon Territory,state_tc-112@acord
state_tc,113,ACORD,Nunavut,state_tc-113@acord
state_tc,2147483647,ACORD,Other,state_tc-2147483647@acord
StateProv,AKA NL Newfoundland and Labrador,iGO,NL,stateprov-aka nl newfoundland and labrador@igo
StateProv,Alabama,iGO,AL,stateprov-alabama@igo
StateProv,Alaska,iGO,AK,stateprov-alaska@igo
StateProv,Alberta,iGO,AB,stateprov-alberta@igo
StateProv,American Samoa,iGO,AS,stateprov-american samoa@igo
StateProv,Arizona,iGO,AZ,stateprov-arizona@igo
StateProv,Arkansas,iGO,AR,stateprov-arkansas@igo
StateProv,Armed Forces Americas (except Canada),iGO,AA,stateprov-armed forces americas (except canada)@igo
StateProv,Armed Forces Europe,iGO,AE,stateprov-armed forces europe@igo
StateProv,British Columbia,iGO,BC,stateprov-british columbia@igo
StateProv,California,iGO,CA,stateprov-california@igo
StateProv,Colorado,iGO,CO,stateprov-colorado@igo
StateProv,Connecticut,iGO,CT,stateprov-connecticut@igo
StateProv,Delaware,iGO,DE,stateprov-delaware@igo
StateProv,District of Columbia,iGO,DC,stateprov-district of columbia@igo
StateProv,Federated States of Micronesia,iGO,FM,stateprov-federated states of micronesia@igo
StateProv,Florida,iGO,FL,stateprov-florida@igo
StateProv,Georgia,iGO,GA,stateprov-georgia@igo
StateProv,Guam,iGO,GU,stateprov-guam@igo
StateProv,Hawaii,iGO,HI,stateprov-hawaii@igo
StateProv,Idaho,iGO,ID,stateprov-idaho@igo
StateProv,Illinois,iGO,IL,stateprov-illinois@igo
StateProv,Indiana,iGO,IN,stateprov-indiana@igo
StateProv,Iowa,iGO,IA,stateprov-iowa@igo
StateProv,Kansas,iGO,KS,stateprov-kansas@igo
StateProv,Kentucky,iGO,KY,stateprov-kentucky@igo
StateProv,Louisiana,iGO,LA,stateprov-louisiana@igo
StateProv,Maine,iGO,ME,stateprov-maine@igo
StateProv,Manitoba,iGO,MB,stateprov-manitoba@igo
StateProv,Marshall Islands,iGO,MH,stateprov-marshall islands@igo
StateProv,Maryland,iGO,MD,stateprov-maryland@igo
StateProv,Massachusetts,iGO,MA,stateprov-massachusetts@igo
StateProv,Michigan,iGO,MI,stateprov-michigan@igo
StateProv,Minnesota,iGO,MN,stateprov-minnesota@igo
StateProv,Mississippi,iGO,MS,stateprov-mississippi@igo
StateProv,Missouri,iGO,MO,stateprov-missouri@igo
StateProv,Montana,iGO,MT,stateprov-montana@igo
StateProv,Nebraska,iGO,NE,stateprov-nebraska@igo
StateProv,Nevada,iGO,NV,stateprov-nevada@igo
StateProv,New Brunswick,iGO,NB,stateprov-new brunswick@igo
StateProv,New Hampshire,iGO,NH,stateprov-new hampshire@igo
StateProv,New Jersey,iGO,NJ,stateprov-new jersey@igo
StateProv,New Mexico,iGO,NM,stateprov-new mexico@igo
StateProv,New York,iGO,NY,stateprov-new york@igo
StateProv,North Carolina,iGO,NC,stateprov-north carolina@igo
StateProv,North Dakota,iGO,ND,stateprov-north dakota@igo
StateProv,Northwest Territories,iGO,NT,stateprov-northwest territories@igo
StateProv,Nova Scotia,iGO,NS,stateprov-nova scotia@igo
StateProv,Nunavut,iGO,NU,stateprov-nunavut@igo
StateProv,Ohio,iGO,OH,stateprov-ohio@igo
StateProv,Oklahoma,iGO,OK,stateprov-oklahoma@igo
StateProv,Ontario,iGO,ON,stateprov-ontario@igo
StateProv,Oregon,iGO,OR,stateprov-oregon@igo
StateProv,Palau,iGO,PW,stateprov-palau@igo
StateProv,Pennsylvania,iGO,PA,stateprov-pennsylvania@igo
StateProv,Prince Edward Island,iGO,PE,stateprov-prince edward island@igo
StateProv,Puerto Rico,iGO,PR,stateprov-puerto rico@igo
StateProv,Quebec,iGO,QC,stateprov-quebec@igo
StateProv,Rhode Island,iGO,RI,stateprov-rhode island@igo
StateProv,Saskatchewan,iGO,SK,stateprov-saskatchewan@igo
StateProv,South Carolina,iGO,SC,stateprov-south carolina@igo
StateProv,South Dakota,iGO,SD,stateprov-south dakota@igo
StateProv,Tennessee,iGO,TN,stateprov-tennessee@igo
StateProv,Texas,iGO,TX,stateprov-texas@igo
StateProv,Utah,iGO,UT,stateprov-utah@igo
StateProv,Vermont,iGO,VT,stateprov-vermont@igo
StateProv,Virgin Islands,iGO,VI,stateprov-virgin islands@igo
StateProv,Virginia,iGO,VA,stateprov-virginia@igo
StateProv,Washington,iGO,WA,stateprov-washington@igo
StateProv,West Virginia,iGO,WV,stateprov-west virginia@igo
StateProv,Wisconsin,iGO,WI,stateprov-wisconsin@igo
StateProv,Wyoming,iGO,WY,stateprov-wyoming@igo
StateProv,Yukon Territory,iGO,YT,stateprov-yukon territory@igo
StateProv_to_ACORD,AB,iGO,101,stateprov_to_acord-ab@igo
StateProv_to_ACORD,AK,iGO,2,stateprov_to_acord-ak@igo
StateProv_to_ACORD,AL,iGO,1,stateprov_to_acord-al@igo
StateProv_to_ACORD,Alabama,iGO,1,stateprov_to_acord-alabama@igo
StateProv_to_ACORD,Alaska,iGO,2,stateprov_to_acord-alaska@igo
StateProv_to_ACORD,Alberta,iGO,101,stateprov_to_acord-alberta@igo
StateProv_to_ACORD,American Samoa,iGO,3,stateprov_to_acord-american samoa@igo
StateProv_to_ACORD,AR,iGO,5,stateprov_to_acord-ar@igo
StateProv_to_ACORD,Arizona,iGO,4,stateprov_to_acord-arizona@igo
StateProv_to_ACORD,Arkansas,iGO,5,stateprov_to_acord-arkansas@igo
StateProv_to_ACORD,Armed Forces Americas (except Canada),iGO,60,stateprov_to_acord-armed forces americas (except canada)@igo
StateProv_to_ACORD,"Armed Forces Canada, Africa, Europe, Middle East",iGO,61,"stateprov_to_acord-armed forces canada, africa, europe, middle east@igo"
StateProv_to_ACORD,AS,iGO,3,stateprov_to_acord-as@igo
StateProv_to_ACORD,AZ,iGO,4,stateprov_to_acord-az@igo
StateProv_to_ACORD,BC,iGO,102,stateprov_to_acord-bc@igo
StateProv_to_ACORD,British Columbia,iGO,102,stateprov_to_acord-british columbia@igo
StateProv_to_ACORD,CA,iGO,6,stateprov_to_acord-ca@igo
StateProv_to_ACORD,California,iGO,6,stateprov_to_acord-california@igo
StateProv_to_ACORD,CO,iGO,7,stateprov_to_acord-co@igo
StateProv_to_ACORD,Colorado,iGO,7,stateprov_to_acord-colorado@igo
StateProv_to_ACORD,Connecticut,iGO,8,stateprov_to_acord-connecticut@igo
StateProv_to_ACORD,CT,iGO,8,stateprov_to_acord-ct@igo
StateProv_to_ACORD,DC,iGO,10,stateprov_to_acord-dc@igo
StateProv_to_ACORD,DE,iGO,9,stateprov_to_acord-de@igo
StateProv_to_ACORD,Delaware,iGO,9,stateprov_to_acord-delaware@igo
StateProv_to_ACORD,District of Columbia,iGO,10,stateprov_to_acord-district of columbia@igo
StateProv_to_ACORD,FL,iGO,12,stateprov_to_acord-fl@igo
StateProv_to_ACORD,Florida,iGO,12,stateprov_to_acord-florida@igo
StateProv_to_ACORD,GA,iGO,13,stateprov_to_acord-ga@igo
StateProv_to_ACORD,Georgia,iGO,13,stateprov_to_acord-georgia@igo
StateProv_to_ACORD,GU,iGO,14,stateprov_to_acord-gu@igo
StateProv_to_ACORD,Guam,iGO,14,stateprov_to_acord-guam@igo
StateProv_to_ACORD,Guantanamo Bay (US Naval Base) Cuba,iGO,80,stateprov_to_acord-guantanamo bay (us naval base) cuba@igo
StateProv_to_ACORD,Hawaii,iGO,15,stateprov_to_acord-hawaii@igo
StateProv_to_ACORD,HI,iGO,15,stateprov_to_acord-hi@igo
StateProv_to_ACORD,IA,iGO,19,stateprov_to_acord-ia@igo
StateProv_to_ACORD,ID,iGO,16,stateprov_to_acord-id@igo
StateProv_to_ACORD,Idaho,iGO,16,stateprov_to_acord-idaho@igo
StateProv_to_ACORD,IL,iGO,17,stateprov_to_acord-il@igo
StateProv_to_ACORD,Illinois,iGO,17,stateprov_to_acord-illinois@igo
StateProv_to_ACORD,IN,iGO,18,stateprov_to_acord-in@igo
StateProv_to_ACORD,Indiana,iGO,18,stateprov_to_acord-indiana@igo
StateProv_to_ACORD,Iowa,iGO,19,stateprov_to_acord-iowa@igo
StateProv_to_ACORD,Kansas,iGO,20,stateprov_to_acord-kansas@igo
StateProv_to_ACORD,Kentucky,iGO,21,stateprov_to_acord-kentucky@igo
StateProv_to_ACORD,KS,iGO,20,stateprov_to_acord-ks@igo
StateProv_to_ACORD,KY,iGO,21,stateprov_to_acord-ky@igo
StateProv_to_ACORD,LA,iGO,22,stateprov_to_acord-la@igo
StateProv_to_ACORD,Louisiana,iGO,22,stateprov_to_acord-louisiana@igo
StateProv_to_ACORD,MA,iGO,26,stateprov_to_acord-ma@igo
StateProv_to_ACORD,Maine,iGO,23,stateprov_to_acord-maine@igo
StateProv_to_ACORD,Manitoba,iGO,103,stateprov_to_acord-manitoba@igo
StateProv_to_ACORD,Maryland,iGO,25,stateprov_to_acord-maryland@igo
StateProv_to_ACORD,Massachusetts,iGO,26,stateprov_to_acord-massachusetts@igo
StateProv_to_ACORD,MB,iGO,103,stateprov_to_acord-mb@igo
StateProv_to_ACORD,MD,iGO,25,stateprov_to_acord-md@igo
StateProv_to_ACORD,ME,iGO,23,stateprov_to_acord-me@igo
StateProv_to_ACORD,MI,iGO,27,stateprov_to_acord-mi@igo
StateProv_to_ACORD,Michigan,iGO,27,stateprov_to_acord-michigan@igo
StateProv_to_ACORD,Minnesota,iGO,28,stateprov_to_acord-minnesota@igo
StateProv_to_ACORD,Mississippi,iGO,29,stateprov_to_acord-mississippi@igo
StateProv_to_ACORD,Missouri,iGO,30,stateprov_to_acord-missouri@igo
StateProv_to_ACORD,MN,iGO,28,stateprov_to_acord-mn@igo
StateProv_to_ACORD,MO,iGO,30,stateprov_to_acord-mo@igo
StateProv_to_ACORD,Montana,iGO,31,stateprov_to_acord-montana@igo
StateProv_to_ACORD,MP,iGO,40,stateprov_to_acord-mp@igo
StateProv_to_ACORD,MS,iGO,29,stateprov_to_acord-ms@igo
StateProv_to_ACORD,MT,iGO,31,stateprov_to_acord-mt@igo
StateProv_to_ACORD,NB,iGO,104,stateprov_to_acord-nb@igo
StateProv_to_ACORD,NC,iGO,38,stateprov_to_acord-nc@igo
StateProv_to_ACORD,ND,iGO,39,stateprov_to_acord-nd@igo
StateProv_to_ACORD,NE,iGO,32,stateprov_to_acord-ne@igo
StateProv_to_ACORD,Nebraska,iGO,32,stateprov_to_acord-nebraska@igo
StateProv_to_ACORD,Nevada,iGO,33,stateprov_to_acord-nevada@igo
StateProv_to_ACORD,New Brunswick,iGO,104,stateprov_to_acord-new brunswick@igo
StateProv_to_ACORD,New Hampshire,iGO,34,stateprov_to_acord-new hampshire@igo
StateProv_to_ACORD,New Jersey,iGO,35,stateprov_to_acord-new jersey@igo
StateProv_to_ACORD,New Mexico,iGO,36,stateprov_to_acord-new mexico@igo
StateProv_to_ACORD,New York,iGO,37,stateprov_to_acord-new york@igo
StateProv_to_ACORD,Newfoundland and Labrador,iGO,105,stateprov_to_acord-newfoundland and labrador@igo
StateProv_to_ACORD,NH,iGO,34,stateprov_to_acord-nh@igo
StateProv_to_ACORD,NJ,iGO,35,stateprov_to_acord-nj@igo
StateProv_to_ACORD,NL,iGO,105,stateprov_to_acord-nl@igo
StateProv_to_ACORD,NM,iGO,36,stateprov_to_acord-nm@igo
StateProv_to_ACORD,North Carolina,iGO,38,stateprov_to_acord-north carolina@igo
StateProv_to_ACORD,North Dakota,iGO,39,stateprov_to_acord-north dakota@igo
StateProv_to_ACORD,Northern Mariana Islands,iGO,40,stateprov_to_acord-northern mariana islands@igo
StateProv_to_ACORD,Northwest Territories,iGO,106,stateprov_to_acord-northwest territories@igo
StateProv_to_ACORD,Nova Scotia,iGO,107,stateprov_to_acord-nova scotia@igo
StateProv_to_ACORD,NS,iGO,107,stateprov_to_acord-ns@igo
StateProv_to_ACORD,NT,iGO,106,stateprov_to_acord-nt@igo
StateProv_to_ACORD,NU,iGO,113,stateprov_to_acord-nu@igo
StateProv_to_ACORD,Nunavut,iGO,113,stateprov_to_acord-nunavut@igo
StateProv_to_ACORD,NV,iGO,33,stateprov_to_acord-nv@igo
StateProv_to_ACORD,NY,iGO,37,stateprov_to_acord-ny@igo
StateProv_to_ACORD,OH,iGO,41,stateprov_to_acord-oh@igo
StateProv_to_ACORD,Ohio,iGO,41,stateprov_to_acord-ohio@igo
StateProv_to_ACORD,OK,iGO,42,stateprov_to_acord-ok@igo
StateProv_to_ACORD,Oklahoma,iGO,42,stateprov_to_acord-oklahoma@igo
StateProv_to_ACORD,ON,iGO,108,stateprov_to_acord-on@igo
StateProv_to_ACORD,Ontario,iGO,108,stateprov_to_acord-ontario@igo
StateProv_to_ACORD,OR,iGO,43,stateprov_to_acord-or@igo
StateProv_to_ACORD,Oregon,iGO,43,stateprov_to_acord-oregon@igo
StateProv_to_ACORD,PA,iGO,45,stateprov_to_acord-pa@igo
StateProv_to_ACORD,PE,iGO,109,stateprov_to_acord-pe@igo
StateProv_to_ACORD,Pennsylvania,iGO,45,stateprov_to_acord-pennsylvania@igo
StateProv_to_ACORD,PR,iGO,46,stateprov_to_acord-pr@igo
StateProv_to_ACORD,Prince Edward Island,iGO,109,stateprov_to_acord-prince edward island@igo
StateProv_to_ACORD,Puerto Rico,iGO,46,stateprov_to_acord-puerto rico@igo
StateProv_to_ACORD,QC,iGO,110,stateprov_to_acord-qc@igo
StateProv_to_ACORD,Quebec,iGO,110,stateprov_to_acord-quebec@igo
StateProv_to_ACORD,Rhode Island,iGO,47,stateprov_to_acord-rhode island@igo
StateProv_to_ACORD,RI,iGO,47,stateprov_to_acord-ri@igo
StateProv_to_ACORD,Saskatchewan,iGO,111,stateprov_to_acord-saskatchewan@igo
StateProv_to_ACORD,SC,iGO,48,stateprov_to_acord-sc@igo
StateProv_to_ACORD,SD,iGO,49,stateprov_to_acord-sd@igo
StateProv_to_ACORD,SK,iGO,111,stateprov_to_acord-sk@igo
StateProv_to_ACORD,South Carolina,iGO,48,stateprov_to_acord-south carolina@igo
StateProv_to_ACORD,South Dakota,iGO,49,stateprov_to_acord-south dakota@igo
StateProv_to_ACORD,Tennessee,iGO,50,stateprov_to_acord-tennessee@igo
StateProv_to_ACORD,Texas,iGO,51,stateprov_to_acord-texas@igo
StateProv_to_ACORD,TN,iGO,50,stateprov_to_acord-tn@igo
StateProv_to_ACORD,TX,iGO,51,stateprov_to_acord-tx@igo
StateProv_to_ACORD,US Armed Forces Pacific,iGO,62,stateprov_to_acord-us armed forces pacific@igo
StateProv_to_ACORD,UT,iGO,52,stateprov_to_acord-ut@igo
StateProv_to_ACORD,Utah,iGO,52,stateprov_to_acord-utah@igo
StateProv_to_ACORD,VA,iGO,55,stateprov_to_acord-va@igo
StateProv_to_ACORD,Vermont,iGO,53,stateprov_to_acord-vermont@igo
StateProv_to_ACORD,VI,iGO,54,stateprov_to_acord-vi@igo
StateProv_to_ACORD,Virgin Islands,iGO,54,stateprov_to_acord-virgin islands@igo
StateProv_to_ACORD,Virginia,iGO,55,stateprov_to_acord-virginia@igo
StateProv_to_ACORD,VT,iGO,53,stateprov_to_acord-vt@igo
StateProv_to_ACORD,WA,iGO,56,stateprov_to_acord-wa@igo
StateProv_to_ACORD,Washington,iGO,56,stateprov_to_acord-washington@igo
StateProv_to_ACORD,West Virginia,iGO,57,stateprov_to_acord-west virginia@igo
StateProv_to_ACORD,WI,iGO,58,stateprov_to_acord-wi@igo
StateProv_to_ACORD,Wisconsin,iGO,58,stateprov_to_acord-wisconsin@igo
StateProv_to_ACORD,WV,iGO,57,stateprov_to_acord-wv@igo
StateProv_to_ACORD,WY,iGO,59,stateprov_to_acord-wy@igo
StateProv_to_ACORD,Wyoming,iGO,59,stateprov_to_acord-wyoming@igo
StateProv_to_ACORD,YT,iGO,112,stateprov_to_acord-yt@igo
StateProv_to_ACORD,Yukon Territory,iGO,112,stateprov_to_acord-yukon territory@igo
tobprembasis_tc,0,ACORD,Unknown,tobprembasis_tc-0@acord
tobprembasis_tc,1,ACORD,Non Smoker,tobprembasis_tc-1@acord
tobprembasis_tc,2,ACORD,Smoker,tobprembasis_tc-2@acord
tobprembasis_tc,3,ACORD,Nicotine Non-Tobacco,tobprembasis_tc-3@acord
tobprembasis_tc,4,ACORD,Tobacco Lower Risk,tobprembasis_tc-4@acord
tobprembasis_tc,5,ACORD,Blended,tobprembasis_tc-5@acord
tobprembasis_tc,2147483647,ACORD,Other,tobprembasis_tc-2147483647@acord
unwriteclass_tc,0,ACORD,Unknown,unwriteclass_tc-0@acord
unwriteclass_tc,1,ACORD,Standard Risk,unwriteclass_tc-1@acord
unwriteclass_tc,2,ACORD,Preferred risk,unwriteclass_tc-2@acord
unwriteclass_tc,3,ACORD,Rated/Substandard Risk,unwriteclass_tc-3@acord
unwriteclass_tc,4,ACORD,Aerobic (super Preferred),unwriteclass_tc-4@acord
unwriteclass_tc,6,ACORD,Standard Plus,unwriteclass_tc-6@acord
unwriteclass_tc,7,ACORD,Uninsurable,unwriteclass_tc-7@acord
unwriteclass_tc,19,ACORD,Preferred Plus,unwriteclass_tc-19@acord
unwriteclass_tc,2147483647,ACORD,Other,unwriteclass_tc-2147483647@acord
vector_tc,0,ACORD,Unknown,vector_tc-0@acord
vector_tc,1,ACORD,Base Premium (Annualized),vector_tc-1@acord
vector_tc,2,ACORD,Substandard Base Premium (annualized),vector_tc-2@acord
vector_tc,3,ACORD,Rider Premium (Annualized),vector_tc-3@acord
vector_tc,4,ACORD,Scheduled Payment,vector_tc-4@acord
vector_tc,5,ACORD,Scheduled Modal Premium,vector_tc-5@acord
vector_tc,6,ACORD,Lump Sum,vector_tc-6@acord
vector_tc,7,ACORD,1035 Amount,vector_tc-7@acord
vector_tc,8,ACORD,Target annualized Premium,vector_tc-8@acord
vector_tc,9,ACORD,Minimum annualized premium,vector_tc-9@acord
vector_tc,10,ACORD,Gross Payment,vector_tc-10@acord
vector_tc,11,ACORD,Net Payment,vector_tc-11@acord
vector_tc,12,ACORD,Premium Load,vector_tc-12@acord
vector_tc,21,ACORD,Withdrawal,vector_tc-21@acord
vector_tc,22,ACORD,Surrender to reduce premium,vector_tc-22@acord
vector_tc,23,ACORD,Total Withdrawal,vector_tc-23@acord
vector_tc,24,ACORD,Maximum Withdrawal,vector_tc-24@acord
vector_tc,25,ACORD,Force Out,vector_tc-25@acord
vector_tc,26,ACORD,Withdrawal Charge,vector_tc-26@acord
vector_tc,31,ACORD,Loan in cash,vector_tc-31@acord
vector_tc,32,ACORD,Loan to reduce premium,vector_tc-32@acord
vector_tc,33,ACORD,Loan interest paid out of pocket,vector_tc-33@acord
vector_tc,34,ACORD,Loan interest capitalized,vector_tc-34@acord
vector_tc,35,ACORD,Total loan interest due,vector_tc-35@acord
vector_tc,36,ACORD,Total loan,vector_tc-36@acord
vector_tc,37,ACORD,Loan balance end of year,vector_tc-37@acord
vector_tc,38,ACORD,Loan repayment,vector_tc-38@acord
vector_tc,39,ACORD,Maximum loan,vector_tc-39@acord
vector_tc,42,ACORD,Total First Year Premium,vector_tc-42@acord
vector_tc,43,ACORD,Total Accumulated Premiums,vector_tc-43@acord
vector_tc,51,ACORD,Net distribution,vector_tc-51@acord
vector_tc,52,ACORD,Cash distribution,vector_tc-52@acord
vector_tc,53,ACORD,Net Loan Charge,vector_tc-53@acord
vector_tc,54,ACORD,Max Preferred Loan,vector_tc-54@acord
vector_tc,61,ACORD,Before tax outlay,vector_tc-61@acord
vector_tc,62,ACORD,Total taxable amount,vector_tc-62@acord
vector_tc,63,ACORD,Tax due,vector_tc-63@acord
vector_tc,64,ACORD,After tax outlay,vector_tc-64@acord
vector_tc,71,ACORD,Death Benefit,vector_tc-71@acord
vector_tc,72,ACORD,Taxable death benefit,vector_tc-72@acord
vector_tc,73,ACORD,Tax on death benefit,vector_tc-73@acord
vector_tc,74,ACORD,After tax death benefit,vector_tc-74@acord
vector_tc,75,ACORD,Gross death benefit,vector_tc-75@acord
vector_tc,76,ACORD,Net Death Benefit,vector_tc-76@acord
vector_tc,81,ACORD,Gross account value,vector_tc-81@acord
vector_tc,82,ACORD,Net account value,vector_tc-82@acord
vector_tc,83,ACORD,Cash (surrender) value,vector_tc-83@acord
vector_tc,84,ACORD,Taxable portion if surrender,vector_tc-84@acord
vector_tc,85,ACORD,Tax due if surrendered,vector_tc-85@acord
vector_tc,86,ACORD,After tax net cash surrender value,vector_tc-86@acord
vector_tc,87,ACORD,Economic Benefit Value,vector_tc-87@acord
vector_tc,88,ACORD,Tax Reserve Value,vector_tc-88@acord
vector_tc,89,ACORD,Dividends to premium deposit fund,vector_tc-89@acord
vector_tc,90,ACORD,Cash value of Paid Up Additions,vector_tc-90@acord
vector_tc,91,ACORD,Paid Premiums,vector_tc-91@acord
vector_tc,101,ACORD,Policy year,vector_tc-101@acord
vector_tc,102,ACORD,Attained policy age,vector_tc-102@acord
vector_tc,103,ACORD,Death benefit option ? tc of V tag,vector_tc-103@acord
vector_tc,104,ACORD,Total base face amount,vector_tc-104@acord
vector_tc,105,ACORD,Cost basis,vector_tc-105@acord
vector_tc,106,ACORD,Surrender charge,vector_tc-106@acord
vector_tc,107,ACORD,Net interest rate,vector_tc-107@acord
vector_tc,108,ACORD,Gross interest rate,vector_tc-108@acord
vector_tc,109,ACORD,Gross interest amount,vector_tc-109@acord
vector_tc,110,ACORD,Interest earned on impaired funds,vector_tc-110@acord
vector_tc,111,ACORD,Interest earned on non-impaired funds,vector_tc-111@acord
vector_tc,112,ACORD,Gross commission amount,vector_tc-112@acord
vector_tc,113,ACORD,Negative Cash Value Age,vector_tc-113@acord
vector_tc,114,ACORD,Negative Cash Value Duration,vector_tc-114@acord
vector_tc,121,ACORD,Mortality and expense charge,vector_tc-121@acord
vector_tc,122,ACORD,Expense Deduction,vector_tc-122@acord
vector_tc,123,ACORD,COI Deduction,vector_tc-123@acord
vector_tc,124,ACORD,Rider Deduction,vector_tc-124@acord
vector_tc,125,ACORD,Fund portfolio charge,vector_tc-125@acord
vector_tc,126,ACORD,Asset based charge,vector_tc-126@acord
vector_tc,127,ACORD,Loan charge rate,vector_tc-127@acord
vector_tc,128,ACORD,Bonus Amount,vector_tc-128@acord
vector_tc,129,ACORD,Reduced paid up amount,vector_tc-129@acord
vector_tc,130,ACORD,Extended term insurance years,vector_tc-130@acord
vector_tc,131,ACORD,Extended term insurance months,vector_tc-131@acord
vector_tc,132,ACORD,Annuitization value,vector_tc-132@acord
vector_tc,133,ACORD,Net Amount at Risk,vector_tc-133@acord
vector_tc,134,ACORD,Reduced annuitization,vector_tc-134@acord
vector_tc,141,ACORD,Annual dividends,vector_tc-141@acord
vector_tc,142,ACORD,Dividends to purchase paid up additions,vector_tc-142@acord
vector_tc,143,ACORD,Dividends paid in cash,vector_tc-143@acord
vector_tc,144,ACORD,Dividends to reduce payment,vector_tc-144@acord
vector_tc,145,ACORD,Dividends applied to term dividend,vector_tc-145@acord
vector_tc,146,ACORD,Dividends to accumulation,vector_tc-146@acord
vector_tc,147,ACORD,Dividends to reduce loans,vector_tc-147@acord
vector_tc,148,ACORD,Dividends reinvested into contract,vector_tc-148@acord
vector_tc,149,ACORD,Death Benefit Paid Up additions,vector_tc-149@acord
vector_tc,150,ACORD,Base policy dividends,vector_tc-150@acord
vector_tc,151,ACORD,Terminal dividends,vector_tc-151@acord
vector_tc,152,ACORD,Dividend Option,vector_tc-152@acord
vector_tc,153,ACORD,OYT Option,vector_tc-153@acord
vector_tc,154,ACORD,Primary Insured's attained age,vector_tc-154@acord
vector_tc,155,ACORD,Joint Insured attained age,vector_tc-155@acord
vector_tc,301,ACORD,Scheduled Modal Payout,vector_tc-301@acord
vector_tc,302,ACORD,Equivalent Level Payout,vector_tc-302@acord
vector_tc,303,ACORD,Rate of Return on Before Tax Surrender Value,vector_tc-303@acord
vector_tc,304,ACORD,Rate of Return on Before Tax Death Benefit,vector_tc-304@acord
vector_tc,305,ACORD,Rate of Return on After Tax Surrender Value,vector_tc-305@acord
vector_tc,306,ACORD,Rate of Return on After Tax Death Benefit,vector_tc-306@acord
vector_tc,307,ACORD,Lump sum payout,vector_tc-307@acord
vector_tc,1001,ACORD,Guideline single premium,vector_tc-1001@acord
vector_tc,1002,ACORD,Guideline level premium,vector_tc-1002@acord
vector_tc,1003,ACORD,Seven pay premium,vector_tc-1003@acord
vector_tc,1004,ACORD,Cumulative Guideline Limit,vector_tc-1004@acord
vector_tc,1005,ACORD,TAMRA 7-PAY premium,vector_tc-1005@acord
vector_tc,2147483647,ACORD,Other,vector_tc-2147483647@acord
state_abbr_tc,1,ACORD,AL,state_abbr_tc-1@acord
state_abbr_tc,2,ACORD,AK,state_abbr_tc-2@acord
state_abbr_tc,3,ACORD,AS,state_abbr_tc-3@acord
state_abbr_tc,4,ACORD,AZ,state_abbr_tc-4@acord
state_abbr_tc,5,ACORD,AR,state_abbr_tc-5@acord
state_abbr_tc,6,ACORD,CA,state_abbr_tc-6@acord
state_abbr_tc,7,ACORD,CO,state_abbr_tc-7@acord
state_abbr_tc,8,ACORD,CT,state_abbr_tc-8@acord
state_abbr_tc,9,ACORD,DE,state_abbr_tc-9@acord
state_abbr_tc,10,ACORD,DC,state_abbr_tc-10@acord
state_abbr_tc,12,ACORD,FL,state_abbr_tc-12@acord
state_abbr_tc,13,ACORD,GA,state_abbr_tc-13@acord
state_abbr_tc,14,ACORD,GU,state_abbr_tc-14@acord
state_abbr_tc,15,ACORD,HI,state_abbr_tc-15@acord
state_abbr_tc,16,ACORD,ID,state_abbr_tc-16@acord
state_abbr_tc,17,ACORD,IL,state_abbr_tc-17@acord
state_abbr_tc,18,ACORD,IN,state_abbr_tc-18@acord
state_abbr_tc,19,ACORD,IA,state_abbr_tc-19@acord
state_abbr_tc,20,ACORD,KS,state_abbr_tc-20@acord
state_abbr_tc,21,ACORD,KY,state_abbr_tc-21@acord
state_abbr_tc,22,ACORD,LA,state_abbr_tc-22@acord
state_abbr_tc,23,ACORD,ME,state_abbr_tc-23@acord
state_abbr_tc,25,ACORD,MD,state_abbr_tc-25@acord
state_abbr_tc,26,ACORD,MA,state_abbr_tc-26@acord
state_abbr_tc,27,ACORD,MI,state_abbr_tc-27@acord
state_abbr_tc,28,ACORD,MN,state_abbr_tc-28@acord
state_abbr_tc,29,ACORD,MS,state_abbr_tc-29@acord
state_abbr_tc,30,ACORD,MO,state_abbr_tc-30@acord
state_abbr_tc,31,ACORD,MT,state_abbr_tc-31@acord
state_abbr_tc,32,ACORD,NE,state_abbr_tc-32@acord
state_abbr_tc,33,ACORD,NV,state_abbr_tc-33@acord
state_abbr_tc,34,ACORD,NH,state_abbr_tc-34@acord
state_abbr_tc,35,ACORD,NJ,state_abbr_tc-35@acord
state_abbr_tc,36,ACORD,NM,state_abbr_tc-36@acord
state_abbr_tc,37,ACORD,NY,state_abbr_tc-37@acord
state_abbr_tc,38,ACORD,NC,state_abbr_tc-38@acord
state_abbr_tc,39,ACORD,ND,state_abbr_tc-39@acord
state_abbr_tc,40,ACORD,MP,state_abbr_tc-40@acord
state_abbr_tc,41,ACORD,OH,state_abbr_tc-41@acord
state_abbr_tc,42,ACORD,OK,state_abbr_tc-42@acord
state_abbr_tc,43,ACORD,OR,state_abbr_tc-43@acord
state_abbr_tc,45,ACORD,PA,state_abbr_tc-45@acord
state_abbr_tc,46,ACORD,PR,state_abbr_tc-46@acord
state_abbr_tc,47,ACORD,RI,state_abbr_tc-47@acord
state_abbr_tc,48,ACORD,SC,state_abbr_tc-48@acord
state_abbr_tc,49,ACORD,SD,state_abbr_tc-49@acord
state_abbr_tc,50,ACORD,TN,state_abbr_tc-50@acord
state_abbr_tc,51,ACORD,TX,state_abbr_tc-51@acord
state_abbr_tc,52,ACORD,UT,state_abbr_tc-52@acord
state_abbr_tc,53,ACORD,VT,state_abbr_tc-53@acord
state_abbr_tc,54,ACORD,VI,state_abbr_tc-54@acord
state_abbr_tc,55,ACORD,VA,state_abbr_tc-55@acord
state_abbr_tc,56,ACORD,WA,state_abbr_tc-56@acord
state_abbr_tc,57,ACORD,WV,state_abbr_tc-57@acord
state_abbr_tc,58,ACORD,WI,state_abbr_tc-58@acord
state_abbr_tc,59,ACORD,WY,state_abbr_tc-59@acord
state_abbr_tc,101,ACORD,AB,state_abbr_tc-101@acord
state_abbr_tc,102,ACORD,BC,state_abbr_tc-102@acord
state_abbr_tc,103,ACORD,MB,state_abbr_tc-103@acord
state_abbr_tc,104,ACORD,NB,state_abbr_tc-104@acord
state_abbr_tc,105,ACORD,NL,state_abbr_tc-105@acord
state_abbr_tc,106,ACORD,NT,state_abbr_tc-106@acord
state_abbr_tc,107,ACORD,NS,state_abbr_tc-107@acord
state_abbr_tc,108,ACORD,ON,state_abbr_tc-108@acord
state_abbr_tc,109,ACORD,PE,state_abbr_tc-109@acord
state_abbr_tc,110,ACORD,QC,state_abbr_tc-110@acord
state_abbr_tc,111,ACORD,SK,state_abbr_tc-111@acord
state_abbr_tc,112,ACORD,YT,state_abbr_tc-112@acord
state_abbr_tc,113,ACORD,NU,state_abbr_tc-113@acord
nation_abbr_tc,0,ACORD,Unknown,nation_abbr_tc-0@acord
nation_abbr_tc,1,ACORD,USA,nation_abbr_tc-1@acord
nation_abbr_tc,2,ACORD,Canada,nation_abbr_tc-2@acord
nation_abbr_tc,7,ACORD,Russia,nation_abbr_tc-7@acord
nation_abbr_tc,20,ACORD,Egypt,nation_abbr_tc-20@acord
nation_abbr_tc,27,ACORD,South Africa,nation_abbr_tc-27@acord
nation_abbr_tc,30,ACORD,Greece,nation_abbr_tc-30@acord
nation_abbr_tc,31,ACORD,Netherlands,nation_abbr_tc-31@acord
nation_abbr_tc,32,ACORD,Belgium,nation_abbr_tc-32@acord
nation_abbr_tc,33,ACORD,France,nation_abbr_tc-33@acord
nation_abbr_tc,34,ACORD,Spain,nation_abbr_tc-34@acord
nation_abbr_tc,36,ACORD,Hungary,nation_abbr_tc-36@acord
nation_abbr_tc,38,ACORD,Yugoslavia,nation_abbr_tc-38@acord
nation_abbr_tc,39,ACORD,Italy,nation_abbr_tc-39@acord
nation_abbr_tc,40,ACORD,Romania,nation_abbr_tc-40@acord
nation_abbr_tc,41,ACORD,Switzerland,nation_abbr_tc-41@acord
nation_abbr_tc,43,ACORD,Austria,nation_abbr_tc-43@acord
nation_abbr_tc,44,ACORD,UK,nation_abbr_tc-44@acord
nation_abbr_tc,45,ACORD,Denmark,nation_abbr_tc-45@acord
nation_abbr_tc,46,ACORD,Sweden,nation_abbr_tc-46@acord
nation_abbr_tc,47,ACORD,Norway,nation_abbr_tc-47@acord
nation_abbr_tc,48,ACORD,Poland,nation_abbr_tc-48@acord
nation_abbr_tc,49,ACORD,Germany,nation_abbr_tc-49@acord
nation_abbr_tc,51,ACORD,Peru,nation_abbr_tc-51@acord
nation_abbr_tc,52,ACORD,Mexico,nation_abbr_tc-52@acord
nation_abbr_tc,53,ACORD,Cuba,nation_abbr_tc-53@acord
nation_abbr_tc,54,ACORD,Argentina,nation_abbr_tc-54@acord
nation_abbr_tc,55,ACORD,Brazil,nation_abbr_tc-55@acord
nation_abbr_tc,56,ACORD,Chile,nation_abbr_tc-56@acord
nation_abbr_tc,57,ACORD,Colombia,nation_abbr_tc-57@acord
nation_abbr_tc,58,ACORD,Venezuela,nation_abbr_tc-58@acord
nation_abbr_tc,60,ACORD,Malaysia,nation_abbr_tc-60@acord
nation_abbr_tc,61,ACORD,Australia,nation_abbr_tc-61@acord
nation_abbr_tc,62,ACORD,Indonesia,nation_abbr_tc-62@acord
nation_abbr_tc,63,ACORD,Philippines,nation_abbr_tc-63@acord
nation_abbr_tc,64,ACORD,NZ,nation_abbr_tc-64@acord
nation_abbr_tc,65,ACORD,Singapore,nation_abbr_tc-65@acord
nation_abbr_tc,66,ACORD,Thailand,nation_abbr_tc-66@acord
nation_abbr_tc,81,ACORD,Japan,nation_abbr_tc-81@acord
nation_abbr_tc,84,ACORD,Viet Nam,nation_abbr_tc-84@acord
nation_abbr_tc,86,ACORD,China,nation_abbr_tc-86@acord
nation_abbr_tc,90,ACORD,Turkey,nation_abbr_tc-90@acord
nation_abbr_tc,91,ACORD,India,nation_abbr_tc-91@acord
nation_abbr_tc,92,ACORD,Pakistan,nation_abbr_tc-92@acord
nation_abbr_tc,93,ACORD,Afghanistan,nation_abbr_tc-93@acord
nation_abbr_tc,94,ACORD,Sri Lanka,nation_abbr_tc-94@acord
nation_abbr_tc,98,ACORD,Iran,nation_abbr_tc-98@acord
nation_abbr_tc,212,ACORD,Morocco,nation_abbr_tc-212@acord
nation_abbr_tc,213,ACORD,Algeria,nation_abbr_tc-213@acord
nation_abbr_tc,216,ACORD,Tunisia,nation_abbr_tc-216@acord
nation_abbr_tc,218,ACORD,Libya,nation_abbr_tc-218@acord
nation_abbr_tc,220,ACORD,Gambia,nation_abbr_tc-220@acord
nation_abbr_tc,221,ACORD,Senegal,nation_abbr_tc-221@acord
nation_abbr_tc,222,ACORD,Mauritania,nation_abbr_tc-222@acord
nation_abbr_tc,223,ACORD,Mali,nation_abbr_tc-223@acord
nation_abbr_tc,224,ACORD,Guinea,nation_abbr_tc-224@acord
nation_abbr_tc,226,ACORD,Burkina Faso,nation_abbr_tc-226@acord
nation_abbr_tc,227,ACORD,Niger,nation_abbr_tc-227@acord
nation_abbr_tc,228,ACORD,Togo,nation_abbr_tc-228@acord
nation_abbr_tc,229,ACORD,Benin,nation_abbr_tc-229@acord
nation_abbr_tc,230,ACORD,Mauritius,nation_abbr_tc-230@acord
nation_abbr_tc,231,ACORD,Liberia,nation_abbr_tc-231@acord
nation_abbr_tc,232,ACORD,Sierra Leone,nation_abbr_tc-232@acord
nation_abbr_tc,233,ACORD,Ghana,nation_abbr_tc-233@acord
nation_abbr_tc,234,ACORD,Nigeria,nation_abbr_tc-234@acord
nation_abbr_tc,235,ACORD,Chad,nation_abbr_tc-235@acord
nation_abbr_tc,236,ACORD,Central African Republic,nation_abbr_tc-236@acord
nation_abbr_tc,237,ACORD,Cameroon,nation_abbr_tc-237@acord
nation_abbr_tc,238,ACORD,Cape Verde,nation_abbr_tc-238@acord
nation_abbr_tc,239,ACORD,Sao Tome and Principe,nation_abbr_tc-239@acord
nation_abbr_tc,240,ACORD,Equatorial Guinea,nation_abbr_tc-240@acord
nation_abbr_tc,241,ACORD,Gabon,nation_abbr_tc-241@acord
nation_abbr_tc,242,ACORD,Bahamas,nation_abbr_tc-242@acord
nation_abbr_tc,244,ACORD,Angola,nation_abbr_tc-244@acord
nation_abbr_tc,246,ACORD,Barbados,nation_abbr_tc-246@acord
nation_abbr_tc,248,ACORD,Aland Islands,nation_abbr_tc-248@acord
nation_abbr_tc,249,ACORD,Sudan,nation_abbr_tc-249@acord
nation_abbr_tc,250,ACORD,Rwanda,nation_abbr_tc-250@acord
nation_abbr_tc,251,ACORD,Ethiopia,nation_abbr_tc-251@acord
nation_abbr_tc,252,ACORD,Somalia,nation_abbr_tc-252@acord
nation_abbr_tc,253,ACORD,Djibouti,nation_abbr_tc-253@acord
nation_abbr_tc,254,ACORD,Kenya,nation_abbr_tc-254@acord
nation_abbr_tc,255,ACORD,Tanzania,nation_abbr_tc-255@acord
nation_abbr_tc,256,ACORD,Uganda,nation_abbr_tc-256@acord
nation_abbr_tc,257,ACORD,Burundi,nation_abbr_tc-257@acord
nation_abbr_tc,258,ACORD,Mozambique,nation_abbr_tc-258@acord
nation_abbr_tc,260,ACORD,Zambia,nation_abbr_tc-260@acord
nation_abbr_tc,261,ACORD,Madagascar,nation_abbr_tc-261@acord
nation_abbr_tc,262,ACORD,Reunion,nation_abbr_tc-262@acord
nation_abbr_tc,263,ACORD,Zimbabwe,nation_abbr_tc-263@acord
nation_abbr_tc,264,ACORD,Namibia,nation_abbr_tc-264@acord
nation_abbr_tc,265,ACORD,Malawi,nation_abbr_tc-265@acord
nation_abbr_tc,266,ACORD,Lesotho,nation_abbr_tc-266@acord
nation_abbr_tc,267,ACORD,Botswana,nation_abbr_tc-267@acord
nation_abbr_tc,268,ACORD,Antigua and Barbuda,nation_abbr_tc-268@acord
nation_abbr_tc,269,ACORD,Comoros,nation_abbr_tc-269@acord
nation_abbr_tc,270,ACORD,Guinea-Bissau,nation_abbr_tc-270@acord
nation_abbr_tc,271,ACORD,The Democratic Republic of the Congo,nation_abbr_tc-271@acord
nation_abbr_tc,284,ACORD,Virgin Islands,nation_abbr_tc-284@acord
nation_abbr_tc,290,ACORD,Saint Helena Ascension and Tristan da Cunha,nation_abbr_tc-290@acord
nation_abbr_tc,297,ACORD,Aruba,nation_abbr_tc-297@acord
nation_abbr_tc,298,ACORD,Faroe Islands,nation_abbr_tc-298@acord
nation_abbr_tc,299,ACORD,Greenland,nation_abbr_tc-299@acord
nation_abbr_tc,345,ACORD,Cayman Islands,nation_abbr_tc-345@acord
nation_abbr_tc,350,ACORD,Gibraltar,nation_abbr_tc-350@acord
nation_abbr_tc,351,ACORD,Portugal,nation_abbr_tc-351@acord
nation_abbr_tc,352,ACORD,Luxembourg,nation_abbr_tc-352@acord
nation_abbr_tc,353,ACORD,Ireland,nation_abbr_tc-353@acord
nation_abbr_tc,354,ACORD,Iceland,nation_abbr_tc-354@acord
nation_abbr_tc,355,ACORD,Albania,nation_abbr_tc-355@acord
nation_abbr_tc,356,ACORD,Malta,nation_abbr_tc-356@acord
nation_abbr_tc,357,ACORD,Cyprus,nation_abbr_tc-357@acord
nation_abbr_tc,358,ACORD,Finland,nation_abbr_tc-358@acord
nation_abbr_tc,359,ACORD,Bulgaria,nation_abbr_tc-359@acord
nation_abbr_tc,360,ACORD,Guernsey,nation_abbr_tc-360@acord
nation_abbr_tc,370,ACORD,Lithuania,nation_abbr_tc-370@acord
nation_abbr_tc,371,ACORD,Latvia,nation_abbr_tc-371@acord
nation_abbr_tc,372,ACORD,Estonia,nation_abbr_tc-372@acord
nation_abbr_tc,373,ACORD,Republic of Moldova,nation_abbr_tc-373@acord
nation_abbr_tc,374,ACORD,Armenia,nation_abbr_tc-374@acord
nation_abbr_tc,375,ACORD,Belarus,nation_abbr_tc-375@acord
nation_abbr_tc,376,ACORD,Andorra,nation_abbr_tc-376@acord
nation_abbr_tc,378,ACORD,San Marino,nation_abbr_tc-378@acord
nation_abbr_tc,380,ACORD,Ukraine,nation_abbr_tc-380@acord
nation_abbr_tc,385,ACORD,Croatia,nation_abbr_tc-385@acord
nation_abbr_tc,386,ACORD,Slovenia,nation_abbr_tc-386@acord
nation_abbr_tc,387,ACORD,Bosnia and Herzegovina,nation_abbr_tc-387@acord
nation_abbr_tc,389,ACORD,The Former Yugoslav Republic of Macedonia,nation_abbr_tc-389@acord
nation_abbr_tc,390,ACORD,Kosovo,nation_abbr_tc-390@acord
nation_abbr_tc,420,ACORD,Czech Republic,nation_abbr_tc-420@acord
nation_abbr_tc,421,ACORD,Slovakia,nation_abbr_tc-421@acord
nation_abbr_tc,423,ACORD,Liechtenstein,nation_abbr_tc-423@acord
nation_abbr_tc,441,ACORD,Bermuda,nation_abbr_tc-441@acord
nation_abbr_tc,473,ACORD,Grenada,nation_abbr_tc-473@acord
nation_abbr_tc,500,ACORD,Falkland Islands,nation_abbr_tc-500@acord
nation_abbr_tc,501,ACORD,Belize,nation_abbr_tc-501@acord
nation_abbr_tc,502,ACORD,Guatemala,nation_abbr_tc-502@acord
nation_abbr_tc,503,ACORD,El Salvador,nation_abbr_tc-503@acord
nation_abbr_tc,504,ACORD,Honduras,nation_abbr_tc-504@acord
nation_abbr_tc,505,ACORD,Nicaragua,nation_abbr_tc-505@acord
nation_abbr_tc,506,ACORD,Costa Rica,nation_abbr_tc-506@acord
nation_abbr_tc,508,ACORD,Saint Pierre and Miquelon,nation_abbr_tc-508@acord
nation_abbr_tc,509,ACORD,Haiti,nation_abbr_tc-509@acord
nation_abbr_tc,510,ACORD,Puerto Rico,nation_abbr_tc-510@acord
nation_abbr_tc,511,ACORD,US Virgin Islands,nation_abbr_tc-511@acord
nation_abbr_tc,512,ACORD,South Georgia and the South Sandwich Islands,nation_abbr_tc-512@acord
nation_abbr_tc,534,ACORD,Sint Maarten (Dutch Part),nation_abbr_tc-534@acord
nation_abbr_tc,535,ACORD,Bonaire Sint Eustatius and Saba,nation_abbr_tc-535@acord
nation_abbr_tc,590,ACORD,Guadeloupe,nation_abbr_tc-590@acord
nation_abbr_tc,591,ACORD,Bolivia,nation_abbr_tc-591@acord
nation_abbr_tc,592,ACORD,Guyana,nation_abbr_tc-592@acord
nation_abbr_tc,593,ACORD,Ecuador,nation_abbr_tc-593@acord
nation_abbr_tc,594,ACORD,French Guiana,nation_abbr_tc-594@acord
nation_abbr_tc,595,ACORD,Paraguay,nation_abbr_tc-595@acord
nation_abbr_tc,596,ACORD,Martinique,nation_abbr_tc-596@acord
nation_abbr_tc,597,ACORD,Suriname,nation_abbr_tc-597@acord
nation_abbr_tc,598,ACORD,Uruguay,nation_abbr_tc-598@acord
nation_abbr_tc,599,ACORD,Netherlands Antilles,nation_abbr_tc-599@acord
nation_abbr_tc,649,ACORD,Turks and Caicos Islands,nation_abbr_tc-649@acord
nation_abbr_tc,652,ACORD,Saint Barthelemy,nation_abbr_tc-652@acord
nation_abbr_tc,663,ACORD,Saint Martin (French Part),nation_abbr_tc-663@acord
nation_abbr_tc,664,ACORD,Montserrat,nation_abbr_tc-664@acord
nation_abbr_tc,671,ACORD,Guam,nation_abbr_tc-671@acord
nation_abbr_tc,672,ACORD,Antarctica,nation_abbr_tc-672@acord
nation_abbr_tc,673,ACORD,Brunei Darussalam,nation_abbr_tc-673@acord
nation_abbr_tc,674,ACORD,Nauru,nation_abbr_tc-674@acord
nation_abbr_tc,675,ACORD,Papua New Guinea,nation_abbr_tc-675@acord
nation_abbr_tc,676,ACORD,Tonga,nation_abbr_tc-676@acord
nation_abbr_tc,677,ACORD,Solomon Islands,nation_abbr_tc-677@acord
nation_abbr_tc,678,ACORD,Vanuatu,nation_abbr_tc-678@acord
nation_abbr_tc,679,ACORD,Fiji,nation_abbr_tc-679@acord
nation_abbr_tc,681,ACORD,Wallis and Futuna,nation_abbr_tc-681@acord
nation_abbr_tc,682,ACORD,Cook Islands,nation_abbr_tc-682@acord
nation_abbr_tc,683,ACORD,Niue,nation_abbr_tc-683@acord
nation_abbr_tc,684,ACORD,American Samoa,nation_abbr_tc-684@acord
nation_abbr_tc,686,ACORD,Kiribati,nation_abbr_tc-686@acord
nation_abbr_tc,687,ACORD,New Caledonia,nation_abbr_tc-687@acord
nation_abbr_tc,688,ACORD,Tuvalu,nation_abbr_tc-688@acord
nation_abbr_tc,689,ACORD,French Polynesia,nation_abbr_tc-689@acord
nation_abbr_tc,691,ACORD,Northern Mariana Islands,nation_abbr_tc-691@acord
nation_abbr_tc,693,ACORD,Palau,nation_abbr_tc-693@acord
nation_abbr_tc,694,ACORD,Marshall Islands,nation_abbr_tc-694@acord
nation_abbr_tc,695,ACORD,Federated States of Micronesia,nation_abbr_tc-695@acord
nation_abbr_tc,728,ACORD,South Sudan,nation_abbr_tc-728@acord
nation_abbr_tc,758,ACORD,Saint Lucia,nation_abbr_tc-758@acord
nation_abbr_tc,767,ACORD,Dominica,nation_abbr_tc-767@acord
nation_abbr_tc,784,ACORD,Saint Vincent and the Grenadines,nation_abbr_tc-784@acord
nation_abbr_tc,809,ACORD,Dominican Republic,nation_abbr_tc-809@acord
nation_abbr_tc,852,ACORD,Hong Kong,nation_abbr_tc-852@acord
nation_abbr_tc,853,ACORD,Macao,nation_abbr_tc-853@acord
nation_abbr_tc,855,ACORD,Cambodia,nation_abbr_tc-855@acord
nation_abbr_tc,856,ACORD,Lao People's Democratic Republic,nation_abbr_tc-856@acord
nation_abbr_tc,868,ACORD,Trinidad and Tobago,nation_abbr_tc-868@acord
nation_abbr_tc,869,ACORD,Saint Kitts and Nevis,nation_abbr_tc-869@acord
nation_abbr_tc,876,ACORD,Jamaica,nation_abbr_tc-876@acord
nation_abbr_tc,880,ACORD,Bangladesh,nation_abbr_tc-880@acord
nation_abbr_tc,886,ACORD,Taiwan Province of China,nation_abbr_tc-886@acord
nation_abbr_tc,950,ACORD,Myanmar,nation_abbr_tc-950@acord
nation_abbr_tc,951,ACORD,Republic of Korea,nation_abbr_tc-951@acord
nation_abbr_tc,952,ACORD,Democratic People's Republic of Korea,nation_abbr_tc-952@acord
nation_abbr_tc,961,ACORD,Lebanon,nation_abbr_tc-961@acord
nation_abbr_tc,962,ACORD,Jordan,nation_abbr_tc-962@acord
nation_abbr_tc,963,ACORD,Syrian Arab Republic,nation_abbr_tc-963@acord
nation_abbr_tc,964,ACORD,Iraq,nation_abbr_tc-964@acord
nation_abbr_tc,965,ACORD,Kuwait,nation_abbr_tc-965@acord
nation_abbr_tc,966,ACORD,Saudi Arabia,nation_abbr_tc-966@acord
nation_abbr_tc,967,ACORD,Yemen,nation_abbr_tc-967@acord
nation_abbr_tc,968,ACORD,Oman,nation_abbr_tc-968@acord
nation_abbr_tc,971,ACORD,United Arab Emirates,nation_abbr_tc-971@acord
nation_abbr_tc,972,ACORD,Israel,nation_abbr_tc-972@acord
nation_abbr_tc,973,ACORD,Bahrain,nation_abbr_tc-973@acord
nation_abbr_tc,974,ACORD,Qatar,nation_abbr_tc-974@acord
nation_abbr_tc,975,ACORD,Bhutan,nation_abbr_tc-975@acord
nation_abbr_tc,977,ACORD,Nepal,nation_abbr_tc-977@acord
nation_abbr_tc,992,ACORD,Tajikistan,nation_abbr_tc-992@acord
nation_abbr_tc,993,ACORD,Turkmenistan,nation_abbr_tc-993@acord
nation_abbr_tc,994,ACORD,Azerbaijan,nation_abbr_tc-994@acord
nation_abbr_tc,995,ACORD,Georgia,nation_abbr_tc-995@acord
nation_abbr_tc,998,ACORD,Uzbekistan,nation_abbr_tc-998@acord
nation_abbr_tc,1001,ACORD,Anguilla,nation_abbr_tc-1001@acord
nation_abbr_tc,1002,ACORD,Panama (also known as Canal Zone),nation_abbr_tc-1002@acord
nation_abbr_tc,1003,ACORD,Cote d'Ivoire,nation_abbr_tc-1003@acord
nation_abbr_tc,1004,ACORD,Eritrea,nation_abbr_tc-1004@acord
nation_abbr_tc,1005,ACORD,Kazakhstan,nation_abbr_tc-1005@acord
nation_abbr_tc,1006,ACORD,Kyrgyzstan,nation_abbr_tc-1006@acord
nation_abbr_tc,1007,ACORD,Cocos (Keeling) Islands,nation_abbr_tc-1007@acord
nation_abbr_tc,1008,ACORD,Mongolia,nation_abbr_tc-1008@acord
nation_abbr_tc,1009,ACORD,Bouvet Island,nation_abbr_tc-1009@acord
nation_abbr_tc,1010,ACORD,Seychelles,nation_abbr_tc-1010@acord
nation_abbr_tc,1011,ACORD,British Indian Ocean Territory,nation_abbr_tc-1011@acord
nation_abbr_tc,1013,ACORD,Samoa,nation_abbr_tc-1013@acord
nation_abbr_tc,1014,ACORD,Timor-Leste,nation_abbr_tc-1014@acord
nation_abbr_tc,1015,ACORD,French Southern Territories,nation_abbr_tc-1015@acord
nation_abbr_tc,1016,ACORD,Heard Island and McDonald Islands,nation_abbr_tc-1016@acord
nation_abbr_tc,1017,ACORD,Mayotte,nation_abbr_tc-1017@acord
nation_abbr_tc,1018,ACORD,Pitcairn,nation_abbr_tc-1018@acord
nation_abbr_tc,1019,ACORD,Svalbard and Jan Mayen,nation_abbr_tc-1019@acord
nation_abbr_tc,1020,ACORD,Tokelau,nation_abbr_tc-1020@acord
nation_abbr_tc,1021,ACORD,United States Minor Outlying Islands,nation_abbr_tc-1021@acord
nation_abbr_tc,1022,ACORD,Western Sahara,nation_abbr_tc-1022@acord
nation_abbr_tc,1023,ACORD,Maldives,nation_abbr_tc-1023@acord
nation_abbr_tc,1024,ACORD,Christmas Island,nation_abbr_tc-1024@acord
nation_abbr_tc,1025,ACORD,Norfolk Island,nation_abbr_tc-1025@acord
nation_abbr_tc,1026,ACORD,Curacao,nation_abbr_tc-1026@acord
nation_abbr_tc,1027,ACORD,Congo,nation_abbr_tc-1027@acord
nation_abbr_tc,1028,ACORD,Monaco,nation_abbr_tc-1028@acord
nation_abbr_tc,1029,ACORD,Holy See (Vatican City State),nation_abbr_tc-1029@acord
nation_abbr_tc,1031,ACORD,Swaziland,nation_abbr_tc-1031@acord
nation_abbr_tc,1032,ACORD,Occupied Palestinian Territory,nation_abbr_tc-1032@acord
nation_abbr_tc,1034,ACORD,Jersey,nation_abbr_tc-1034@acord
nation_abbr_tc,1035,ACORD,Isle of Man,nation_abbr_tc-1035@acord
nation_abbr_tc,1036,ACORD,Serbia,nation_abbr_tc-1036@acord
nation_abbr_tc,1037,ACORD,Montenegro,nation_abbr_tc-1037@acord
nation_abbr_tc,1038,ACORD,North Yemen,nation_abbr_tc-1038@acord
nation_abbr_tc,1039,ACORD,South Yemen,nation_abbr_tc-1039@acord
nation_abbr_tc,1040,ACORD,Union of Soviet Socialist Republics,nation_abbr_tc-1040@acord
nation_abbr_tc,2147483647,ACORD,Other,nation_abbr_tc-2147483647@acord
