RoleName,Key
Accountant,accountantsclient-accountant
Accountant's Client,accountant-accountantsclient
Adopted Child,adoptiveparent-adoptedchild
Adopted Daughter,adoptiveparent-adoptedchild
Adopted Son,adoptiveparent-adoptedchild
Adoptive Brother,adoptivesibling-adoptivesibling
Adoptive Father,adoptedchild-adoptiveparent
Adoptive Mother,adoptedchild-adoptiveparent
Adoptive Parent,adoptedchild-adoptiveparent
Adoptive Sibling,adoptivesibling-adoptivesibling
Adoptive Sister,adoptivesibling-adoptivesibling
Advisee,advisor-advisee
Advisor,advisee-advisor
Assistant,assistee-assistant
Assistee,assistant-assistee
Attorney,attorneysclient-attorney
Attorney's Client,attorney-attorneysclient
Banker,bankerof-banker
Banker of,banker-bankerof
Board Member,boardmember-boardmember
Brother,sibling-sibling
Brother-in-law,siblinginlaw-siblinginlaw
Business,business-business
Business Associate,businessassociate-businessassociate
Business Contact,contactw/business-businesscontact
Child,parent-child
Child-in-Law,parentsinlaw-childinlaw
Common Law Husband,commonlawspouse-commonlawspouse
Common Law Spouse,commonlawspouse-commonlawspouse
Common Law Wife,commonlawspouse-commonlawspouse
Contact w/ Business,businesscontact-contactw/business
Creditor,creditorof-creditor
Creditor Of,creditor-creditorof
Daughter,parent-child
Daughter-in-law,parentsinlaw-childinlaw
Employee,employer-employee
Employer,employee-employer
Ex-husband,formerspouse-formerspouse
Ex-wife,formerspouse-formerspouse
Father,child-parent
Father-in-law,childinlaw-parentsinlaw
Fiancé (male),fiancé-fiancée
Fiancée (engaged female),fiancée-fiancé
Former Spouse,formerspouse-formerspouse
Foster Brother,fostersibling-fostersibling
Foster Child,fosterparent-fosterchild
Foster Daughter,fosterparent-fosterchild
Foster Father,fosterchild-fosterparent
Foster Mother,fosterchild-fosterparent
Foster Parent,fosterchild-fosterparent
Foster Sibling,fostersibling-fostersibling
Foster Sister,fostersibling-fostersibling
Foster Son,fosterparent-fosterchild
God Child,godparent-godchild
God Daughter,godparent-godchild
God Father,godchild-godparent
God Mother,godchild-godparent
God Parent,godchild-godparent
God Son,godparent-godchild
Grandchild,grandparent-grandchild
Granddaughter,grandparent-grandchild
Grandfather,grandchild-grandparent
Grandmother,grandchild-grandparent
Grandparent,grandchild-grandparent
Grandson,grandparent-grandchild
Grantee,grantor-grantee
Grantor,grantee-grantor
Great Grandchild,greatgrandparent-greatgrandchild
Great Granddaughter,greatgrandparent-greatgrandchild
Great Grandfather,greatgrandchild-greatgrandparent
Great Grandmother,greatgrandchild-greatgrandparent
Great Grandparent,greatgrandchild-greatgrandparent
Great Grandson,greatgrandparent-greatgrandchild
Half Brother,halfsibling-halfsibling
Half Sibling,halfsibling-halfsibling
Half Sister,halfsibling-halfsibling
Husband,spouse-spouse
Mentor,mentoredby-mentor
Mentored By,mentor-mentoredby
Mother,child-parent
Mother-in-law,childinlaw-parentsinlaw
Nominator,referral-nominator
Non Relative,nonrelative-nonrelative
Other,other-other
Parent,child-parent
Parents-in-law,childinlaw-parentsinlaw
Partner,partner-partner
Referral,nominator-referral
Sibling,sibling-sibling
Sibling in Law,siblinginlaw-siblinginlaw
Sister,sibling-sibling
Sister-in-law,siblinginlaw-siblinginlaw
Son,parent-child
Son-in-law,parentsinlaw-childinlaw
Spouse,spouse-spouse
Step Brother,stepsibling-stepsibling
Step Daughter,stepparent-stepchild
Step Father,stepchild-stepparent
Step Mother,stepchild-stepparent
Step Parent,stepchild-stepparent
Step Sister,stepsibling-stepsibling
Step Son,stepparent-stepchild
Step-Child,stepparent-stepchild
Step-Sibling,stepsibling-stepsibling
Wife,spouse-spouse
Unknown,unknown-unknown