Relationship Role Name,Category,To Role,From Role,Relationship Role Name  Key,Reciprocal Role Key
Accountant,Business,Accountant,Accountant's Client,accountantsclient-accountant,accountant-accountantsclient
Advisee,Business,Advisee,Advisor,advisor-advisee,advisee-advisor
Assistant,Business,Assistant,Assistee,assistee-assistant,assistant-assistee
Attorney,Business,Attorney,Attorney's Client,attorneysclient-attorney,attorney-attorneysclient
Banker,Business,Banker,Banker of,bankerof-banker,banker-bankerof
Board Member,Business,Board Member,Board Member,boardmember-boardmember,boardmember-boardmember
Business,Business,Business,Business,business-business,business-business
Business Associate,Business,Business Associate,Business Associate,businessassociate-businessassociate,businessassociate-businessassociate
Business Contact,Business,Business Contact,Contact w/ Business,contactw/business-businesscontact,businesscontact-contactw/business
Creditor,Business,Creditor,Creditor Of,creditorof-creditor,creditor-creditorof
Employee,Business,Employee,Employer,employer-employee,employee-employer
Grantee,Business,Grantee,Grantor,grantor-grantee,grantee-grantor
Mentor,Business,Mentor,Mentored By,mentoredby-mentor,mentor-mentoredby
Non Relative,Business,Non Relative,Non Relative,nonrelative-nonrelative,nonrelative-nonrelative
Partner,Business,Partner,Partner,partner-partner,partner-partner
Referral,Business,Referral,Nominator,nominator-referral,referral-nominator
Other,Other,Other,Other,other-other,other-other
Accountant's Client,Business,Accountant's Client,Accountant,accountant-accountantsclient,accountantsclient-accountant
Advisor,Business,Advisor,Advisee,advisee-advisor,advisor-advisee
Assistee,Business,Assistee,Assistant,assistant-assistee,assistee-assistant
Attorney's Client,Business,Attorney's Client,Attorney,attorney-attorneysclient,attorneysclient-attorney
Banker of,Business,Banker of,Banker,banker-bankerof,bankerof-banker
Contact w/ Business,Business,Contact w/ Business,Business Contact,businesscontact-contactwbusiness,contactwbusiness-businesscontact
Creditor Of,Business,Creditor Of,Creditor,creditor-creditorof,creditorof-creditor
Employer,Business,Employer,Employee,employee-employer,employer-employee
Grantor,Business,Grantor,Grantee,grantee-grantor,grantor-grantee
Mentored By,Business,Mentored By,Mentor,mentor-mentoredby,mentoredby-mentor
Nominator,Business,Nominator,Referral,referral-nominator,nominator-referral
Adopted Child,Family,Adopted Child,Adoptive Parent,adoptiveparent-adoptedchild,adoptedchild-adoptiveparent
Adoptive Sibling,Family,Adoptive Sibling,Adoptive Sibling,adoptivesibling-adoptivesibling,adoptivesibling-adoptivesibling
Child,Family,Child,Parent,parent-child,child-parent
Child-in-Law,Family,Child-in-Law,Parents-in-law,parentsinlaw-childinlaw,childinlaw-parentsinlaw
Common Law Spouse,Family,Common Law Spouse,Common Law Spouse,commonlawspouse-commonlawspouse,commonlawspouse-commonlawspouse
Companion,Family,Companion,Companion,companion-companion,companion-companion
Dependent,Family,Dependent,Legal Guardian,legalguardian-dependent,legalward-legalguardian
Disabled Adult Dependent,Family,Disabled Adult Dependent,Disabled Adult Dependent,disabledadultdependent-disabledadultdependent,disabledadultdependent-disabledadultdependent
Domestic Partner,Family,Domestic Partner,Domestic Partner,domesticpartner-domesticpartner,domesticpartner-domesticpartner
Family,Family,Family,Family,family-family,family-family
Former Spouse,Family,Former Spouse,Former Spouse,formerspouse-formerspouse,formerspouse-formerspouse
Foster Child,Family,Foster Child,Foster Parent,fosterparent-fosterchild,fosterchild-fosterparent
Foster Sibling,Family,Foster Sibling,Foster Sibling,fostersibling-fostersibling,fostersibling-fostersibling
Fiancé,Family,Fiancé,Fiancée,fiancée-fiancé,fiancé-fiancée
Fiancée,Family,Fiancée,Fiancé,fiancé-fiancée,fiancée-fiancé
Friend,Family,Friend,Friend,friend-friend,friend-friend
God Child,Family,God Child,God Parent,godparent-godchild,godchild-godparent
Grandchild,Family,Grandchild,Grandparent,grandparent-grandchild,grandchild-grandparent
Great Grandchild,Family,Great Grandchild,Great Grandparent,greatgrandparent-greatgrandchild,greatgrandchild-greatgrandparent
Half Sibling,Family,Half Sibling,Half Sibling,halfsibling-halfsibling,halfsibling-halfsibling
Legal Guardian,Family,Legal Guardian,Legal Ward,legalward-legalguardian,legalguardian-legalward
Roommate,Family,Roommate,Roommate,roommate-roommate,roommate-roommate
Sibling in Law,Family,Sibling in Law,Sibling in Law,siblinginlaw-siblinginlaw,siblinginlaw-siblinginlaw
Sibling,Family,Sibling,Sibling,sibling-sibling,sibling-sibling
Spouse,Family,Spouse,Spouse,spouse-spouse,spouse-spouse
Step Parent,Family,Step Parent,Step-Child,stepchild-stepparent,stepparent-stepchild
Step-Sibling,Family,Step-Sibling,Step-Sibling,stepsibling-stepsibling,stepsibling-stepsibling
Cousin,Family,Cousin,Cousin,cousin-cousin,cousin-cousin
Boy Friend,Family,Boy Friend,Girl Friend,girlfriend-boyfriend,boyfriend-girlfriend
Adoptive Parent,Family,Adoptive Parent,Adopted Child,adoptedchild-adoptiveparent,adoptiveparent-adoptedchild
Parent,Family,Parent,Child,child-parent,parent-child
Parents-in-law,Family,Parents-in-law,Child-in-Law,childinlaw-parentsinlaw,parentsinlaw-childinlaw
Legal Guardian,Family,Legal Guardian,Dependent,dependent-legalguardian,legalguardian-dependent
Foster Parent,Family,Foster Parent,Foster Child,fosterchild-fosterparent,fosterparent-fosterchild
God Parent,Family,God Parent,God Child,godchild-godparent,godparent-godchild
Grandparent,Family,Grandparent,Grandchild,grandchild-grandparent,grandparent-grandchild
Great Grandparent,Family,Great Grandparent,Great Grandchild,greatgrandchild-greatgrandparent,greatgrandparent-greatgrandchild
Legal Ward,Family,Legal Ward,Legal Guardian,legalguardian-legalward,legalward-legalguardian
Step-Child,Family,Step-Child,Step Parent,stepparent-stepchild,stepchild-stepparent
Girl Friend,Family,Girl Friend,Boy Friend,boyfriend-girlfriend,girlfriend-boyfriend
Unknown,Other,Unknown,Unknown,unknown-unknown,unknown-unknown