{
    "insuranceapp" : [
        "iGOEntitySyncPlugin.InsuranceAppFormatter",
        "iGOEntitySyncPlugin.InsuranceAppMapper",
        "iGOEntitySyncPlugin.InsuranceAppNormalizer"
    ],
    "illustration" : [
        "iGOEntitySyncPlugin.IllustrationNormalizer",
        "iGOEntitySyncPlugin.IllustrationMapper"
    ],
    "policyservice" : [
        "iGOEntitySyncPlugin.PolicyServiceMapper"
    ],
    "needsanalysis" : [
        "iGOEntitySyncPlugin.InsuranceAppFormatter",
        "iGOEntitySyncPlugin.NeedsAnalysisMapper",
        "iGOEntitySyncPlugin.NeedsAnalysisNormalizer"
    ]
}