{
    "NewIllustrationEntry": {
        "relatedEntryMap": null,
        "relatedEntryListMap": null,
        "objectType": "illustration__c",
        "id": null,
        "fieldMap": {
            "external_id__c": {
                "value": null,
                "name": "external_id__c"
            },
            "sourcetext__c": {
                "value": "iGO",
                "name": "SourceText__c"
            },
            "source__c": {
                "value": "iGO",
                "name": "Source__c"
            },
            "accelerated_death_benefit__c": {
                "value": "True",
                "name": null
            },
            "accidental_death_benefit__c": {
                "value": "True",
                "name": null
            },
            "additional_insured_rider__c": {
                "value": "True",
                "name": null
            },
            "amount1035__c": {
                "value": "1736476",
                "name": null
            },
            "annual_premium__c": {
                "value": null,
                "name": null
            },
            "children_s_benefit_rider__c": {
                "value": "True",
                "name": null
            },
            "coverage_amount__c": {
                "value": null,
                "name": null
            },
            "disability_benefitamount__c": {
                "value": null,
                "name": null
            },
            "disability_occupation__c": {
                "value": null,
                "name": null
            },
            "modal_premium__c": {
                "value": null,
                "name": null
            },
            "non_1035_amount__c": {
                "value": "",
                "name": null
            },
            "product_code__c": {
                "value": null,
                "name": null
            },
            "product_name__c": {
                "value": null,
                "name": null
            },
            "waiver_of_premium__c": {
                "value": "True",
                "name": null
            },
            "avoid_a_mec__c": {
                "value": null,
                "name": null
            },
            "death_benefit_option__c": {
                "value": null,
                "name": null
            },
            "disability_benefitmode__c": {
                "value": null,
                "name": null
            },
            "disability_benefitperiod__c": {
                "value": null,
                "name": null
            },
            "disability_eliminationperiod__c": {
                "value": null,
                "name": null
            },
            "disability_occupationclass__c": {
                "value": null,
                "name": null
            },
            "interest_basis__c": {
                "value": null,
                "name": null
            },
            "issue_state__c": {
                "value": "Arkansas",
                "name": null
            },
            "mode__c": {
                "value": null,
                "name": null
            },
            "product_type_name__c": {
                "value": "Whole Life",
                "name": null
            },
            "solve_for__c": {
                "value": null,
                "name": null
            },
            "underwriting_class__c": {
                "value": null,
                "name": null
            }
        },
        "externalId": null,
        "primaryInsured": null,
        "insuranceCase": {
            "relatedEntryMap": null,
            "relatedEntryListMap": null,
            "objectType": "insurancecase__c",
            "id": "a0W360000029gJGEAY",
            "fieldMap": null,
            "externalId": null
        }
    }
}