{
    "SyncRecord" : {
        "INSURANCECASEID": "a0M61000001C23KEAS" 
    },
    "SyncPDF" : {
        "relatedEntryMap": {},
        "relatedEntryListMap": {},
        "objectType": "fact_finder__c",
        "id": null,
        "fieldMap": {
            "name": {
                "value": "Need Analysis Result"
            },
            "insurancecase__c": {
                "value": "need value"
            },
            "external_id__c": {
                "value": "fc0b300f-8181-4fac-b84b-5d2e545e5359"
            }
        },
        "externalId": null    
    }
}